### ISSUE TITLE
Sass not compiling

### ISSUE THREAD

**Issue by CarterStevens1** [glenn2223/vscode-live-sass-compiler#100]
```
Command called: "liveSass.command.watchMySass"
--------------------
Starting to compile all files
--------------------
Changing status bar to: "Working on it..."
--------------------
Getting SASS files
Query pattern: **/[^_]*.s[a|c]ss
Can be overwritten: true
--------------------
Checking folder 1 of 1
Folder: Jay Art bio
--------------------
No base folder override found. Keeping workspace folder
--------------------
Found 1 SASS files
--------------------
Compiling Sass/Scss Files: 
e:\repos\Jay Art bio\style.scss
--------------------
Starting file 1 of 1
Path: e:\repos\Jay Art bio\style.scss
--------------------
Starting format 1 of 1
Settings: {"format":"expanded","extensionName":".css","savePath":null}
--------------------
Calculating file paths
Calculating the save paths for the css and map output files
Originating path: e:\repos\Jay Art bio\style.scss
--------------------
Searching for workspace
Need to find a workspace folder that holds the file
--------------------
Workspace has folder
Searching for the workspace folder where this file is located
Path: e:\repos\Jay Art bio\style.scss
--------------------
Checking folder 1 of 1
Folder: Jay Art bio
MATCH
--------------------
Using: e:\repos\Jay Art bio
--------------------
Starting compilation
Starting compilation of file
Path: e:\repos\Jay Art bio\style.scss
--------------------
Autoprefixer isn't false, applying to file
Path: e:\repos\Jay Art bio\style.scss
--------------------
Preparing autoprefixer
--------------------
Changing BROWSERSLIST_DISABLE_CACHE setting
Was: undefined
Now: 1
--------------------
Starting autoprefixer
--------------------
Completed autoprefixer
--------------------
Restored BROWSERSLIST_DISABLE_CACHE to: undefined
--------------------
Saving file
Saving a file to the system
Target: e:\repos\Jay Art bio\style.css.map
--------------------
Saving file
Saving a file to the system
Target: e:\repos\Jay Art bio\style.css
--------------------
Generated:
Changing status bar to: Success
Registered timeout to switch state back
--------------------
e:\repos\Jay Art bio\style.css.map
e:\repos\Jay Art bio\style.css
--------------------
Switching UI state
--------------------
Changing status bar to: Watching
--------------------
Watching...
--------------------
Switching UI state
--------------------
Changing status bar to: Watching
--------------------
Watching...
--------------------
Firing timeout function to switch back
--------------------
Changing status bar to: Watching
--------------------
```

**Comment by CarterStevens1** [comment]
This is the only output i get on scss file change. This doesnt send the change to the css file


 - VS Code event: "onDidSaveTextDocument"
--------------------

**Comment by glenn2223** [comment]
The only it doesn't output after that point is if the file isn't a SASS file. I have copied the code below - this is the checks that the code performs. 

FYI: `fileName` is the full path of the file that we are checking and `partialSass` is an argument that, in this case, is `true`.
```JS
return (
    (partialSass || !filename.startsWith("_")) &&
    (filename.endsWith("sass") || filename.endsWith("scss"))
);
```

What is the name and extension of the file you're saving? 

Does it output the same message again when you save once more? *It should do so every time you save anything in your project tbh.*

**Comment by CarterStevens1** [comment]
Hi, so ive tried it with a file named _style.scss in a new vs code window and also with standard style.scss in my project but none are working correctly. it doesnt update the css on save at all only on the odd occasion where i delete something it randomly works then stops updating.
at the moment it only works on a forced compile when i click watch sass after turning off.

i get this print whenever i make a change VS Code event: "onDidSaveTextDocument"
--------------------

This started happening about 2 days ago now.

Ive tried rolling back to a previous update also but to no avail.

**Comment by glenn2223** [comment]
Can you try the below, that is if it's the same issue as #96 

---

I believe I have identified the issue. Can you see if [v5.1.0-rc.2](https://github.com/glenn2223/vscode-live-sass-compiler/releases/tag/v5.1.0-rc.2) fixes your issue. 

You can see installation instruction [here](https://github.com/glenn2223/vscode-live-sass-compiler/issues/84)

Thanks

**Comment by CarterStevens1** [comment]
I tried the update yesterday but it didn't work for me! 
It started not compiling since about 3 days ago where I made an extra scss file in one of my workspaces for my project started playing up and not updating so I deleted the extra scss file I had made and still was not working

**Comment by glenn2223** [comment]
Can you please run `liveSass.command.debugFileList` and paste the output here. Thanks

**Comment by glenn2223** [comment]
>Can you please run `liveSass.command.debugFileList` and paste the output here. Thanks


Hey @CarterStevens1, have you had a chance to rn the above?

**Comment by CarterStevens1** [comment]
hi glenn,

I haven't unfortunately i have switched to using a bat file instead and running it through the terminal as nothing was working for me!

**Comment by glenn2223** [comment]
No problem. I will close this issue for now as more info is required
