### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by hamerstandr** [glenn2223/vscode-live-sass-compiler#103]
- Issue Type: `Bug`
- Extension Name: `live-sass`
- Extension Version: `5.0.4`
- OS Version: `Windows_NT x64 10.0.22000`
- VS Code version: `1.57.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by glenn2223** [comment]
Please paste the data from your clipboard. Thanks

**Comment by glenn2223** [comment]
Closing as more info required
