### ISSUE TITLE
autoprefix doesn't work

### ISSUE THREAD

**Issue by Santeenee** [glenn2223/vscode-live-sass-compiler#104]
![image](https://user-images.githubusercontent.com/65949803/124821692-537d0c00-df6f-11eb-960c-e598e26b64e9.png)

These are my settings in the .vscode folder. 

I don't understand why vendor prefixes aren't applied in the styles.css as expected.

Ex.: If I write "justify-content: space-evenly;" in a simple styles.scss file, 
I don't get "-ms-flex-pack: space-evenly;" 
and the other vendor prefixes that I expect 
(as the original version of this extension does)

**Comment by glenn2223** [comment]
>"Developers are often surprised by how few prefixes are required today. If Autoprefixer doesn’t add prefixes to your CSS, check if they’re still required on [Can I Use](https://caniuse.com/)."
> ~ from [autoprefixer faq](https://github.com/postcss/autoprefixer#why-doesnt-autoprefixer-add-prefixes-to-border-radius)

Although the FAQ is related to `border-radius`, the point applies globally

The basic summary of it is that; if it isn't doing it, you don't need it

However, that's said, if you need to target older browsers then you should be adding those extra browsers to your `autoprefixer` setting - something like `["defaults","IE10"]`

**Comment by Santeenee** [comment]
Typo: it's "IE 10" not "IE10"

Example:
{
"liveSassCompile.settings.autoprefix": ["defaults","IE 10"]  
}

Thank you for keeping this extension alive!

**Comment by glenn2223** [comment]
> Typo: it's "IE 10" not "IE10"

Sorry, my bad. Thanks for pointing it out - I have fixed it
