### ISSUE TITLE
Error with comments when compiling in css

### ISSUE THREAD

**Issue by WebNeil** [glenn2223/vscode-live-sass-compiler#105]
![image](https://user-images.githubusercontent.com/84662174/125440435-93f4b031-2ee8-4e50-aaec-abf3c96fd63c.png)
![image](https://user-images.githubusercontent.com/84662174/125440751-9343c436-c3ab-4c97-b41c-58b293ee09ba.png)
The comment moves down for some reason

**Comment by glenn2223** [comment]
It seems that `@use` isn't called inline but rather included before any code output - see below. This may be how it's only placed  in the output file once 🤷‍♂️

>⚠️ Heads up!
>A stylesheet’s `@use` rules must come before any rules other than `@forward`, including style rules. However, you can declare variables before `@use` rules to use when configuring modules.
>    -- SASS: https://sass-lang.com/documentation/at-rules/use

You will be better opening an issue at [sass/dart-sass](https://github.com/sass/dart-sass)
