### ISSUE TITLE
Compiled CSS unlinks the bootstrap from html

### ISSUE THREAD

**Issue by tvrhossain** [glenn2223/vscode-live-sass-compiler#109]
At first, thank u for the fork. As I need to @import bootstrap.scss file into the style.scss, every time the scss is compiled into css (watch scss), the compiled css file also have the same import bootstrap.scss statement, which in turn unlink the bootstrap.css file from my html, because I link the compiled css file in the html and import the bootstrap.css there. I m not sure if I making any mistake here but plz have a look at my setting. I m using npm and bootstrap. 

Style.scss
![style scss](https://user-images.githubusercontent.com/6359871/126875553-fb219176-a267-43e6-8701-9cd27667852d.png)

The Compiled Css (which has bootstrap). This **@import statement will be replaced, once the file is compiled**. hence it unlinks the html from bootstrap.css. (One workaround is importing both scss and css file in scss file, so that it compiles both import in this compiled css file, but importing css in scss file is redundant) 
![compiledCss](https://user-images.githubusercontent.com/6359871/126875569-1d969871-4166-49f5-94cd-afef1f55b0df.png)

![Index](https://user-images.githubusercontent.com/6359871/126875574-f1f8b5cb-b66f-4a15-b3b4-5082c37631e7.png)

**Comment by glenn2223** [comment]
CSS actually supports `@import` statements, see [here](https://sass-lang.com/documentation/at-rules/import)

So that, technically, is valid CSS. It's down to the browser to load the next url, and the next... and so on

If I remember correctly you need to remove the `url` and parenthesis

---

There's also a note on that page about using node modules

**Comment by glenn2223** [comment]
Hey @tvrhossain , did my comment help at all? Can I close this issue?

**Comment by glenn2223** [comment]
Closing - more info required
