### ISSUE TITLE
Changes to a referenced file don't trigger main file to recompile

### ISSUE THREAD

**Issue by real-didi** [glenn2223/vscode-live-sass-compiler#111]
I have a problem getting main file recompiled after making changes to referenced styles.

Steps to reproduce:

Create _style.scss_
`@use 'style.included';`

And _style.included.scss_
`body {
    background-color: blue;
}`

Start 'Watch Sass' and make changes to _style.included.scss_ , 
for example change it to `body {
    background-color: black;
}` and save it.

Result: only _style.included.scss_ gets recompiled.
![Screenshot 2021-08-04 202617](https://user-images.githubusercontent.com/1590757/128208765-6107a781-cf46-4ac1-9075-5b0c21d93698.png)

**Comment by glenn2223** [comment]
Hey @real-didi, glad you're trying the extension.

SASS partials are traditionally started with an underscore (`_`).  When Ritwick originally created this project he had this heavily influence the code. So when a file starts with an underscore it is not compiled, but rather compiles all possible files - those without an underscore. And, on the reverse of that, when a file without underscore is saved it should just be that files that is compiled.

Another point about this extension is that it doesn't parse the SASS stylesheet but rather just passes it to the compiler - this means that the extension doesn't actually know which files are linked to which.

I hope this makes sense and explains why it isn't working as expected

---

Going to close for two reasons
- it's, kind of, related to #17 - in the fact of knowing which files link to which
- also, any non-underscored file name will have to output a file , unless we start having settings that say which individual files should output and which shouldn't
