### ISSUE TITLE
QUESTION: Some questions and recommendations

### ISSUE THREAD

**Issue by morrow95** [glenn2223/vscode-live-sass-compiler#113]
I'm coming from using a standalone app (Koala) to compile and minimize my scss and js files.  Bear with me for being a noob using extensions with it and setting things up.

So I have it installed, setup, and working :

.code-workspace
```
{
	"folders": [
		{
			"path": "."
		}
	],
	"settings": {
		"liveSassCompile.settings.watchOnLaunch": true
	}
}
```

settings.json in .vscode folder
```
{
    "liveSassCompile.settings.includeItems": [
        "/_config/scss/*"
    ]
    "liveSassCompile.settings.formats":[
       {
            "format": "compressed",
            "extensionName": ".css",
            "savePath": "/assets/css"
       }
    ],
    "liveSassCompile.settings.generateMap": false,
    "liveSassCompile.settings.autoprefix": [
        false
   ]
}
```

One thing I am curious about is some of my projects have two different folders to watch with different output/save locations.  In the above I used `liveSassCompile.settings.includeItems` to specify only one folder to watch.  How would I go about specifying two different folders each with a different `liveSassCompile.settings.formats` settings?  For example I want to watch "/_config/scss/*" and save to "/assets/css" and also watch "/admin/_config/scss/*" and save to "/admin/css".

Second is what do some of you recommend for js?  I'd basically like the same functionality that live sass provides, but for javascript files.

**Comment by glenn2223** [comment]
>I want to watch "/_config/scss/" and save to "/assets/css" and also watch "/admin/_config/scss/" and save to "/admin/css"

As you having two different output paths, it wouldn't be possible to do this.

Even though you have a workspace, I'm assuming that there's only one root folder included with a structure similar to that shown below?
```
WORKSPACE / TOP LEVEL FOLDER
↳ _config
    ↳ scss
↳ admin
    ↳ _config
        ↳ scss
    ↳ css
↳ assets
    ↳css
```
If so, I don't believe you can have `admin` as another `"folders"` in your workspace file to allow multi-root settings. Though you may be able to, so maybe give it a whirl.

However, if you can change your structure so the admin output is `/admin/assets/css` then you could have the `savePath` as `~/../assets/css`. This means, relative to the file that's being compiled, go up a folder and save to the path `/assets/css`.

---

>Second is what do some of you recommend for js? I'd basically like the same functionality that live sass provides, but for javascript files.

Sorry, I can't recommend anything. Most of the time I use a gulp file with some npm packages to compile various TS files I have. However, there may be something out there.

TBH, from my experience, the whole JS module compilation could do with a half-decent extension. There's so much more that can be done around it - I have some vague ideas but nothing that will be a working extension any time soon (just so busy atm - uni studies, family life, full-time work 😫 😂)

**Comment by morrow95** [comment]
@glenn2223 Appreciate the response.  Yeah, I can't believe I am having such a hard time finding solutions for things that are what I would consider 'standard practice' for any web dev - compile/minify css/js and minify html before uploading.  There is stuff out there I'm finding, but not maintained/updated or have other issues.  With my current outdated/deprecated setup I can edit as I please and all css/js changes are compiled/minimized on save/edit then when I upload the html is minimized on the fly and keeps the original files as is for easy editing on my end - easy and painless, but doesn't support newer coding coming out.

**Comment by glenn2223** [comment]
>Yeah, I can't believe I am having such a hard time finding solutions for things that are what I would consider 'standard practice' for any web dev

Yeah, I completely agree

>There is stuff out there I'm finding, but not maintained/updated or have other issues.

I suppose that's the issue with open source - projects being dropped because the contributers can no longer maintain or can't put the hours in/don't get the support, etc, etc.
