### ISSUE TITLE
savePath not working

### ISSUE THREAD

**Issue by canuckkat** [glenn2223/vscode-live-sass-compiler#114]
I have a refresh install v5.1.0 . VSCode tells me it was updated 5 days ago (August 7 or so).

My .vscode
```
{
     "liveSassCompile.settings.formats":[
        {
            "format": "expanded",
            "extensionName": ".css",
            "savePath": "/src/css"
        },
        {
            "extensionName": ".min.css",
            "format": "compressed",
            "savePath": "/dist/css"
        }
    ],
    "liveSassCompile.settings.excludeList": [
       "**/node_modules/**",
       ".vscode/**"
    ],
    "liveSassCompile.settings.generateMap": true,
    "liveSassCompile.settings.autoprefix": [
        "defaults"
    ]
} 
```

Output:
```
Change detected - 2021-08-12, 12:47:00 p.m.
_header.scss
--------------------
Generated:
c:\repos\bootcamp-clone\src\scss\style.css.map
c:\repos\bootcamp-clone\src\scss\style.css
--------------------
```

I'm expecting it to save in `c:\repos\bootcamp-clone\src\css` and `c:\repos\bootcamp-clone\dist\css`

**Comment by glenn2223** [comment]
Hey @canuckkat. Sorry, but I can't replicate this issue.

---

Using the below settings...
```JS
{
    "liveSassCompile.settings.formats": [ // <-- The important setting
        {
            "extensionName": ".css",
            "format": "compressed"
        },
        {
            "savePath": "/wwwroot/dist/test",
            "extensionName": ".css",
            "format": "expanded"
        }
    ],
    // Below are others, for reference
    "liveSassCompile.settings.autoprefix": true,
    "liveSassCompile.settings.compileOnWatch": false,
    "liveSassCompile.settings.forceBaseDirectory": "/wwwroot",
    //"liveSassCompile.settings.generateMap": false, // <-- Removed for testing
    "liveSassCompile.settings.watchOnLaunch": true,
    "liveSassCompile.settings.showOutputWindowOn": "Information"
}
```

I get the following output:
```
--------------------
Watching...
--------------------
Change detected - 12/08/2021, 18:05:46
Essentials.scss
--------------------
Generated:
d:\Sites\Test Site\wwwroot\Assets\Style\Essentials.css.map
d:\Sites\Test Site\wwwroot\Assets\Style\Essentials.css
--------------------
Generated:
d:\Sites\Test Site\wwwroot\dist\test\Essentials.css.map
d:\Sites\Test Site\wwwroot\dist\test\Essentials.css
--------------------
Watching...
--------------------
```

---

Was there not anything else output as it should be followed by:

```
--------------------
Watching...
--------------------
```

Can you provide the file structure and an example file?

**Comment by canuckkat** [comment]
![image](https://user-images.githubusercontent.com/996527/129285877-4cc37a02-3235-406e-85b3-ed9ae9ee583d.png)

[_colours.scss.txt](https://github.com/glenn2223/vscode-live-sass-compiler/files/6979196/_colours.scss.txt)

**Comment by glenn2223** [comment]
Hey @canuckkat,

Sorry for the delay in getting back to you. I still can't replicate the issue.

I created a new folder and copied the folder structure to get your `/vscode/settings.json` file and the `\src\scss` and accompanying `/partials` subfolder - as per the screenshot below.

![File structure before first compilation](https://user-images.githubusercontent.com/33450392/129569514-aa78176f-b1d6-4e7a-b465-e74b9df58177.png)

I then adjusted the `styles` file so it output some compileable code. Then - upon save - it output the below:

![Output window showing the output of 2 CSS files and each accompanying map file](https://user-images.githubusercontent.com/33450392/129570516-f9fd6872-989e-422b-a381-4d7ea8267ddf.png)

and also changed the file structure to that shown below.

![File structure after compilation](https://user-images.githubusercontent.com/33450392/129569722-341c2045-6c1f-49a6-9164-ee6011f7819e.png)

As you can see the extension is working as expected on my machine with two different test folders.

----

Can you delete `/dist/css/styles.mini.css` and its' map file then compile again. All I can think is that the file has compiled to that location, it's just that you missed it in the ouput.

For reference you can download the exact folder I've been working on --> [Issue 114.zip](https://github.com/glenn2223/vscode-live-sass-compiler/files/6992662/Issue.114.zip).

Could you please confirm that it is working as expected? Thanks.

**Comment by canuckkat** [comment]
OHHH. I am dumb. I made a .vscode file instead of having a .vscode folder with a settings.json. Ugh.

Sorry for all the trouble!

**Comment by glenn2223** [comment]
> OHHH. I am dumb. I made a .vscode file instead of having a .vscode folder with a settings.json file. Ugh.

No worries. Can't believe I missed it from your screenshot 🤦‍♂️😂

>Sorry for all the trouble!
