### ISSUE TITLE
[Request] Publish extension on open-vsx.org

### ISSUE THREAD

**Issue by oxy** [glenn2223/vscode-live-sass-compiler#12]
Hi there!

I'm reaching out to you because we currently have the [upstream fork of this extension](https://github.com/ritwickdey/vscode-live-sass-compiler.git) manually added to our extension gallery at Coder for [code-server](https://github.com/cdr/code-server/), and we're currently working on a migration to open-vsx, which is also used by other community VSCode forks (including, but not limited to Arch Linux's Code-OSS builds and VSCodium).

We (and other open source VSCode forks) cannot use Microsoft's extension gallery, as MS' terms of service allows only the proprietary MS products to interact with the official gallery.

Since upstream is no longer active, We'd really appreciate it if you can add your extension to open-vsx! A simple guide on publishing extensions to Open-VSX is available [here](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions).

**Comment by glenn2223** [comment]
Hi @oxy,

I'm all about helping the open source community.

I'll take a look over the next few days.

Be seeing you soon on Open-VSX!!

**Comment by glenn2223** [comment]
We're live over on [open-vsx](https://open-vsx.org/extension/glenn2223/live-sass), just waiting on the claim to the namespace!
