### ISSUE TITLE
Plugin dont work on Linux

### ISSUE THREAD

**Issue by Mopsior** [glenn2223/vscode-live-sass-compiler#122]
Hey, I'm download plugin and i have this error `Live Sass Compiler: Unhandled error while compiling the active file. Error message: Cannot read property 'map' of undefined`. My system is ZorinOS 16 (based on ubuntu)

**Comment by glenn2223** [comment]
Hey @Mopsior ,

That doesn't sound like an issue with the extension but rather than with your SASS. Have you declared the variable `map` before you tried using it?

If you're using the newer `@use` instead of `@import` then you need to make sure you're including the namespace in any variable/function usage, or declaring the `@use` as global.

If this doesn't help/make sense, please can I see your code.

**Comment by glenn2223** [comment]
Sorry, there might be an underlying issue now I've just reread the message. Can I have a copy of your settings file please

**Comment by Mopsior** [comment]
I'm changed json to txt beacuse github requires that
[settings.txt](https://github.com/glenn2223/vscode-live-sass-compiler/files/7192347/settings.txt)

This is good file?

**Comment by Mopsior** [comment]
I don't change anything in plugin settings

**Comment by glenn2223** [comment]
Thanks for the file. Yeah, I can see you've not touched any settings.

Can you please follow the below steps:
1. Open/re-open the project
2. Save the file
2. Wait for the error message to come up
3. Press <kbd>F1</kbd> then enter `>Live Sass: Report an issue` (note the `>` may already be there) into the pop-up and press <kbd>Enter</kbd>
4. This will attempt to open your browser, allow it
5. When you're presented with the browser page, which is aimed at opening a new issue, ignore it and return to this issue
6. Add a comment here and paste the data that would have already been copied to your clipboard

Thanks again

**Comment by glenn2223** [comment]
Hey @Mopsior, any luck in getting me that data I requested?

**Comment by glenn2223** [comment]
Closing as more info required
