### ISSUE TITLE
Possible Issue with Include & Exclude Settings

### ISSUE THREAD

**Issue by glenn2223** [glenn2223/vscode-live-sass-compiler#123]
Hey Glenn,

First of all, thank you for the amazing work, I love the extension, it's just wonderful! 

I think I'm having a similar request as Pascal, although quite possibly different, but it seems to fall under the same area.

I can't pin point the exact time of when it changed behavior, but basically, it used to only compile my `main.scss` file which is under `/style/sass`, and therefore only create the first `/style/css` folder in my screenshot below, but now it also creates a `.css` file for every other `.scss` files it finds and so it ends up creating another `/css` folder in my `/style/sass` folder:
<img width="171" alt="GXmN2T8kJo" src="https://user-images.githubusercontent.com/49172724/134589957-75eb4f29-02bb-4bb2-9194-0aeae965ee0c.png">

I tried using `excludeList` and `includeItems` (separately) so it focuses only on my `main.scss` file, it does the desired effect of ignoring the files I don't want it to compile, however, it then only compiles when it detects a change to `main.scss`, which is barely edited compared to my other `.scss` files.

I think that ideally you'd want to have the option to select which file(s) are compiled with the use of `excludeList` and/or `includeItems`, while not ignoring the changes that are made to the other files, therefore compiling on saved changes in other files.

Right now, as I want my Sass to update after each change I made to a file is saved, I stopped using `excludeList` and `includeItems`, and I delete the extra folder it creates, but that's not very ideal.

Here are my current settings for the extension, as I figured it might be useful:

    "files.autoSave": "afterDelay",

    "liveSassCompile.settings.formats": [
        {
            "format": "expanded",
            "extensionName": ".css",
            "savePath": "~/../css"
        },
        {
            "format": "compressed",
            "extensionName": ".min.css",
            "savePath": "~/../css/dist"
        }
    ],
    "liveSassCompile.settings.generateMap": false,
    "liveSassCompile.settings.autoprefix": [
        "defaults"
    ],
    "liveSassCompile.settings.showOutputWindowOn": "Warning",

I hope my explanation was clear enough, I'll be glad to answer questions if needed.

_Originally posted by @EmbitiousDev in https://github.com/glenn2223/vscode-live-sass-compiler/issues/118#issuecomment-926200234_

**Comment by glenn2223** [comment]
Hey @EmbitiousDev,

So the exclude setting will ignore every file within it, this includes any partials - so I don't think this is what you're after. Though including just that file should be giving you the desired effect - which is possible, just by placing the file in the glob pattern instead of a folder/`*.sass` setting.

Can I have a copy of the settings you have tried so far? Can I also have the location of the partial SASS files as well as another SASS file that you don't want to be compiled?

**Comment by glenn2223** [comment]
Closing as more info required

**Comment by EmbitiousDev** [comment]
Hey Glenn, 

Sorry for the delay, I got busy, and didn't have much time to test and gather more information.
But when trying to reproduce it again, I found that the issue solved itself, I'm not sure what was the cause of it, it really is a mystery.
Really sorry for the waste of time.

**Comment by glenn2223** [comment]
No worries, just glad it's working 

Have a good weekend 👍
