### ISSUE TITLE
Installing Live Sass Compiler

### ISSUE THREAD

**Issue by dp-designpilot** [glenn2223/vscode-live-sass-compiler#124]
Hi Glenn

I have a MacBook Air and have a local development environment with Homebrew, Apache, MariaDB, PHP7.4 and PHP8.0, it works perfectly. Do I now have to install **brew install sass/sass/sass** so that I can use the Live Sass compiler.

**Comment by glenn2223** [comment]
Hey @dp-designpilot,

The extension actually comes packaged with the sass/sass JavaScript API (npm package), this means that nothing extra should need to be installed Why do you ask, are you having issues?

**Comment by dp-designpilot** [comment]
No, I have no problems (it's only because 1.42.1 is stated as the most recent on the https://sass-lang.com/install page).  And I've set up a development environment with homebrew

**Comment by glenn2223** [comment]
Sorry for the delay, been a crazy few days (started my next uni module).

I would suggest that you add the JSON file in [this zip](https://github.com/glenn2223/vscode-live-sass-compiler/files/7253060/settings.zip) to your `.vscode` folder. The contents of this file are: (for reference)

```JSON
{
    "liveSassCompile.settings.formats":[
       {
           "extensionName": ".css",
           "format": "compressed",
           "savePath": "~/../css"
       }
   ]
}
```
 
This tells the compiler to save the file up one directory and then in the CSS folder. Alternatively, you can use `/[SCSS-CSS]/css` as your `savePath` setting if the `[SCSS-CSS]` folder is at the first level in your project.

I have the below example you can refer to as well.

[Issue 124.zip](https://github.com/glenn2223/vscode-live-sass-compiler/files/7253199/Issue.124.zip)

---

I will close this issue now but please feel free to continue to ask any questions
