### ISSUE TITLE
Using sass:math built in module generates wrong css 

### ISSUE THREAD

**Issue by murugappanrm** [glenn2223/vscode-live-sass-compiler#125]
Hi,

When i used the sass:math module, and used one of the math.div function, compiler does not generate the css for the property and also generates an error css file. 

File containing the built in
![file with Builtin](https://user-images.githubusercontent.com/63133893/135254881-e600e536-e6cc-4ea1-8f7b-58e0c1029026.png)

generated CSS:
![generated css file](https://user-images.githubusercontent.com/63133893/135254946-b89a29d0-269d-4e34-872f-74f6bac12d36.png)

Please use the scss files in the attached zip file.
[shinobi.zip](https://github.com/glenn2223/vscode-live-sass-compiler/files/7251234/shinobi.zip)

**Comment by glenn2223** [comment]
Hi @murugappanrm,

Sorry to see you're having an issue. I'm afraid that I can not replicate this. 

Below is my example project, can you check the output of both files, compared to your own?

[Issue 125.zip](https://github.com/glenn2223/vscode-live-sass-compiler/files/7253449/Issue.125.zip)

You don't have that comment anywhere in any of your files?

What OS do you have?

**Comment by murugappanrm** [comment]
Hi @glenn2223 

I am truly sorry about this. When i re-did all the sheets and tried again, the whole thing worked as is. I am flabbergasted. It must be due to my uninstalling old Rick's version and installing your extension a few times. Probably, everything cleared after a hard reboot.

One thing still remain unanswered. Hope you could help. This is regarding the debug. It does not seem to generate any output in the VSCode debug console. I did set the debug in the setting for Live Sass Compiler.  This is the code for _card.scss

@use 'sass:math';

.card {
  display: block;
  padding: $base-padding;
  border: $base-border-thickness solid #ddd;
  box-shadow: $base-box-shadow;
  border-radius: math.div($base-border-radius, 4);

  .card-title {
    font-size: $base-font-size;
    padding-bottom: $base-padding;
    font-weight: bold;
  }
  .card-body {
    font-size: $base-font-size;

    a {
      text-decoration: underline;
    }
  }
}

@debug math.div(10, 3);
@debug math.$pi;
@debug math.floor(2.6);
@debug math.max(1px, 20px, 15px, 12px);

**Comment by glenn2223** [comment]
Please refer to #89 - I'm currently waiting on sass to allow the JS API to output this type of information. Sorry.
