### ISSUE TITLE
Merge in one file the output

### ISSUE THREAD

**Issue by vincenzo-antolini-os** [glenn2223/vscode-live-sass-compiler#127]
I have a bunch of files. Is there a way to merge them?
Thanks in advance

**Comment by glenn2223** [comment]
Sure, you can import them into a "main" file using `@use`. I'd suggest you start [here](https://sass-lang.com/documentation/at-rules/use).

If you're not using the typical naming of partial files (leading with an underscore - `_`) then you'd need to look at [`excludeList`](https://github.com/glenn2223/vscode-live-sass-compiler/blob/master/docs/settings.md#livesasscompilesettingsexcludelist) and [`includeItems`](https://github.com/glenn2223/vscode-live-sass-compiler/blob/master/docs/settings.md#livesasscompilesettingsincludeitems), using one of these should help in compiling only the files you care about.

---

**Sidebar:** another thing to consider is actually having them as individual files included on the page. HTTP2 has greatly improved the handling of multiple requests ([subjected proof](https://imagekit.io/demo/http2-vs-http1)) - especially in HTTPS - so adding multiple small files may benefit you more than one big file - in terms of load time.
Plus by only loading the files you care about you can reduce unnecessary CSS bloat and again reduce load times.
