### ISSUE TITLE
liveSassCompile.command.debugFileList not found

### ISSUE THREAD

**Issue by robotikz** [glenn2223/vscode-live-sass-compiler#133]
![image](https://user-images.githubusercontent.com/10348033/140742348-c230bfde-c2aa-448b-aa23-5b43b6149608.png)

**Comment by glenn2223** [comment]
Sorry for the delay in getting back, I've not been very well.

It seems like you don't have a SASS/SCSS file in your workspace. When, and only when, you have a file with one of these two extensions, VSCode will load the extension and thus the commands.

Please confirm that this fixes your issue, thanks.

**Comment by robotikz** [comment]
Windows 11
It works well, if I start my VSCode for the first time and do not switch/open to another workspace. 
If I open another workspace, then it does not work, I need to restart my machine :(

**Comment by glenn2223** [comment]
I'll have to do some testing and get back to you

**Comment by glenn2223** [comment]
I have tested it on my version of Windows 11 and wasn't able to reproduce. As long as the project you're opening contains a `.scss` or `.sass` file then it should activate the extension and all of it's commands. If the extension doesn't contain either of these files then VS Code won't bother activating it.

Can you provide copies of the two projects your switching between?

**Comment by glenn2223** [comment]
Closing as info required
