### ISSUE TITLE
Compiling on launch, but not updating css when scss is modified

### ISSUE THREAD

**Issue by geoffroy-serre** [glenn2223/vscode-live-sass-compiler#137]
### Original post

Hi,

When i click on watch sass, the scss file is properly compiled and style.css created. But when i modify my scss, nothing is live compiled.
Vs code and extension is up to date, no error message just showing Watching in console .
Same happens if i use ctrl shift P to launch the live compiler.

I tried to specify the output in settings.json as I saw on stack, but it didnt solve the issue, the scss is only compiled on launch and watching have no effect, no update.
Launching vsCode in admin change nothing either.

Thanks for the help and your work ^^

Windows 11
VS code 1.62.3
Live Saas Compiler by Glenn 5.1.1

---

### Tasks for 5.2 release

- [x] Find cause
- [x] Apply fix

**Comment by glenn2223** [comment]
It sounds like the file might be excluded. Is it all files that don't trigger compilation or just a set few?

When you have a file that isn't triggering compilation, with that file open, try running the `liveSass.command.debugInclusion` command. That might help.

If it doesn't, I'm going to need a few bits:
- your settings
- set the `liveSassCompile.settings.showOutputWindowOn` to trace, save the problem file and include the output
- after clearing that output, run the `liveSass.command.debugFileList` and include that too, please

**Comment by geoffroy-serre** [comment]
With the command debugInclusion, i saw that it watched the file.Scss,  even if on launch it compiled successfully the renamed file (file.scss) .
Just renaming the project folder, and re open it with vscode solve the issue. It seems doing thaht it "reset" the file being watched.

**Comment by glenn2223** [comment]
I can see the problem, will fix soon

**Comment by glenn2223** [comment]
So v5.2.0-alpha.1 is available for testing. Download it below or from the `ahead`  branch

[live-sass-5.2.0-alpha.1.zip](https://github.com/glenn2223/vscode-live-sass-compiler/files/7800163/live-sass-5.2.0-alpha.1.zip)
