### ISSUE TITLE
Live Sass Compiler: Unhandled error while compiling all files. Error message: Cannot read property 'substr' of null

### ISSUE THREAD

**Issue by VincentHogendoorn** [glenn2223/vscode-live-sass-compiler#138]
I keep getting this error and I can't find what it is...

My structure looks like this: 
![Schermafbeelding 2021-11-23 om 14 32 08](https://user-images.githubusercontent.com/36482530/143033223-ff367ae5-4986-4209-8e27-c6419ddc99bb.png)

And my settings.json looks like this:
`{
    "liveSassCompile.settings.formats": [
        {
            "format" : "compressed",
            "extensionName" : ".css",
            "savePath": "/themes/baseplatev2/css/"
        }
    ],
    "liveSassCompile.settings.autoprefix": [
        "> 1%",
        "last 2 versions"
    ],
    "liveSassCompile.settings.forceBaseDirectory": "/themes/baseplatev2/sass/",
}`

Does anyone have a clue?

**Comment by glenn2223** [comment]
Can you get the error message to pop up again and then run the command `Live Sass: Report an issue`, I just need the text it's copied into your clipboard so you don't need to open a new issue

**Comment by glenn2223** [comment]
Any luck getting the error information I requested?

I tried to see if it was your settings that caused the issue but I wasn't able to reproduce it.

**Comment by VincentHogendoorn** [comment]
Hi there,

Sorry for the late reply, appreciate the quick response.
Thing is the issue stopped occurring and I got the compiler to work. again. I don't really know what went wrong.

**Comment by glenn2223** [comment]
Fair enough, glad it's working. If you face it again then please comment again
