### ISSUE TITLE
"liveSassCompile.settings.formats" showing warning for "savePath"

### ISSUE THREAD

**Issue by dibakash** [glenn2223/vscode-live-sass-compiler#139]
### Original post 

"liveSassCompile.settings.formats" shows a warning for "savePath" if the value of "savePath" is set to anything other than null. Showing same warning for "liveSassCompile.settings.excludeList" array values as well.

Shows the following warning in VS CODE warnings:
```
Must start with any of:
`/` or `\` (for workspace root)
`~/` or `~\` for relative to the file being processed. Must not end with a path separator (`/` or `\`)
Set the save location of exported CSS.

Set the relative path from Workspace Root.

'/' stands for your workspace root.

Example: /subfolder1/subfolder2. (NOTE: if folder does not exist, folder will be created as well)."
```
![Screenshot (41)](https://user-images.githubusercontent.com/44256849/143426870-cae91f6a-27a4-4c15-a941-7753d88b8af2.png)

Here are my json settings:
------
```
"liveSassCompile.settings.formats": [
		{
			"format": "expanded",
			"extensionName": ".css",
			"savePath": "~/../css"
		}
	],
	"liveSassCompile.settings.excludeList": [
		"**/node_modules/**",
		".vscode/**"
	],
```

While the
 Sass still compiles to CSS with the above settings Vscode still shows a warning in "savePath" as well as "liveSassCompile.settings.excludeList" array values.

---

### Tasks for 5.2 release

- [x] Find cause
- [x] Apply fix

**Comment by glenn2223** [comment]
The pattern for your exclude list should look like this:
````JS
"liveSassCompile.settings.excludeList": [
  "/**/node_modules/**",
  "/.vscode/**"
]
```

However, if that's all you've got then you can just remove it as that's the default.

I'm not sure why `savePath` has started to throw a warning, the regex is valid - I'll do some reading/checking.

**Comment by dibakash** [comment]
Yes. you are right about the exclude list pattern. 

The `savePath` has started to throw a warning from the last VsCode update I guess (not sure exactly from when. Just encountered it today). Will wait for your update.

**Comment by glenn2223** [comment]
So the issue was two-fold, Microsoft released an update that stopped trying to use incorrect regex - [reference](https://github.com/microsoft/vscode-json-languageservice/commit/de73b8b67e3c125b3d249ae53ff046b8411c0d2d#diff-446907be7bbde664b082d8429d463a53099555b54e5d379edaee6220a7d42a52)

I checked my regex and, apparently, it's invalid somehow - even though it is valid in regex101. I needed to double double escape all of my `\` characters to `\\\\` instead of just `\\`

I will apply a fix and publish an update soon

**Comment by dibakash** [comment]
Great. Checked the package.json of your extension and updated line 150 of the JSON with your Fix [#139](https://github.com/glenn2223/vscode-live-sass-compiler/issues/139) (sorry for not waiting for the update ). No longer throws a warning.

**Comment by glenn2223** [comment]
>No longer throws a warning.

Great! I'm glad to hear you had the same result as I did.

>sorry for not waiting for the update

Not a problem, can't blame you! Any warnings really annoy me

**Comment by michael-strother-wth** [comment]
I've also noticed this issue but on my system, neither escaping nor double-escaping remedies the warning message.
Oddly enough it *does* save to the designated directory as I originally configured it (despite the warning).

**Comment by glenn2223** [comment]
Hmmm, strange. What OS do you have? Mine is Windows

**Comment by michael-strother-wth** [comment]
> Hmmm, strange. What OS do you have? Mine is Windows

Windows 10.

**Comment by glenn2223** [comment]
> > Hmmm, strange. What OS do you have? Mine is Windows
> 
> Windows 10.

Very strange

Are you updating your `package.json` as dibakash did? Or just your `settings.json` file?

If it's the latter then please revert your setting and use the version that I have zipped below

[live-sass-5.1.2-alpha.1.zip](https://github.com/glenn2223/vscode-live-sass-compiler/files/7738500/live-sass-5.1.2-alpha.1.zip)

**Comment by dibakash** [comment]
Although the issue was solved for windows 10, after I changed the package.json with the fix you mentioned [above](https://github.com/glenn2223/vscode-live-sass-compiler/issues/139#issuecomment-979828994), while I was working in WSL(windows subsystem for linux, ubuntu 20.04) the same issue showed up. However, after I tried installing your latest updated version [live-sass-5.1.2-alpha.1.zip](https://github.com/glenn2223/vscode-live-sass-compiler/files/7738500/live-sass-5.1.2-alpha.1.zip) and the issue is fixed.

**Comment by glenn2223** [comment]
> Although the issue was solved for windows 10, after I changed the package.json with the fix you mentioned [above](https://github.com/glenn2223/vscode-live-sass-compiler/issues/139#issuecomment-979828994), while I was working in WSL(windows subsystem for linux, ubuntu 20.04) the same issue showed up. However, after I tried installing your latest updated version [live-sass-5.1.2-alpha.1.zip](https://github.com/glenn2223/vscode-live-sass-compiler/files/7738500/live-sass-5.1.2-alpha.1.zip) the issue is now fixed.

Sorry for the delay

Maybe the Linux version hasn't used your updated JSON data or had some kind of caching issue. As long as the new version didn't have the issue, I have no concerns. Thanks for checking and commenting though - never want to push a broken "fix" 😂
