### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by YannickLarher** [glenn2223/vscode-live-sass-compiler#140]
### Original post

Hello, 
I have a problem, probably a beginner's problem...
If I create a folder, I create in it 1 scss file, I have an error : 
Compilation Error
There was no CSS output from sass/sass
If I take a folder where there are already scss files created before, it works and I can add new ones...
Can you help me to solve this little problem? Thank you!

---

### Tasks for 5.2 release

- [x] Find cause
- [x] Apply fix

**Comment by glenn2223** [comment]
I'll do a bit of investigating. Is there any text in the scss file you created?

**Comment by YannickLarher** [comment]
Hello,yes, there are a few lines of code. 
In fact I had the old version (from the old developer) of Live sass compiler. And I encounter this problem since the update to your version. Is it possible that some files have remained and cause a conflict? If I reinstall the old version, it works again, I don't have the errors anymore...
I restarted VSC between the two versions. I emptied the caches in appdata\roaming...

**Comment by glenn2223** [comment]
So it's an error thrown by my own code, which has done a check on the CSS output from dart-sass.

I have adjusted the code to output an error message that may have been thrown by dart-sass. Can you install the below alpha and try again? Hopefully, there will be extra error information to highlight any human/coding errors.

[live-sass-5.1.2-alpha.1.zip](https://github.com/glenn2223/vscode-live-sass-compiler/files/7632919/live-sass-5.1.2-alpha.1.zip)

Thanks in advance

**Comment by YannickLarher** [comment]
Thanks a lot! I try this version and this is the errors : 
Compilation Error
There was no CSS output from sass/sass
Sass error: NONE
--------------------
Watching...
--------------------
Change detected - 01/12/2021, 11:16:18
Untitled-1.scss
--------------------
Compilation Error
There was no CSS output from sass/sass
Sass error: NONE
--------------------
Watching...

**Comment by glenn2223** [comment]
So it's not an error thrown by dart-sass or a code level error I can identify at the minute.

Can you provide me with the file you're trying to compile.

**Comment by YannickLarher** [comment]
[Untitled-1.zip](https://github.com/glenn2223/vscode-live-sass-compiler/files/7633123/Untitled-1.zip)

**Comment by glenn2223** [comment]
So there is actually no CSS output from the file you provided, as it's just variables. I have applied a fix, can you confirm that it's fixed in the below version

[live-sass-5.1.2-alpha.2.zip](https://github.com/glenn2223/vscode-live-sass-compiler/files/7633203/live-sass-5.1.2-alpha.2.zip)

**Comment by YannickLarher** [comment]
everything works as it should! Thanks a lot! I wish you a nice day
