### ISSUE TITLE
Custom formating

### ISSUE THREAD

**Issue by deweblooper** [glenn2223/vscode-live-sass-compiler#141]
Hi Glenn is it possible to customize settings or somehow make output CSS slightly customized?
Like commented map row move to new extra row plus one more empty row, 
or not change some data like
_content: "\f291"_  leave as is and not convert to   _content: ""_
I´ve found way with hard modifying \out\extension.js
but I thinkg it´s too rough if there exist some more elegant ways.
thank you

**Comment by glenn2223** [comment]
> Like commented map row move to new extra row plus one more empty row,

Unfortunately, this isn't possible. 

> _content: "\f291"_ leave as is and not convert to _content: ""_

This is a duplicate - please see [this comment](https://github.com/glenn2223/vscode-live-sass-compiler/issues/39#issuecomment-791479152)

----

I'll close but please continue to comment if you have more questions

**Comment by deweblooper** [comment]
OK, thank you, it´s fine. Maybe once you´ll find a way to implement something for overriding original "\out\extension.js" file to save changes without replacing after plugin update.
But anyway, I am very happy with your plugin

**Comment by glenn2223** [comment]
> OK, thank you, it´s fine. Maybe once you´ll find a way to implement something

If it's something that's highly requested then sure I could look at adding some customisation to the source map output. Not sure exactly how at the minute though.

> But anyway, I am very happy with your plugin. I hope I´ve made right donation to this project using "Sponsor this project @TopMarksDevelopment" in your right column :)

I'm happy you like the extension. And I'm also ecstatic that you've donated, THANK YOU!! 😍 (And yes, that's the right place 😁)

**Comment by Brockenstein** [comment]
Two years later and I would say the fact that someone every year comes into issues either looking for or posting this as an issue means it is something highly requested.
