### ISSUE TITLE
ASP.NET MVC layout templates are being treated as "partial files"

### ISSUE THREAD

**Issue by luanmm** [glenn2223/vscode-live-sass-compiler#143]
## Original message

In a project that uses layouts in ASP.NET MVC, these files are partial for the framework, but are "normal" CSS files and, to use SASS in these scenario, it should be treated as a normal SCSS file.

Structure:

- Views
  - Shared
    - _Layout.cshtml
    - _Layout.cshtml.css (to generate this file, the ideal scenario is that a file named _Layout.cshtml.scss could be generated in Live Sass extension)

The reason for this to not work is because files starting with "_" are always treated as partial SCSS files.

There is a chance that if a file is in the pattern of "liveSassCompile.settings.includeItems" it could be processed even if the name starts with "_"? So I could explicit add a pattern (like `/**/Views/**/_*.cshtml.scss`) to make this work. Or the default "liveSassCompile.settings.excludeList" could contain the pattern `/**/_*.*`, so this behavior could be configured by the user "out-of-the-box" instead of being hardcoded.

Thanks in advance and congratulations for the great work!

----

## Tasks

- [x] Apply code changes
- [x] Update documentation

**Comment by glenn2223** [comment]
**Definitely open for comments/thoughts**

---

Thanks for making the suggestion, a great idea! However, I think it would have to be its own setting.

> There is a chance that if a file is in the pattern of "liveSassCompile.settings.includeItems" it could be processed even if the name starts with "_"? So I could explicit add a pattern (like `/**/Views/**/_*.cshtml.scss`) to make this work.

Good idea but we would need to check for an include file containing some kind of `/_*.*` to stop the exclusion of partials that start with a `_`. Quite a heavy (and possibly buggy) way to resolve this.

> Or the default "liveSassCompile.settings.excludeList" could contain the pattern `/**/_*.*`,...

As I'm sure you know, the way the extension is currently set up allows a saved partial to compile all "full" files. So, by adding this default exclude and without a separate setting, we wouldn't know when an individual's "actual" partial files are saved to trigger the compilation of all files.

---

### Idea
So, I think a separate setting should be introduced. Possibly called (to keep with the naming convention) `partialsList`. This would then default to `/**/_*.s[ac]ss` to keep with the current implementation.

### Usage/Implementation
By adding glob patterns to `partialList` you can define one (or many) files/directories to treat as partials. So, when a file is saved that matches one of these patterns is saved, it will compile everything. When it doesn't match one of these patterns it compiles just that one file.

### Advantages
- Setting could be customised at each workspace level
- Fully customisable partial locations
- This also means one less breaking change for current users. And one less for those migrating from the original extension.

### Disadvantages
- None that I can think of

**Comment by luanmm** [comment]
Thanks for your reply, @glenn2223!

I wasn't aware of all the behaviors, thanks for sharing your thoughts and expertise. I'm not an expert, so I can't think of any aspects that I could add/contribute to your suggested design for now.

If somebody could share another point of view, it would be nice to have new contributions and ideas. Otherwise, I could try to follow your guidance and open a PR, if you think that would be helpful (just not sure if I will have time to do it in the next couple weeks).

Best regards!

**Comment by glenn2223** [comment]
> I wasn't aware of all the behaviors, thanks for sharing your thoughts and expertise. I'm not an expert, so I can't think of any aspects that I could add/contribute to your suggested design for now.

No problem. It's also fine if you don't feel you can contribute to the point. Do you feel this _possible_ solution would work for you?

> If somebody could share another point of view, it would be nice to have new contributions and ideas

It's not happened so far, but here's hoping for change with some more ideas 🤞. Come on community, weigh in 😂

> Otherwise, I could try to follow your guidance and open a PR, if you think that would be helpful

No need for a PR. I just like to share my thoughts and have the chance for feedback, rather than just implementing something that "should do the job". If I don't get any further feedback after a few days then I will implement the change myself.

I'm about to have a 2-week break from my uni studies, and a week off from work, so I should have the spare time to pop this in and push an alpha for you/people to try come the new year

**Comment by luanmm** [comment]
I think that, for my use case, it should work, indeed.

For now, I just need to build some "partial" files (in this specific case, unfortunately, is not the reality, because this is more a conflict in conventions between SASS and ASP.NET that anything else :smile:). So, with this new options, it should do the trick.

I think I will help testing it, then, when the new version comes out. :mx_claus: 

Thanks for the help, @glenn2223. And congratz for the effort to maintain this project!

**Comment by glenn2223** [comment]
So v5.2.0-alpha.1 is available for testing. Download it below or from the `ahead`  branch

[live-sass-5.2.0-alpha.1.zip](https://github.com/glenn2223/vscode-live-sass-compiler/files/7800163/live-sass-5.2.0-alpha.1.zip)

**Comment by luanmm** [comment]
This alpha version works in my ASP.NET MVC project, after configured as below:

```json
    "liveSassCompile.settings.excludeList": [
        "/.vscode/**",
        "/**/node_modules/**",
        "/**/wwwroot/lib/**"
    ],
    "liveSassCompile.settings.includeItems": [
        "/**/wwwroot/**/*.scss",
        "/**/Views/**/*.cshtml.scss"
    ],
    "liveSassCompile.settings.partialsList": [
        "/**/_*[^.cshtml].s[ac]ss"
    ]
```

Thank you for the effort, @glenn2223!

**Comment by glenn2223** [comment]
Glad to hear it, one thing though - you actually need the glob pattern `/**/_!(*.cshtml).s[ac]ss`.

Your glob pattern will incorrectly match any file that ends in **any** of those characters, rather than the whole term (e.g. `_c.sass` or `_h.sass` or `_l.sass`)

**Comment by luanmm** [comment]
I confess that I'm not so used to work with glob patterns and thought that something could be wrong there :smile: 

Thanks for the guidance, @glenn2223!

**Comment by glenn2223** [comment]
Glad to help 😁
