### ISSUE TITLE
Live Sass Compiler not finding .scss file

### ISSUE THREAD

**Issue by brohon** [glenn2223/vscode-live-sass-compiler#145]
### Original post

These are my workspace settings: 
```
{
    "liveSassCompile.settings.formats": [
        {
         "format": "expanded",
         "extensionName": ".css",
         "savePath": "~/"
        }
       ],
    "liveSassCompile.settings.includeItems": [
        "/src/styles/main.scss",
    ],
    "git.ignoreLimitWarning": true
}
```

But when I run Get All Included Files The main.scss is not found. Compiling once by hand works fine. 

I'm on a windows 10 machine SSHd into a linux machine. I have installed 5.1.2-alpha

---

### Steps to fix for 5.2 release

- [ ] Find cause
- [ ] Fix it

**Comment by glenn2223** [comment]
Sorry to hear your having an issue.

With the main file open, what's the result of running the `liveSass.command.debugInclusion`command?

Then can you please clear the output window and include the output provided by the `liveSass.command.debugFileList` command.

**Comment by brohon** [comment]
When I run `liveSass.command.debugInclusion`

```
Checking current file
/home/dave/MagentoAPI/dev/src/styles/main.scss
--------------------
File excluded
The file is excluded based on your settings, please check your configuration
```
When I run `liveSass.command.debugFileList`

```
Extension Info
--------------------
Current File
--------------------
/home/dave/MagentoAPI/dev/src/styles/main.scss
--------------------
Workspace Folders
--------------------
[0] dev
/home/dave/MagentoAPI/dev
--------------------
Checking workspace folder 0 of 1
Path: /home/dave/MagentoAPI/dev
--------------------
--------------------
Current Include/Exclude Settings
--------------------
Include: [ /src/styles/main.scss ]
Exclude: [ /**/node_modules/**, /.vscode/** ]
--------------------
Included SASS Files
--------------------
--------------------
Included Partial SASS Files
--------------------
--------------------
Excluded SASS Files
--------------------
--------------------
```

Thanks for your help with this!

**Comment by glenn2223** [comment]
Very strange. I've quickly expanded the `liveSass.command.debugFileList` command in the below revision - just added a search for any/all SASS files in the project. Hopefully, it will help me identify the issue, ready for a proper testing build.

Can you run the command and include the extra output. Thanks

[live-sass-5.2.0-nightly.2.zip](https://github.com/glenn2223/vscode-live-sass-compiler/files/7811134/live-sass-5.2.0-nightly.2.zip)

**Comment by brohon** [comment]
Here's the output:
`Extension Info
--------------------
Current File
--------------------
/home/dave/MagentoAPI/dev/src/styles/main.scss
--------------------
Workspace Folders
--------------------
[0] mc_test
/home/dave/mc_test
[1] mc_dev
/home/dave/mc_dev
[2] mailchimp_integration
/home/dave/mailchimp_integration
[3] MagentoAPI
/home/dave/MagentoAPI
--------------------
Checking workspace folder 1 of 4
Path: /home/dave/mc_dev
--------------------
--------------------
Current Include/Exclude Settings
--------------------
Include: [ NULL ]
Exclude: [ /**/node_modules/**, /.vscode/** ]
--------------------
Included SASS Files
--------------------
/home/dave/MagentoAPI/dev/src/styles/main.scss
--------------------
Included Partial SASS Files
--------------------
--------------------
Excluded SASS Files
--------------------
--------------------
All SASS Files
--------------------
/home/dave/MagentoAPI/dev/src/styles/main.scss
--------------------
Checking workspace folder 2 of 4
Path: /home/dave/mailchimp_integration
--------------------
--------------------
Current Include/Exclude Settings
--------------------
Include: [ NULL ]
Exclude: [ /**/node_modules/**, /.vscode/** ]
--------------------
Included SASS Files
--------------------
/home/dave/MagentoAPI/dev/src/styles/main.scss
--------------------
Included Partial SASS Files
--------------------
--------------------
Excluded SASS Files
--------------------
--------------------
All SASS Files
--------------------
/home/dave/MagentoAPI/dev/src/styles/main.scss
--------------------
Checking workspace folder 3 of 4
Path: /home/dave/MagentoAPI
--------------------
--------------------
Current Include/Exclude Settings
--------------------
Include: [ NULL ]
Exclude: [ /**/node_modules/**, /.vscode/** ]
--------------------
Included SASS Files
--------------------
/home/dave/MagentoAPI/dev/src/styles/main.scss
--------------------
Included Partial SASS Files
--------------------
--------------------
Excluded SASS Files
--------------------
--------------------
All SASS Files
--------------------
/home/dave/MagentoAPI/dev/src/styles/main.scss
--------------------
Checking workspace folder 0 of 4
Path: /home/dave/mc_test
--------------------
--------------------
Current Include/Exclude Settings
--------------------
Include: [ NULL ]
Exclude: [ /**/node_modules/**, /.vscode/** ]
--------------------
Included SASS Files
--------------------
/home/dave/MagentoAPI/dev/src/styles/main.scss
--------------------
Included Partial SASS Files
--------------------
--------------------
Excluded SASS Files
--------------------
--------------------
All SASS Files
--------------------
/home/dave/MagentoAPI/dev/src/styles/main.scss`

But it's still not compiling after save when it's watching.

**Comment by glenn2223** [comment]
That's very strange the files are now being detected in your new workspace structure. Stranger still that it's still not compiling.

Can you set your `showOutputOn` to `Trace` save the file and then paste the output here? Thanks

**Comment by brohon** [comment]
`Command called: "liveSass.command.watchMySass"
--------------------
Starting to compile all files
--------------------
Changing status bar to: "Working on it..."
--------------------
Getting SASS files
Query pattern: undefined
Can be overwritten: true
--------------------
Checking folder 1 of 1
Folder: dev
--------------------
Query pattern overwritten
New pattern(s): "/src/styles/main.scss"
--------------------
No base folder override found. Keeping workspace folder
--------------------
Found 0 SASS files
--------------------
Compiling Sass/Scss Files: 
--------------------
Switching UI state
--------------------
Changing status bar to: Watching
--------------------
Watching...
--------------------
VS Code event: "onDidSaveTextDocument"
--------------------
Found the workspace folder
Workspace Name: dev
--------------------
SASS file saved
A SASS file has been saved, starting checks
--------------------
Checking SASS path isn't excluded
Path: /home/dave/MagentoAPI/dev/src/styles/main.scss
--------------------
No base folder override found. Keeping workspace folder
--------------------
Searching folder
File not found, must be excluded
--------------------
File excluded
The file has not been compiled as it's excluded by user settings
Path: /home/dave/MagentoAPI/dev/src/styles/main.scss
--------------------`

I've checked the user settings.json and `liveSassCompile` settings are listed in that file, only the workspace file.

**Comment by glenn2223** [comment]
I have a theory as to why it might not be working.

I have expanded on some trace logs and applied a fix (if this is the cause). Please install the revision below, keep your `showOutputWindowOn` as `Trace`, test and then post the output back here.

[live-sass-5.2.0-nightly.2.1.zip](https://github.com/glenn2223/vscode-live-sass-compiler/files/7825326/live-sass-5.2.0-nightly.2.1.zip)

Thanks

**Comment by brohon** [comment]
```
"live-sass-compiler" is now activate
--------------------
Constructing app model
--------------------
Constructing error logger
--------------------
Clearing any old log data
--------------------
Error logs cleared
--------------------
Changing status bar to: "Starting..."
--------------------
App model constructed
--------------------
Checking for an unread announcement
--------------------
Live SASS commands ready
Commands have been saved and are ready to be used
--------------------
Announcement has already been shown
--------------------
Changing status bar to: Not watching (or Watch SASS)
--------------------
Command called: "liveSass.command.watchMySass"
--------------------
Starting to compile all files
--------------------
Changing status bar to: "Working on it..."
--------------------
Getting SASS files
Query pattern: undefined
Can be overwritten: true
--------------------
Checking folder 1 of 1
Folder: dev
--------------------
Query pattern overwritten
New pattern(s): "/src/styles/main.scss"
--------------------
No base folder override found. Keeping workspace folder
--------------------
Found 0 SASS files
--------------------
Compiling Sass/Scss Files: 
--------------------
Switching UI state
--------------------
Changing status bar to: Watching
--------------------
Watching...
--------------------
VS Code event: "onDidSaveTextDocument"
--------------------
Found the workspace folder
Workspace Name: dev
--------------------
SASS file saved
A SASS file has been saved, starting checks
--------------------
Checking SASS path isn't excluded
Path: /home/dave/MagentoAPI/dev/src/styles/main.scss
--------------------
No base folder override found. Keeping workspace folder
--------------------
Searching folder
Search results
--------------------
File not found, must be excluded
--------------------
File excluded
The file has not been compiled as it's excluded by user settings
Path: /home/dave/MagentoAPI/dev/src/styles/main.scss
--------------------
```

Still no dice. Hope this helps.

**Comment by brohon** [comment]
Hey Glenn

I had to remove this from my settings file to get it to work. I tried this previously. 

```
    "liveSassCompile.settings.includeItems": [
        "/src/styles/main.scss",
```

Didn't know that including a path excluded others. Also, that's the relative path to my workspace so I think it should have worked. Nonetheless, it's working now without specifying the path.

**Comment by brohon** [comment]
Follow-up, I only got it to work once. Still have the path remove and it's not compiling.

**Comment by glenn2223** [comment]
Sorry for the delay, racking my brain.

---

> Didn't know that including a path excluded others. Also, that's the relative path to my workspace so I think it should have worked....

Yeah, the `includeItems` is the perfect setting when you only have a few files you want to compile. However, saving a specified file - or any other partial files - should still compile any necessary files.

>... Nonetheless, it's working now without specifying the path.   ....    Follow-up, I only got it to work once

Strange that it compiled one time.

----

So I think it may be some kind of compatibility issue when fdir is searching using a SSH connection. Maybe username and password info needs to be passed through so fdir can correctly crawl it 🤷 

To test this could you please do a couple of things for me? Firstly, can you use the below nightly build so I can see the output from a specific fdir command?

[live-sass-5.2.0-nightly.2.2.zip](https://github.com/glenn2223/vscode-live-sass-compiler/files/7842517/live-sass-5.2.0-nightly.2.2.zip)

After that, could you copy the files locally and test the extension then?

If the issue does lie somewhere in/with fdir then I can reach out to them to see if there's anything that can be done to resolve the matter

**Comment by brohon** [comment]
Here's the output:

```
Watching...
--------------------
VS Code event: "onDidSaveTextDocument"
--------------------
Found the workspace folder
Workspace Name: MagentoAPI
--------------------
SASS file saved
A SASS file has been saved, starting checks
--------------------
Checking SASS path isn't excluded
Path: /home/dave/MagentoAPI/dev/src/styles/main.scss
--------------------
No base folder override found. Keeping workspace folder
--------------------
Searching folder
FDIR OUTPUT
[{"dir":"/home/dave/MagentoAPI","files":[]},{"dir":"/home/dave/MagentoAPI/dev","files":["/home/dave/MagentoAPI/dev/docker-compose.yml","/home/dave/MagentoAPI/dev/dockerfile"]},{"dir":"/home/dave/MagentoAPI/dev/.app","files":["/home/dave/MagentoAPI/dev/.app/composer.json","/home/dave/MagentoAPI/dev/.app/composer.lock"]},{"dir":"/home/dave/MagentoAPI/dev/.vscode","files":["/home/dave/MagentoAPI/dev/.vscode/settings.json"]},{"dir":"/home/dave/MagentoAPI/dev/mysql-data","files":["/home/dave/MagentoAPI/dev/mysql-data/#ib_16384_0.dblwr","/home/dave/MagentoAPI/dev/mysql-data/#ib_16384_1.dblwr","/home/dave/MagentoAPI/dev/mysql-data/auto.cnf","/home/dave/MagentoAPI/dev/mysql-data/binlog.000001","/home/dave/MagentoAPI/dev/mysql-data/binlog.000002","/home/dave/MagentoAPI/dev/mysql-data/binlog.000003","/home/dave/MagentoAPI/dev/mysql-data/binlog.000004","/home/dave/MagentoAPI/dev/mysql-data/binlog.000005","/home/dave/MagentoAPI/dev/mysql-data/binlog.000006","/home/dave/MagentoAPI/dev/mysql-data/binlog.000007","/home/dave/MagentoAPI/dev/mysql-data/binlog.000008","/home/dave/MagentoAPI/dev/mysql-data/binlog.000009","/home/dave/MagentoAPI/dev/mysql-data/binlog.000010","/home/dave/MagentoAPI/dev/mysql-data/binlog.000011","/home/dave/MagentoAPI/dev/mysql-data/binlog.000012","/home/dave/MagentoAPI/dev/mysql-data/binlog.000013","/home/dave/MagentoAPI/dev/mysql-data/binlog.000014","/home/dave/MagentoAPI/dev/mysql-data/binlog.000015","/home/dave/MagentoAPI/dev/mysql-data/binlog.000016","/home/dave/MagentoAPI/dev/mysql-data/binlog.000017","/home/dave/MagentoAPI/dev/mysql-data/binlog.000018","/home/dave/MagentoAPI/dev/mysql-data/binlog.000019","/home/dave/MagentoAPI/dev/mysql-data/binlog.000020","/home/dave/MagentoAPI/dev/mysql-data/binlog.000021","/home/dave/MagentoAPI/dev/mysql-data/binlog.000022","/home/dave/MagentoAPI/dev/mysql-data/binlog.000023","/home/dave/MagentoAPI/dev/mysql-data/binlog.000024","/home/dave/MagentoAPI/dev/mysql-data/binlog.000025","/home/dave/MagentoAPI/dev/mysql-data/binlog.000026","/home/dave/MagentoAPI/dev/mysql-data/binlog.000027","/home/dave/MagentoAPI/dev/mysql-data/binlog.000028","/home/dave/MagentoAPI/dev/mysql-data/binlog.000029","/home/dave/MagentoAPI/dev/mysql-data/binlog.000030","/home/dave/MagentoAPI/dev/mysql-data/binlog.000031","/home/dave/MagentoAPI/dev/mysql-data/binlog.000032","/home/dave/MagentoAPI/dev/mysql-data/binlog.000033","/home/dave/MagentoAPI/dev/mysql-data/binlog.000034","/home/dave/MagentoAPI/dev/mysql-data/binlog.000035","/home/dave/MagentoAPI/dev/mysql-data/binlog.000036","/home/dave/MagentoAPI/dev/mysql-data/binlog.000037","/home/dave/MagentoAPI/dev/mysql-data/binlog.000038","/home/dave/MagentoAPI/dev/mysql-data/binlog.000039","/home/dave/MagentoAPI/dev/mysql-data/binlog.index","/home/dave/MagentoAPI/dev/mysql-data/ca-key.pem","/home/dave/MagentoAPI/dev/mysql-data/ca.pem","/home/dave/MagentoAPI/dev/mysql-data/client-cert.pem","/home/dave/MagentoAPI/dev/mysql-data/client-key.pem","/home/dave/MagentoAPI/dev/mysql-data/ib_buffer_pool","/home/dave/MagentoAPI/dev/mysql-data/ib_logfile0","/home/dave/MagentoAPI/dev/mysql-data/ib_logfile1","/home/dave/MagentoAPI/dev/mysql-data/ibdata1","/home/dave/MagentoAPI/dev/mysql-data/mysql.ibd","/home/dave/MagentoAPI/dev/mysql-data/private_key.pem","/home/dave/MagentoAPI/dev/mysql-data/public_key.pem","/home/dave/MagentoAPI/dev/mysql-data/server-cert.pem","/home/dave/MagentoAPI/dev/mysql-data/server-key.pem","/home/dave/MagentoAPI/dev/mysql-data/undo_001","/home/dave/MagentoAPI/dev/mysql-data/undo_002"]},{"dir":"/home/dave/MagentoAPI/dev/php-confs","files":["/home/dave/MagentoAPI/dev/php-confs/override.ini"]},{"dir":"/home/dave/MagentoAPI/dev/src","files":["/home/dave/MagentoAPI/dev/src/AttTest.php","/home/dave/MagentoAPI/dev/src/AttributesSamplePayload.json","/home/dave/MagentoAPI/dev/src/MageAPIdev.code-workspace","/home/dave/MagentoAPI/dev/src/ParentTest.php","/home/dave/MagentoAPI/dev/src/Scratch.php","/home/dave/MagentoAPI/dev/src/SirvTest.php","/home/dave/MagentoAPI/dev/src/Sirvimgtest.php","/home/dave/MagentoAPI/dev/src/SqlQueries.php","/home/dave/MagentoAPI/dev/src/UUconnparams.php","/home/dave/MagentoAPI/dev/src/UUconnparamsbulk.php","/home/dave/MagentoAPI/dev/src/autoConfig.php","/home/dave/MagentoAPI/dev/src/cats.php","/home/dave/MagentoAPI/dev/src/firstUp.php","/home/dave/MagentoAPI/dev/src/home.php","/home/dave/MagentoAPI/dev/src/imgLinkTab.php","/home/dave/MagentoAPI/dev/src/index.php","/home/dave/MagentoAPI/dev/src/login.php","/home/dave/MagentoAPI/dev/src/newGet.php","/home/dave/MagentoAPI/dev/src/newfile.txt","/home/dave/MagentoAPI/dev/src/protect-this.php","/home/dave/MagentoAPI/dev/src/scratch2.php","/home/dave/MagentoAPI/dev/src/style.css","/home/dave/MagentoAPI/dev/src/workingGUZ.php","/home/dave/MagentoAPI/dev/src/workspace.code-workspace"]},{"dir":"/home/dave/MagentoAPI/dev/.app/vendor","files":["/home/dave/MagentoAPI/dev/.app/vendor/autoload.php"]}]
--------------------
Search results
Path: /home/dave/MagentoAPI/dev/src/styles/main.scss
  isMatch: true
   - Base path: /home/dave/MagentoAPI
   - Rela path: dev/src/styles/main.scss
  compare: true
   - Orig file path: /home/dave/MagentoAPI/dev/src/styles/main.scss
   - Orig sass path: /home/dave/MagentoAPI/dev/src/styles/main.scss
--------------------
File not found, must be excluded
--------------------
File excluded
The file has not been compiled as it's excluded by user settings
Path: /home/dave/MagentoAPI/dev/src/styles/main.scss
--------------------
```

**Comment by glenn2223** [comment]
Hey @brohon,

So the great team over at `fdir` believe that they have identified the problem and resolved it. I have released alpha-2 which is available on the [ahead](https://github.com/glenn2223/vscode-live-sass-compiler/tree/ahead) branch.

Please download [`v5.2.0-alpha.2`](https://github.com/glenn2223/vscode-live-sass-compiler/blob/da5273112ee400b371cec216b0b8f2852aa0c13c/live-sass-5.2.0-alpha.2.zip) and see if it has fixed your issue.

**Comment by glenn2223** [comment]
Hey @brohon, have you had a chance to test this yet?

**Comment by brohon** [comment]
Hey @glenn2223 , not yet. Been working on the logic in my application. I'll test it this afternoon and get back to you.

**Comment by brohon** [comment]
Glenn! No Worries about pestering! It Works! Successfully made a change to the Sass file and it generated my CSS. I didn't have to specify anything in the workspace settings either, which is nice. Below is the output in case you're interested. 

Thanks for your diligence on this. It's much appreciated. The open-source world turns 'round because of people like you.

```
No workspace provided
Using originating path: /home/dave/MagentoAPI/dev/src/styles/main.scss
--------------------
Starting compilation
Starting compilation of file
Path: /home/dave/MagentoAPI/dev/src/styles/main.scss
--------------------
Autoprefixer isn't false, applying to file
Path: /home/dave/MagentoAPI/dev/src/styles/main.scss
--------------------
Preparing autoprefixer
--------------------
Starting autoprefixer
--------------------
Completed autoprefixer
--------------------
Saving file
Saving a file to the system
Target: /home/dave/MagentoAPI/dev/src/styles/main.css.map
--------------------
Saving file
Saving a file to the system
Target: /home/dave/MagentoAPI/dev/src/styles/main.css
--------------------
Changing status bar to: Success
Registered timeout to switch state back
--------------------
Generated:
/home/dave/MagentoAPI/dev/src/styles/main.css.map
/home/dave/MagentoAPI/dev/src/styles/main.css
--------------------
Registered timeout to revert UI to correct watching status
--------------------
Firing timeout function to switch back
--------------------
Changing status bar to: Watching
--------------------
Switching UI state
--------------------
Changing status bar to: Watching
--------------------
Watching...
--------------------
Firing timeout function to switch back
--------------------
Changing status bar to: Watching
--------------------
```

**Comment by glenn2223** [comment]
Glad it works and thanks for the compliment!!

I'll push v5.2-rc.1 soon!
