### ISSUE TITLE
Configuration Question

### ISSUE THREAD

**Issue by Dave-Lindberg** [glenn2223/vscode-live-sass-compiler#146]
I've installed Live Sass Compiler (@id:glenn2223.live-sass) into VS Code, and have updated settings in the project root's vscode/settings.json file, including savePath.

My project structure looks like this: 
```
/root
  /app
    /public
      ...
      /wp-content
        ...
        /themes
          ...
          /theme-name
            ...
            /sass
              style.scss
              ... 
            style.css
  /vscode
    settings.json
```

and in setting.json: `"savePath": "~/.."`

However, saving style.scss in /theme-name/sass only updates theme-name/sass/style.css, rather than theme-name/style.css.

Trying to debug this issue, I run `liveSass.command.debugFileList`, and receive the following output: 

```
--------------------
Extension Info
--------------------
Current File
--------------------
extension-output-glenn2223.live-sass-#1
--------------------
Workspace Folders
--------------------
[0] uvacswim2022
/Users/dlindberg/Local Sites/uvacswim2022
--------------------
Checking workspace folder 0 of 1
Path: /Users/dlindberg/Local Sites/uvacswim2022
--------------------
--------------------
Current Include/Exclude Settings
--------------------
Include: [ NULL ]
Exclude: [ /**/node_modules/**, /.vscode/** ]
--------------------
Included SASS Files
--------------------
...
```
followed by a lengthy list of included SASS files and Partial Files (which I can include if helpful).  

fwiw, running macOS Monterey v12.1 on an M1 Macbook Pro.

**Comment by glenn2223** [comment]
Sorry to hear you're having a problem.

I'm afraid that I'm not able to reproduce this using a sample project (here -> [Issue 146 - Sample Project.zip](https://github.com/glenn2223/vscode-live-sass-compiler/files/7825136/Issue.146.-.Sample.Project.zip)). As you can see from the below screenshot it has saved the file one folder up.

![image](https://user-images.githubusercontent.com/33450392/148463156-25d25686-f18c-4cfc-9d1e-6952a7059309.png)

Could you set your `showOutputOn` setting to trace, save the file and then include the output here?

Thanks

**Comment by Dave-Lindberg** [comment]
I appreciate your replying so promptly. I reviewed your test project, and it does indeed work as intended.  

Here's the output from saving style.scss with `showOutputWindowOn: trace`: 

```
VS Code event: "onDidSaveTextDocument"
--------------------
SASS file saved
A SASS file has been saved, starting checks
--------------------
Found the workspace folder
Workspace Name: uvacswim2022
--------------------
Checking SASS path isn't excluded
Path: /Users/dlindberg/Local Sites/uvacswim2022/app/public/wp-content/themes/hello-theme-child-master/sass/style.scss
--------------------
No base folder override found. Keeping workspace folder
--------------------
Searching folder
File found, not excluded
--------------------
Change detected - 1/7/2022, 10:29:14 AM
style.scss
--------------------
File is not a partial
The file is not a partial so we will compile only this one
Path: /Users/dlindberg/Local Sites/uvacswim2022/app/public/wp-content/themes/hello-theme-child-master/sass/style.scss
--------------------
Starting format 1 of 1
Settings: {"format":"expanded","extensionName":".css","savePath":null,"savePathSegmentKeys":null,"savePathReplaceSegmentsWith":null}
--------------------
Calculating file paths
Calculating the save paths for the css and map output files
Originating path: /Users/dlindberg/Local Sites/uvacswim2022/app/public/wp-content/themes/hello-theme-child-master/sass/style.scss
--------------------
No workspace provided
Using originating path: /Users/dlindberg/Local Sites/uvacswim2022/app/public/wp-content/themes/hello-theme-child-master/sass/style.scss
--------------------
Starting compilation
Starting compilation of file
Path: /Users/dlindberg/Local Sites/uvacswim2022/app/public/wp-content/themes/hello-theme-child-master/sass/style.scss
--------------------
Autoprefixer isn't false, applying to file
Path: /Users/dlindberg/Local Sites/uvacswim2022/app/public/wp-content/themes/hello-theme-child-master/sass/style.scss
--------------------
Preparing autoprefixer
--------------------
Changing BROWSERSLIST_DISABLE_CACHE setting
Was: 1
Now: 1
--------------------
Starting autoprefixer
--------------------
Completed autoprefixer
--------------------
Restored BROWSERSLIST_DISABLE_CACHE to: 1
--------------------
Saving file
Saving a file to the system
Target: /Users/dlindberg/Local Sites/uvacswim2022/app/public/wp-content/themes/hello-theme-child-master/sass/style.css.map
--------------------
Saving file
Saving a file to the system
Target: /Users/dlindberg/Local Sites/uvacswim2022/app/public/wp-content/themes/hello-theme-child-master/sass/style.css
--------------------
Changing status bar to: Success
Registered timeout to switch state back
--------------------
Generated:
/Users/dlindberg/Local Sites/uvacswim2022/app/public/wp-content/themes/hello-theme-child-master/sass/style.css.map
/Users/dlindberg/Local Sites/uvacswim2022/app/public/wp-content/themes/hello-theme-child-master/sass/style.css
--------------------
Registered timeout to revert UI to correct watching status
--------------------
Switching UI state
--------------------
Changing status bar to: Watching
--------------------
Watching...
--------------------
Firing timeout function to switch back
--------------------
Changing status bar to: Watching
--------------------
```

Please let me know your thoughts. Thanks!

**Comment by glenn2223** [comment]
Thanks for providing the requested info

> --------------------
> Starting format 1 of 1
> Settings: {"format":"expanded","extensionName":".css","savePath":null,"savePathSegmentKeys":null,"savePathReplaceSegmentsWith":null}
> --------------------

This part is the root cause. It seems that VS Code is not finding the `"savePath": "~/.."` setting you set and instead is using the default `null` value.

It may be that there's an incorrect spelling in the settings or possibly a misconfiguration between the top-level workspace setting file and a lower `setting.json` file.

Can I see a screenshot of the folder hierarchy in VS Code as well as any `settings.json` or `.code-workspace` files you have?

**Comment by Dave-Lindberg** [comment]
Here are the screenshots. Thanks again for all your help!

![file structure_1-of-2](https://user-images.githubusercontent.com/40928208/148628788-7c03b5f7-6b83-4075-a280-458549237506.png)
![file-structure_2-of-2](https://user-images.githubusercontent.com/40928208/148628791-1033e6c9-b2ad-4db7-be21-eabab6a3c40b.png)
![vscode-settings](https://user-images.githubusercontent.com/40928208/1486
![workspace-sattings](https://user-images.githubusercontent.com/40928208/148628800-604e1ab3-c9c0-4baa-9ae3-6bdb90ad0441.png)
28796-15f4e73c-4e4c-4b4a-a40d-f08947cc20c3.png)
![user-settings](https://user-images.githubusercontent.com/40928208/148628803-4ff9e25e-0df8-4c45-aee0-94206faafc77.png)

**Comment by glenn2223** [comment]
I can see the problem

The `vscode`folder needs to be called `.vscode` (note the dot)

Does this solve your problem?

**Comment by Dave-Lindberg** [comment]
Yes, this is exactly the source of the issue. Thank you **very** much!

**Comment by glenn2223** [comment]
No problem, glad it's sorted
