### ISSUE TITLE
I can't get a variable from another file to work

### ISSUE THREAD

**Issue by nicholusi2021** [glenn2223/vscode-live-sass-compiler#147]
I'm getting an error trying to use variables from another .scss file.

I have a file called test.scss with 

```
$color-text-default: #555;

body {
  color: $color-text-default;
}
```

That works fine with the variable in the same file.  

Now I create another file called _testvar.scss in the same folder.  It contains

```$color-text-default: #555;```

and I change test.scss to

```
@use "testvar";

body {
  color: $color-text-default;
}
```

but I get the following error: 

```
Change detected - 1/6/2022, 4:59:02 PM
test.scss
--------------------
Compilation Error
Error: Undefined variable.
  ╷
4 │   color: $color-text-default;
  │          ^^^^^^^^^^^^^^^^^^^
  ╵
  c:\StagedPages\scss\test.scss 4:10  root stylesheet
--------------------
Compilation Error
Error: Undefined variable.
  ╷
4 │   color: $color-text-default;
  │          ^^^^^^^^^^^^^^^^^^^
  ╵
  c:\StagedPages\scss\test.scss 4:10  root stylesheet
--------------------
Watching...

```

am I doing something wrong?

**Comment by glenn2223** [comment]
Yes, I'm afraid that you're doing it wrong. Please change the first line as shown below

```scss
@use "testvar" as *;
```

I'd also suggest reading up on `@use` [here](https://sass-lang.com/documentation/at-rules/use), namespaces are the FUTURE!!! 😂

Hope this helps

**Comment by nicholusi2021** [comment]
Ah, thank you!

**Comment by glenn2223** [comment]
Glad to help 😁
