### ISSUE TITLE
Absolute paths for/in map files

### ISSUE THREAD

**Issue by sKopheK** [glenn2223/vscode-live-sass-compiler#15]
Hello, I believe it's not necessary to have absolute paths with protocols generated within map files paths, might be even harmful sometimes.

Map file, e.g.:
```
{
    ...
    "file": "file:///d:/htdocs/usetri-v5/public_html/scss/calc-bs.css"
}
```
(file paths under `sources` are relative)

CSS file, e.g.:
```
/*# sourceMappingURL=file:///d:/htdocs/usetri-v5/public_html/css1/calc-bs.css.map *//*# sourceMappingURL=calc-bs.css.map */
```

**Comment by glenn2223** [comment]
Definitely an issue, thanks for the insight. Fixed in 4.3.3
