### ISSUE TITLE
Error in savePath of liveSassCompile.settings.formats 

### ISSUE THREAD

**Issue by redwan-hossain** [glenn2223/vscode-live-sass-compiler#150]
Screenshot-
![Screenshot from 2022-01-21 20-58-58](https://user-images.githubusercontent.com/15859460/150549832-3798f341-981a-4d39-ac0e-417c9addab6b.png)

OS- Ubuntu Budgie 20.04 LTS

I am getting this error while setting savePath though the compile process works fine-
Must start with any of:
`/` or `\` (for workspace root)
`~/` or `~\` for relative to the file being processed. Must not end with a path separator (`/` or `\`)

My setting for this- 

"liveSassCompile.settings.formats":[
        {
            "format": "expanded",
            "extensionName": ".css",
            "savePath": "/assets/css"
        },
        {
            "extensionName": ".min.css",
            "format": "compressed",
            "savePath": "/assets/css/min"
        }
    ]

**Comment by glenn2223** [comment]
This should be fixed in the v5.2-alpha available [here](https://github.com/glenn2223/vscode-live-sass-compiler/tree/ahead). Could you please confirm?

**Comment by redwan-hossain** [comment]
Yes. The error message is gone. Thanks for the quick update. Should I keep the alpha version or roll back to the stable one?

**Comment by glenn2223** [comment]
That's up to you. My alphas can always use more testers and, so far, the current has been stable. I'll soon be releasing rc1 which is essentially the same code as the alpha.
