### ISSUE TITLE
forceBaseDirectory stop working

### ISSUE THREAD

**Issue by slawekmoskal** [glenn2223/vscode-live-sass-compiler#153]
I have been using it for over 3 months. Everything worked fine.

Today I got the error:

_Error with your `forceBaseDirectory` setting
Can not find path: /vscode/project/~
Setting: "~/"
Workspace folder: project_

My setting:

`"liveSassCompile.settings.forceBaseDirectory": "~/"`

In one work space I have several / scss / directories and in each of them different files for different clients.

**Comment by glenn2223** [comment]
`forceBaseDirectory` has never accepted a tilde (`~`). The purpose of this setting is to move the search location to a path higher up the hierarchy - for example to a folder at `/Assets/styles/`

The tilde was only ever used in `formats[].savePath`

Are you sure it ever worked like that? Doesn't seem right

**Comment by slawekmoskal** [comment]
It worked many months on macOS 12.0 :)

**Comment by slawekmoskal** [comment]
Hi. Documentation:

```
Using savePath
Starting with / or \ means the path is relative to the workspace root
Starting with ~/ or ~\ means that it's relative to the file being processed
```
I checked if it would work in other settings ((~/ or ~\) ). And it worked. For a few weeks.

**Comment by glenn2223** [comment]
There have been no code changes to that section of code. If the setting `~/` did ever work then it would have had the same result as not including it at all. The use of `~/` was never intended to work nor is it documented.

For these reasons I am closing this issue
