### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by martijn-hovens** [glenn2223/vscode-live-sass-compiler#155]
- Issue Type: `Performance`
- Extension Name: `live-sass`
- Extension Version: `5.1.1`
- OS Version: `Darwin x64 21.2.0`
- VS Code version: `1.64.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///var/folders/j1/nnr8rdv17fg3dn7c74xz_jsr0000gp/T/glenn2223.live-sass-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by glenn2223** [comment]
Closing as info required
