### ISSUE TITLE
File is not in a workspace.

### ISSUE THREAD

**Issue by Xteripus** [glenn2223/vscode-live-sass-compiler#160]
Hi, I was editing a file from Filezilla and it gave this warning:

![image](https://user-images.githubusercontent.com/68998228/157883164-d4e57b4a-fde8-4de5-b7d5-bd63350978fc.png)

Any ideas? 

Thanks.

**Comment by glenn2223** [comment]
Yeah, I can see the issue. I have a fix ready to publish in the next day or two

**Comment by Xteripus** [comment]
Thank you 🚀
