### ISSUE TITLE
Not an issue: Just that the original package was officially deprecated :-)

### ISSUE THREAD

**Issue by realjjaveweb** [glenn2223/vscode-live-sass-compiler#161]
Hi,
because I didn't manage to find any contact information about you here, I am using this form to inform you,
that I've emailed Ritwick Dey to ask him to mark unmaintained project as deprecated and link to your maintained fork,
he replied yesterday that he'll do it and he has already done so :slightly_smiling_face:  :
https://github.com/ritwickdey/vscode-live-sass-compiler

Have a great day! :slightly_smiling_face: 
Thanks Ritwick Dey for creating this and you for keeping it up to speed :slightly_smiling_face:

**Comment by glenn2223** [comment]
Not a problem.

Yeah, I had an email from Ritwick on Thursday saying how he'd deprecated his extension and pointed those over to mine.

Thanks for the praise, always appreciated 🤩
