### ISSUE TITLE
Prefixes are not working

### ISSUE THREAD

**Issue by Xteripus** [glenn2223/vscode-live-sass-compiler#165]
Hi, I noticed that prefix are not working the old plugin used to add prefixes automatically I checked the prefix section in the documentation but it didn't work. 

Thanks!

**Comment by glenn2223** [comment]
Most prefixes are now no longer required. If you are requiring them for a specific browser then you need to target it.

What prefix are you expecting?

**Comment by Xteripus** [comment]
I was expecting something like this:
`display: -webkit-box;
    display: -ms-flexbox;
    display: flex;
    -webkit-box-pack: end;
    -ms-flex-pack: end;
    justify-content: flex-end;
    -webkit-box-align: center;
    -ms-flex-align: center;
    align-items: center`
But if it's no longer required it's ok I guess.

**Comment by glenn2223** [comment]
Yeah, `flex` has really good support so those prefixes aren't required any more - though you can specify a browser/setting. However, by adding these prefixes, you are only supporting an extra 0.6% accumatively (the default for autoprefixer is now `> 0.5%, last 2 versions, Firefox ESR, not dead`)

But, biggest win here, SMALLER FILE SIZES YAY!! 😂

---

Closing. But, if you have any further questions then comment again 😁

**Comment by Xteripus** [comment]
You are the best🚀!

**Comment by AngelikaBlend** [comment]
Hey @glenn2223,  We have the same problem with some of our developers on the team. It causes some issues when one person in the team saves files with prefixes and others don't. Is it possible to enable those prefixes with settings?

**Comment by glenn2223** [comment]
If different members of the team are using different extension versions/IDEs then there will always be discrepancies between them.

However, that being said, you should set `autoprefixer` to `true` and have your `browserlist` settings in a shared file (whether that's a `.browserlistsrc` file or embedded in the `package.json`). This will unify the output, providing that whatever compilation platform you're all using supports it (hopefully mine 😁 - which does)

You can see more about the setting in the docs [here](https://github.com/glenn2223/vscode-live-sass-compiler/blob/master/docs/settings.md#livesasscompilesettingsautoprefix) and about it's usage/format [here](https://github.com/browserslist/browserslist#browserslist-)

Also, the current default value is `defaults`. I'd suggest you use this and add other options that best suit your needs. A list of what browserslist functions/commands are supported can be seen [here](https://github.com/browserslist/browserslist#full-list)

**Comment by JayaSaiKiran** [comment]
Thank you glenn i have changed the settings in vs-code 
 //autoprefix, will auto add perfix like -webkit- -moz-..
    "liveSassCompile.settings.autoprefix": [
        "> 1%",
        "last 2 versions"
    ]
Its is working as expected.
