### ISSUE TITLE
Compiler doesn't look at imported files

### ISSUE THREAD

**Issue by T-D3V** [glenn2223/vscode-live-sass-compiler#166]
Hey so I have a styles.scss where i  @import another file and it won't recognise the changes from the other file can anybody help me.

thx

**Comment by glenn2223** [comment]
The partial file needs to start with an underscore `_` for the system to register changes and save other files (indirectly related to #17)

**Comment by T-D3V** [comment]
![image](https://user-images.githubusercontent.com/40610605/160854022-193c6db8-680f-4c22-b04d-340768425ab9.png)
My Files are structured like this

**Comment by T-D3V** [comment]
user workspace or directory?

**Comment by T-D3V** [comment]
![image](https://user-images.githubusercontent.com/40610605/160873283-9eb25cab-99bf-478a-b146-6424d45b55fe.png)
that's my workspace don't have a settings.json in .vscode tbh

**Comment by T-D3V** [comment]
have most things in the user settings

**Comment by glenn2223** [comment]
Can you follow the below steps:
1. Run the command (by first pressing <kbd>F1</kbd>) `liveSass.command.showOutputOn.information`
2. Go to the partial file
3. Save the file
4. Copy the output I (that should pop up) into a new comment

---

Just FYI, the first command should create a `settings.json` (if it doesn't exist) as you have altered the default settings

**Comment by glenn2223** [comment]
Sorry, updated by comment, I meant `trace` not `information`

**Comment by T-D3V** [comment]
Yo so I just checked it again and everything worked I'm guessing I had a wrong property which of course wouldn't be compiled.
Anywas thanks for the help It all works now btw. great extension love it.

**Comment by glenn2223** [comment]
Just glad you got it working. If you have any other issues then just post another comment.

Thanks
