### ISSUE TITLE
Not compiling scss into css

### ISSUE THREAD

**Issue by paulsally** [glenn2223/vscode-live-sass-compiler#167]
### Not compiling scss into css

**Machine & Versions**
| Item | Value |
|----------------------:|:-----------------------|
| VS Code | v1.65.2 |
| Platform | darwin arm64 |
| Node | 14.16.0 (89) |
| Live Sass | 5.3.0 |
<details><summary>Installed Extensions</summary><div>
- vscode.configuration-editing (1.0.0)<br/>- vscode.css-language-features (1.0.0)<br/>- vscode.debug-auto-launch (1.0.0)<br/>- vscode.emmet (1.0.0)<br/>- vscode.git (1.0.0)<br/>- vscode.git-base (1.0.0)<br/>- vscode.github (0.0.1)<br/>- vscode.github-authentication (0.0.2)<br/>- vscode.ipynb (1.0.0)<br/>- vscode.json-language-features (1.0.0)<br/>- vscode.merge-conflict (1.0.0)<br/>- vscode.microsoft-authentication (0.0.1)<br/>- vscode.typescript-language-features (1.0.0)<br/>- atlassian.atlascode (2.10.11)<br/>- bajdzis.vscode-twig-pack (1.1.0)<br/>- bradlc.vscode-tailwindcss (0.7.7)<br/>- DmitryDorofeev.empty-indent (0.2.0)<br/>- eamodio.gitlens (12.0.5)<br/>- ecmel.vscode-html-css (1.11.0)<br/>- esbenp.prettier-vscode (9.5.0)<br/>- formulahendry.code-runner (0.11.7)<br/>- glenn2223.live-sass (5.3.0)<br/>- josee9988.minifyall (2.10.0)<br/>- mblode.twig-language (0.9.2)<br/>- mrmlnc.vscode-scss (0.10.0)<br/>- ms-vsliveshare.vsliveshare (1.0.5449)<br/>- oderwat.indent-rainbow (8.2.2)<br/>- pranaygp.vscode-css-peek (4.2.0)<br/>- redhat.vscode-yaml (1.6.0)<br/>- ritwickdey.LiveServer (5.7.5)<br/>- Zignd.html-css-class-completion (1.20.0)
</div></details>

**LOG**: 
```JSON
{
"NO LOG": "PLEASE SPECIFY YOUR ISSUE BELOW"
}
```
=======================

**Comment by glenn2223** [comment]
Sorry to hear you're having an issue.

Did the application close (or did you close it) before you ran the command to open this issue? I only ask because there is no error information provided in the copy.

Is this happening for every file?

Can you provide the SASS you were trying to save (or, better yet, a zip of the whole code)?

Can you also set the 'showOutputWindowOn' setting to trace and save the same file again then provide the output here?

Thanks in advance

**Comment by glenn2223** [comment]
I'm assuming this is an application error. It may be that there is a SASS error. Have you tried converting to `@use` instead of `@import`? Does the icon in the bottom right switch to 'Error` when you save a file?

**Comment by glenn2223** [comment]
Closing as info required
