### ISSUE TITLE
[question] How to choose the specific project to compile and for watching ?

### ISSUE THREAD

**Issue by iamrealmarsel** [glenn2223/vscode-live-sass-compiler#170]
Hi there!
I opened one project in vs code, worked in it and everything is ok. Then I decided to add the second project into vs code, it's not for work, but just for reference. When I ran Live Sass, it compiled the styles in all projects:  
![Screen Shot 2022-04-11 at 4 43 35 PM](https://user-images.githubusercontent.com/20097612/162754424-4c7a474e-2766-4087-ada6-04e2e0db1f0b.png)

Why does it do it and how can I choose only one project? For example, the Live Server extension at first asks which project to run:  
![Screen Shot 2022-04-11 at 4 43 40 PM](https://user-images.githubusercontent.com/20097612/162754763-ffb5de3f-3c8c-4e05-8ccc-7ca47aac3b0b.png)

Thank you.

**Comment by glenn2223** [comment]
You should have a `.workplace-code` file now and you can ignore that folder or in the settings fine in the second project you can ignore it there instead

**Comment by iamrealmarsel** [comment]
Got it. It's a pity that I can't just select the root folder with mouse click like in Live Server, but thank you very much for your answer!
