### ISSUE TITLE
SCSS is not generating automatic -webkit, -moz, properties to the CSS file...

### ISSUE THREAD

**Issue by JayaSaiKiran** [glenn2223/vscode-live-sass-compiler#174]
Is there any solution for this extension to get those -webkit, -moz, properties to the CSS file automatically instead of manually writing all browser compatibility properties in scss.

Where as ritwickdey sass extension  adds automatically  -webkit, -moz, properties to the CSS file.

**Comment by glenn2223** [comment]
Please see #165 

Thanks
