### ISSUE TITLE
Unhandled Error While Compiling All Files

### ISSUE THREAD

**Issue by johncanero** [glenn2223/vscode-live-sass-compiler#175]
SASS Compiler not working when I was clicking SASS Watch.

**Comment by glenn2223** [comment]
Do you have any further information? What are your settings? Are you expecting all files to compile or is it an error with a specific file?

The extension is working so it may be a setting issue or an error with your SASS

**Comment by glenn2223** [comment]
Hey @johncanero, do you have any other information?

**Comment by johncanero** [comment]
Hi glenn2223, I am sorry for the late notice and reply. It is now fixed. I was able to edit the settings in json. Thank you! I am new to Sass. Hopefully, I can understand it fully and learn it well.

**Comment by glenn2223** [comment]
Glad you got it sorted 😁
