### ISSUE TITLE
not compiling files if prefixed with underscore.

### ISSUE THREAD

**Issue by umair2288** [glenn2223/vscode-live-sass-compiler#176]
if we named the file as _main.scss instead of main.scss it's not compiling and showing no errors. I'm not sure is it an intended behaviour. if it is it's better to be documented.

**Comment by glenn2223** [comment]
Hey, sorry for the delay. To keep the code simple it treats all files with a leading underscore as a partial file. Saving a partial file compiles all non-partial files on the project. You can tweak this functionality by changing the `liveSassCompile.settings.partialsList` setting

I agree that it could be clearer. I will get add some documentation added about it

**Comment by bfren** [comment]
I'm having the opposite problem - my partials are compiling when I save them! Is that expected behaviour?  I would expect them to be ignored, and only compiled when a file that imports them is compiled?

**Comment by glenn2223** [comment]
Added more documentation in v5.4.0
