### ISSUE TITLE
Root reference goes to drive root rather than repository root

### ISSUE THREAD

**Issue by cmothersead** [glenn2223/vscode-live-sass-compiler#177]
I'm certain I'm missing something obvious here, but I am trying to use the '@use' rule and reference a file at the root directory of my workspace ex: @use "/example"; but the file is not found as that path is trying to reference C:/example.scss rather than [workspace_root]/example.scss like I expect/want.

Do I need to configure something? I cannot find any reference to someone having similar issues with this or any sass compilers.

**Comment by glenn2223** [comment]
Thanks for reporting this issue. I will work on this soon.

All I need to do is add another customer importer. Not sure if this will classify as a breaking change though... thoughts 🤷‍♂️

**Comment by glenn2223** [comment]
Load paths refer wouldn't work, unfortunately. They refer to adding a direct reference to a location that you can then use in shorthand - _"if you pass `node_modules/susy/sass` as a load path, you can use `@use "susy"` to load `node_modules/susy/sass/susy.scss`"_

I have an alpha with the change applied (below), you just need to add `"liveSassCompile.settings.rootIsWorkspace": true` to your settings. Does it work as you'd like/expect?

[live-sass-5.4.0-alpha.2.zip](https://github.com/glenn2223/vscode-live-sass-compiler/files/8698561/live-sass-5.4.0-alpha.2.zip)

**Comment by cmothersead** [comment]
Seems to be working for me at the moment! Much appreciated. I'll let you know if I run into any issues as I "clean up" my workspace of all the relative references...

**Comment by glenn2223** [comment]
Glad it's working @cmothersead. I assume it worked on the rest of the project?

**Comment by cmothersead** [comment]
Yeah, I haven't had any issues with it. Worked as expected for the whole project!

**Comment by glenn2223** [comment]
Thanks for confirming, I'll publish officially soon!

**Comment by glenn2223** [comment]
Now available in v5.4.0
