### ISSUE TITLE
Do not remove @charset "UTF-8" when minify output .min.css?

### ISSUE THREAD

**Issue by saosangmo** [glenn2223/vscode-live-sass-compiler#179]
Dear @glenn2223 ,

I want to include `@charset "UTF-8";` at the top CSS file but after minify .css files, you plugin remove this text?

-Dzung Do

**Comment by glenn2223** [comment]
The output should include a BOM in compressed mode, which is shorter but has the same effect. Please refer to sass/dart-sass#1387
