### ISSUE TITLE
Output window not accessible when watchOnLaunch is on

### ISSUE THREAD

**Issue by sKopheK** [glenn2223/vscode-live-sass-compiler#18]
Have to turn the watch off and on again to see output window when the `watchOnLaunch` option is set to true.
![image](https://user-images.githubusercontent.com/5802917/105180848-fc02f500-5b22-11eb-9f01-0bfcf17de4fb.png)

**Comment by glenn2223** [comment]
Thanks for highlighting this, I was experiencing this yesterday but couldn't remember how to replicate it when I got home 😁

Fixed for next release. Which I can publish tonight when I get back home 👍
