### ISSUE TITLE
save css based on scss file wrapper may be a feature

### ISSUE THREAD

**Issue by abdallaoui-dev** [glenn2223/vscode-live-sass-compiler#184]
I'm facing a problem in my project,
I fix it but my problem is that I'm running two cmds
for this I want to share my fix

I have a project looks like this:

```

-- dist
  --css

--src
  --scss
    --about
        laptop-desktop
             _other_files.scss
             laptop-desktop.scss
        mobile-portrait
             _other_files.scss
             mobile-portrait.scss
    --home
        laptop-desktop
             _other_files.scss
             laptop-desktop.scss
        mobile-portrait
             _other_files.scss
             mobile-portrait.scss

```
when I hit save my dist looks like this

```
--dist
   --css
          laptop-desktop.scss
          mobile-portrait.scss
```

what I need in dist:
```
--dist
  --css
    --about
           laptop-desktop.css
           mobile-portrait.css
    --home
           laptop-desktop.css
           mobile-portrait.css
```
I know this is not explained well because I'm not good in english
I made a great example explains my problem I hob you take a look. Thanks
https://github.com/abdallaoui-dev/scssIssue

**Comment by glenn2223** [comment]
Hey @abdallaoui-dev, can you check the below preview works as you'd expect. It works in my all my tests

[live-sass-5.5.0.zip](https://github.com/glenn2223/vscode-live-sass-compiler/files/9040352/live-sass-5.5.0.zip)

**Comment by glenn2223** [comment]
Have you had the chance to test it yet @abdallaoui-dev?
