### ISSUE TITLE
how to input multiple *.scss files and output one css file?

### ISSUE THREAD

**Issue by nigelwhite** [glenn2223/vscode-live-sass-compiler#188]
Can anyone suggest how to go about doing this?

I have several scss files, one for each component. [I'm using Drupal UI Patterns]. The vscode-live-sass-compiler is brilliant at finding all the scss files, using wildcards in "liveSassCompile.settings.includeItems". However the output is multiple css files: one css file for each scss file. This means more maintenance overhead as I have to take further steps.

How would I go about outputting all my components' scss into one css? It would be great to create more components without having to manually signpost each one's css.

Thanks

I've tried 2 other approaches and got to simlar more-maintenance-overhead positions -
1. @import statements to compile sass partials into a final sass file. You have to add each partial manually because you can't use wildcards.
2. In Drupal THEME.libraries.yml we can add a library but we can't use wildcards so we have to reference each component manually

**Comment by glenn2223** [comment]
Sorry this is a compiler that follows Sass best practices. You can only have a single output by having all files imported into a main file. Order is critical in css and adding files in unspecified locations could break the layout.

If this is something you require then you can see if a packaging software will work, like webpack... maybe 🤷‍♂️

**Comment by nigelwhite** [comment]
Ah yes, you're right. Thank you
