### ISSUE TITLE
Output console opens every time I save a sass file while watching sass

### ISSUE THREAD

**Issue by simonfarah** [glenn2223/vscode-live-sass-compiler#189]
Hello! Just switched to this extension after Ritwick's one got deprecated and actually have a question. When watching my sass files, every time a sass file is saved, the output console pops up which is actually pretty annoying. I was used to see the console only when launching the watch sass, when I have an error in the sass while compiling and when I stop the watching. This behavior was not present in the other extension. Is there a way to stop this? Thanks!

**Comment by glenn2223** [comment]
Hey @simonfarah, the setting you want to change is [showOutputWindowOn]( https://github.com/glenn2223/vscode-live-sass-compiler/blob/master/docs/settings.md#livesasscompilesettingsshowoutputwindowon)

You can choose your level of output by adjusting this setting
