### ISSUE TITLE
Live Sass: Watch Sass resulted in an error

### ISSUE THREAD

**Issue by chrismtb12** [glenn2223/vscode-live-sass-compiler#19]
Extension installs fine, but Watch Sass doesn't appear on the status bar and when pressing F1 and selecting Live Sass: Watch Sass this error message appears.
"Command 'Live Sass: Watch Sass' resulted in an error (command 'liveSass.command.watchMySass' not found)"

This is on Windows10.

**Comment by chrismtb12** [comment]
> 
> 
> Extension installs fine, but Watch Sass doesn't appear on the status bar and when pressing F1 and selecting Live Sass: Watch Sass this error message appears.
> "Command 'Live Sass: Watch Sass' resulted in an error (command 'liveSass.command.watchMySass' not found)"
> 
> This is on Windows10.

**Comment by glenn2223** [comment]
I noticed you've closed this issue, have your resolved the issue. If so, what happened? I only ask because it may help someone else or even be something for the FAQ

If not, can you send me your workspace (or part of it) for testing?

**Comment by chrismtb12** [comment]
> 
> 
> I noticed you've closed this issue, have your resolved the issue. If so, what happened? I only ask because it may help someone else or even be something for the FAQ
> 
> If not, can you send me your workspace (or part of it) for testing?

Hi Glenn,

Sorry.

Yes i was adding the complier as part of an online course that required Sass. The Watch Sass was not being displayed in the status bar of vsCode and F1 then Live SASS: Watch SASS was not working either.

But it turns out you need to have .scss file in an open folder along with the index.html for Watch Sass to appear in the status bar.

The video i watched the Watch Sass appeared once the tutor installed it but did not have a .scss file which is why i was wondering why it was not working.

Hope this helps.

I appreciate the quick reply.

**Comment by glenn2223** [comment]
I suspected it was a missing sass file. Thanks for confirming 👍

It's set up in VS Code to start only when certain filetypes are in open/in the the workspace.
