### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by whitersun** [glenn2223/vscode-live-sass-compiler#190]
- Issue Type: `Performance`
- Extension Name: `live-sass`
- Extension Version: `5.4.0`
- OS Version: `Windows_NT x64 10.0.19044`
- VS Code version: `1.68.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///c%3A/Users/user/AppData/Local/Temp/glenn2223.live-sass-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by glenn2223** [comment]
> ⚠️ Make sure to **attach** this file from your _home_-directory: 
> ⚠️`file:///c%3A/Users/user/AppData/Local/Temp/glenn2223.live-sass-unresponsive.cpuprofile.txt`

Please can you provide this file
