### ISSUE TITLE
Live Sass Compiler

### ISSUE THREAD

**Issue by xlsmile** [glenn2223/vscode-live-sass-compiler#192]
After updating the Compiler to the Glenn Marks' version, as VScode suggested, the Compiler stopped working. The Ritwick Day's one worked like a charm! I know it has to do with custom user settings, but why not to keep the previous setting without overriding them?

**Comment by glenn2223** [comment]
You should be able to just switch, any settings that I have replaced have had the original deprecated with the functionality staying the same.

What issues did you face?

**Comment by xlsmile** [comment]
Thanks, Glenn. After the installation of a new version, the compiler stopped working completely (reload and all other stuff was done, of course). It then appeared that the settings from the previous version were not automatically migrated. So, I had to add them manually in "Workspace" to make things work in a new compiler. That was just annoying. Thank you!

**Comment by glenn2223** [comment]
Strange, maybe VS Code removes settings when an extension is uninstalled to keep the users' settings cleaner?????
---
Closing as out of scope (a VS issue it seems)
