### ISSUE TITLE
Please tell me how to prevent quotes from turning into double quotes.

### ISSUE THREAD

**Issue by konsole257** [glenn2223/vscode-live-sass-compiler#196]
Please tell me how to prevent quotes from turning into double quotes.

**Comment by glenn2223** [comment]
I'm afraid that it's not the extension itself that is making this change. The extension uses the [sass/dart-sass](https://github.com/sass/dart-sass/issues) package, so you'd be better opening an issue/discussion there and they can assist or explain why it does this

---

Closing as out of scope for this project
