### ISSUE TITLE
I have a problem!!!!!!

### ISSUE THREAD

**Issue by Ilya2201** [glenn2223/vscode-live-sass-compiler#202]
hello, with your last update, it became impossible to find a setting on how to paste the copied classes into SCSS using the BEM methodology, using such a symbol "&"!!!!!!!!!

**Comment by glenn2223** [comment]
This extension doesn't have any BEM settings. The `&` is working as expected in the latest release.

Are you sure you don't have another extension that is handling BEM support (maybe [Bem Helper](https://marketplace.visualstudio.com/items?itemName=Box-Of-Hats.bemhelper))

**Comment by glenn2223** [comment]
Closing as more info required
