### ISSUE TITLE
Error: Can't find stylesheet to import

### ISSUE THREAD

**Issue by lijianxiong0324** [glenn2223/vscode-live-sass-compiler#206]
I want to compile a SCSS file to CSS but it gives me the error below, does anyone know how to solve this?

Compilation Error
Error: Can't find stylesheet to import.
  ╷
1 │ @import "..\bootstrap\scss\bootstrap.scss";
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  d:\Arbet\Övriga\Webbplats Iran\Project\scss\main.scss 1:9  root stylesheet

**Comment by glenn2223** [comment]
It is not finding the file you are saying is at: `d:\Arbet\Övriga\Webbplats Iran\Project\bootstrap\scss\bootstrap.scss`. You will need to adjust the path so it points to the correct path.

Hope this makes sense

**Comment by lijianxiong0324** [comment]
> It is not finding the file you are saying is at: `d:\Arbet\Övriga\Webbplats Iran\Project\bootstrap\scss\bootstrap.scss`. You will need to adjust the path so it points to the correct path.
> 
> Hope this makes sense

Thank you for your reply, I have solved the problem by writting 

@import "../bootstrap/scss/bootstrap.scss" 

instead of

@import "..\bootstrap\scss\bootstrap.scss"

because \b, \s, \b in the path are read as metacharacters, and "..\\bootstrap\\scss\\bootstrap.scss" won't be considered as valid path here...

**Comment by glenn2223** [comment]
>because \b, \s, \b in the path are read as metacharacters, …

Wow, didn't realise it did that on import URLs. Well, every day is a learning day 😂

Glad you figured it out
