### ISSUE TITLE
Changes are not detected.

### ISSUE THREAD

**Issue by sefacndmr01** [glenn2223/vscode-live-sass-compiler#207]
It suddenly stopped detecting changes in all workspaces. I tried reinstall extension, restart editor. Output says "Watching..." but still not detects changes. Help please :(

Edit: Just detects included file. Excluded files are not detecting.

settings.json:

![image](https://user-images.githubusercontent.com/18026221/180506795-664518e7-cfb1-4d02-b614-03b795630912.png)

**Comment by sefacndmr01** [comment]
When excludeList paths start with `/` or `\` not detecs changes. But VSCode warns "Must start with a path separator (`/` or `\`)" for excludeList list paths.

**Comment by glenn2223** [comment]
In my fork, `excludeList` checks any saved SASS file to see if it's excluded, whether partial or not.

You don't need to exclude partial files, if they start with a (standard practice) underscore - i.e. `_partial-variables.scss`

If you do not have your partials beginning with an underscore then you will want to change the setting from `excludeList` to [`partialsList`](https://github.com/glenn2223/vscode-live-sass-compiler/blob/master/docs/settings.md#livesasscompilesettingspartialslist). This then tells the compiler not to create a `.css` for the matching files, but rather compile the main file instead.
