### ISSUE TITLE
Cant see watch sass

### ISSUE THREAD

**Issue by Valvepl** [glenn2223/vscode-live-sass-compiler#209]
Hey there,
I can't sadly see watch sass button. No clue why. 
My settings:

![unknown (1)](https://user-images.githubusercontent.com/102621104/181375347-4de88b81-c006-4210-add8-3c3d348e5c57.png)
![unknown](https://user-images.githubusercontent.com/102621104/181375349-eca1cae9-5c24-46b1-a705-96bbcc1c6892.png)
![Zrzut ekranu 2022-07-27 232242](https://user-images.githubusercontent.com/102621104/181375512-86ff47d1-2ca4-428e-8a40-e27622e1c6c7.png)

**Comment by glenn2223** [comment]
The extension only activates when a SASS/SCSS file is open (or in the workspace), you currently have a CSS file open.

**Comment by glenn2223** [comment]
Did this work @Valvepl ?

----

Closing as looks to be used error
