### ISSUE TITLE
please add a feature (compile on file change)

### ISSUE THREAD

**Issue by Bugnutiy** [glenn2223/vscode-live-sass-compiler#210]
I have to use a different code editor. VS Code is used as a SCSS compiler on the server. Could you add a compile start when the file is changed? That is, not when saving a file, but when changing it by an external program.

**Comment by glenn2223** [comment]
Sorry but VSCode watches for file changes and then notifies the extension, which the below code shows/utilises. There is no actual file watching done by the extension itself.

https://github.com/glenn2223/vscode-live-sass-compiler/blob/84738b5f8a33c739bbfd6564d720a3de80fb2968/src/extension.ts#L172-L180

The only workaround I can see is [Remote Development using SSH](https://code.visualstudio.com/docs/remote/ssh). This is where the "host" has an instance of VSCode with this extension installed. Then a client connects to the "host" and can save files to trigger compilation. However, I'm pretty sure it still requires VS Code (sorry not too familiar with this kind of setup)

---

Closing as out of scope. A dedicated file watcher program is required to match specific requirements. If you have further questions/comments then please continue to comment on this issue
