### ISSUE TITLE
Working on it bug

### ISSUE THREAD

**Issue by letsevenoddz** [glenn2223/vscode-live-sass-compiler#213]
Hello!
I just uploaded the extention on VSCode but I cannot use it on my system. I click on Watch Sass but it gives an erorr in the end.

![image](https://user-images.githubusercontent.com/93825115/184531446-2a1b460d-acea-4f1d-a774-b4289216d620.png)
![image](https://user-images.githubusercontent.com/93825115/184531556-fa4c311e-ec5c-4ad1-84d2-23cb76506124.png)

**Comment by glenn2223** [comment]
Can you set [`showOutputWindowOn`](https://github.com/glenn2223/vscode-live-sass-compiler/blob/master/docs/settings.md#livesasscompilesettingsshowoutputwindowon) then paste the output here.

Also, how large is your workspace (all files, not just sass ones)?

**Comment by letsevenoddz** [comment]
@glenn2223 I have many projects in one folder and it was opened in VSCode. I moved large portion of them to my archive and now it's working! Thanks!
