### ISSUE TITLE
Missing relative paths of in- and output folders

### ISSUE THREAD

**Issue by Herb2511** [glenn2223/vscode-live-sass-compiler#214]
We didn't find a solution for our problem to navigate out of our scss-folder structure and put the output css into the same folder structure in the main css-folder. 

![image](https://user-images.githubusercontent.com/49374651/185124081-6b1b48b2-9f56-40ff-9f86-e52439960d8c.png)

All our workarounds were unsuccessful. savePaths like "/css/., ~/., /. ~/../../.. " didn't fix the problem. It would be useful to use further properties, to configure something like this for a multiple folder-root:

 "liveSassCompile.settings.formats": [

folder1 {
     {
      "format": "expanded",
      "extensionName": ".css",
      "srcPath": "/scss/global/desktop/",
      "savePath": "/css/global/desktop/"
    }
},

folder 2 {
     {
      "format": "expanded",
      "extensionName": ".css",
      "srcPath": "/scss/global/mobile/",
      "savePath": "/css/global/mobile/"
    }
},
etc.
  ],

**Comment by glenn2223** [comment]
If you want to keep the exact same file structure then you'd need `savePathReplacementPairs`. Maybe something like the below (untested)

```js
"liveSassCompile.settings.formats": [
{
    "format": "expanded",
    "extensionName": ".css",
    "savePathReplacementPairs": {
        "/scss/": "/CSS/"
    }
}]
```

**Comment by Herb2511** [comment]
> If you want to keep the exact same file structure then you'd need `savePathReplacementPairs`. Maybe something like the below (untested)
> 
> ```js
> "liveSassCompile.settings.formats": [
> {
>     "format": "expanded",
>     "extensionName": ".css",
>     "savePathReplacementPairs": {
>         "/scss/": "/CSS/"
>     }
> }]
> ```

Thank you. That worked immediately and saved our problem after some tests. Now after local testing we can use your compiler in our production workspace. Great!
