### ISSUE TITLE
CSS Unknown Properties.

### ISSUE THREAD

**Issue by ChrisNColeman** [glenn2223/vscode-live-sass-compiler#219]
Sass compiler does not recognise some properties -

1)  dominant-baseline
2) r 'SVG radius'

Chris.

ps. Just an issue, not a pain !

**Comment by glenn2223** [comment]
Sorry, not sure what you mean by `does not recognise`? Are they being removed?

**Comment by ChrisNColeman** [comment]
Glen, looks like I made a mistake -

      ```
  .text,
        .hourText,
        .am_pm {
            // font-family: Consolas, monospace;
            font-family: 'Courier New', Courier;
            font-weight: 600;
            text-anchor: middle;
            dominant-baseline: middle;
        }
```
Is producing messages like -
   Unknown property: 'r'
   Unknown property: 'dominant-baseline'

However, it looks like they're not coming from 'live-sass-compile', so apologies ..

Chris.

**Comment by glenn2223** [comment]
Not a problem. Glad you got to the bottom of it 😁
