### ISSUE TITLE
css attributes compiles without quotation marks

### ISSUE THREAD

**Issue by schalk-barnard** [glenn2223/vscode-live-sass-compiler#220]
Attributes not compiled with quotation marks eg.

.navbar__collapse[aria-expanded="false"] {
  width: 0;
}

compiles to

.navbar__collapse[aria-expanded=false] {
  width: 0;
}

**Comment by glenn2223** [comment]
The built-in SASS tool will strip quotes if they are not required. There a handy article I found that provides some examples of when they would be, you can see it below

https://mathiasbynens.be/notes/unquoted-attribute-values#css

---

If this is causing a genuine issue in your code then you'd have to report it over at the compiler: [sass/dart-sass](https://github.com/sass/dart-sass)
