### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by hamzaejaz787** [glenn2223/vscode-live-sass-compiler#222]
- Issue Type: `Performance`
- Extension Name: `live-sass`
- Extension Version: `5.5.1`
- OS Version: `Windows_NT x64 10.0.19044`
- VS Code version: `1.71.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///c%3A/Users/hejaz/AppData/Local/Temp/glenn2223.live-sass-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load
[glenn2223.live-sass-unresponsive.cpuprofile.txt](https://github.com/glenn2223/vscode-live-sass-compiler/files/9539788/glenn2223.live-sass-unresponsive.cpuprofile.txt)

**Comment by therealcoolpup** [comment]
Pity there aren't many alternatives to this POS extension.

**Comment by glenn2223** [comment]
Sorry for the delay, got a lot on with uni studies, full-time work and general dad duties.

Thanks for providing the file, it looks like the issue lies inside the SASS compiler itself. if you install the npm SASS extension and compile the same file using that do you still have this issue/slowness?

I doubt it will help much, as the move to fdir removed this overhead. However, if you have many files (not just SASS), the `forceBaseDirectory` setting **_may_** help.

**Comment by glenn2223** [comment]
Hey @therealcoolpup, there are many alternatives!!! You could buy premium software, which has many staff members dedicated to its success. You could debug the problem and PR a solution _(hey, welcome to open source)_. Or you could fund my salary!!!!!!, I'd love to quit my job and spend all my working hours developing open-source software!

Though, the main thing you can do is not complain about a FREE open-source extension that I have dedicated countless hours to - for your companies to profit from 😉

**Comment by therealcoolpup** [comment]
@glenn2223 All software, free or not is subject to criticism.

Digression. Im not sure who was controlling the vs code extension but the old one was working fine and now for some reason it is deprecated (installed new one and it works), why? 

Why are you surprised you aren't making much from this? Thats the nature of open source, you give your everything and get nothing in return.

**Comment by glenn2223** [comment]
@therealcoolpup: to save spamming this issue, I have opened a discussion at #223

**Comment by glenn2223** [comment]
Any luck @hamzaejaz787?

**Comment by hamzaejaz787** [comment]
I found using the 'Minimum Static Site Setup with Sass' suitable for my needs so I've currently switched to that

**Comment by glenn2223** [comment]
No problem. Thanks for coming back to me 

---

Closing as more info required
