### ISSUE TITLE
Live Sass Compiler not work after update

### ISSUE THREAD

**Issue by rahmathidawe** [glenn2223/vscode-live-sass-compiler#224]
hello, i just update live sass compiler extension and it's not working as previous version...
please let me know how to solve it
![2022-09-30_06-21](https://user-images.githubusercontent.com/52455138/193158919-14376dc8-4dcc-442f-b9f5-01adbe95d041.png)

**Comment by glenn2223** [comment]
Can I see your `settings.json` file?

**Comment by rahmathidawe** [comment]
{
    "sftp.downloadWhenOpenInRemoteExplorer": true,
    "editor.wordWrap": "on",
    "files.associations": {
        ".htaccess": "ini"
    },
    "liveServer.settings.donotShowInfoMsg": true,
    "editor.renderWhitespace": "all",
    "diffEditor.wordWrap": "on",
    "liveSassCompile.settings.includeItems": [
        "D:\\Lab\\js\\jquery3.5.min.js"
    ],
    "explorer.confirmDelete": false,
    "terminal.integrated.confirmOnExit": true,
    "terminal.integrated.cursorBlinking": true,
    "terminal.integrated.environmentChangesIndicator": "on",
    "workbench.startupEditor": "newUntitledFile",
    "workbench.activityBar.visible": true,
    "liveServer.settings.donotVerifyTags": true,
    "workbench.editor.enablePreview": false,
    "security.workspace.trust.untrustedFiles": "open",
    "fontAwesomeAutocomplete.patterns": [
        "**/*.html",
        "**/*.php"
    ],
    "git.autofetch": true,
    "php.suggest.basic": false,
    "editor.minimap.enabled": false,
    "git.enableSmartCommit": true,
    "git.confirmSync": false,
    "security.workspace.trust.emptyWindow": false,
    "editor.hover.enabled": false,
    "liveSassCompile.settings.autoprefix": [
    
    ]
}

**Comment by glenn2223** [comment]
> ```js
>     "liveSassCompile.settings.includeItems": [
>         "D:\\Lab\\js\\jquery3.5.min.js"
>     ],
> ```

This is your problem line it seems. You are only telling the SASS compiler to compile a `JS` file. You'd need to either remove this line or change it to target the correct file

**Comment by rahmathidawe** [comment]
thanks glenn, I will try your advise

**Comment by glenn2223** [comment]
Great! Can you let me know how it goes so I/you can close the issue? Thanks in advance

**Comment by rahmathidawe** [comment]
I don't know where it came from, but I think it's from windows 10 update. but thank you very much, it's work well now

**Comment by glenn2223** [comment]
Glad it worked!!
