### ISSUE TITLE
Output window steals focus from Terminal

### ISSUE THREAD

**Issue by 4e576rt8uh9ij9okp** [glenn2223/vscode-live-sass-compiler#225]
Hi, I couldn't find any solution for that.
But then I ctrl+s and it auto compiles the sass it changes from Terminal to Output and that's really annoying.

I don't know if the extension or VScode is causing this.

**Comment by glenn2223** [comment]
You'd need to change the [`liveSassCompile.settings.showOutputWindowOn
`](https://github.com/glenn2223/vscode-live-sass-compiler/blob/master/docs/settings.md#livesasscompilesettingsshowoutputwindowon) to `Error` or `None`. Preferably `Error` so it only steals focus when your SASS has an error

Hope this helps

**Comment by glenn2223** [comment]
Did that help at all @4e576rt8uh9ij9okp?

**Comment by glenn2223** [comment]
Closing as info required
