### ISSUE TITLE
Compile main .sass if any of the imported .sass documents are saved

### ISSUE THREAD

**Issue by TimurKr** [glenn2223/vscode-live-sass-compiler#227]
In my project structure I have `styles.sass` which is importing many other sass modules. Those sub-modules are only imported in the `styles.sass`, to there is no need for them to be compiled, but I would like to recompile the `style.sass` whenever any of the sub-modules is changed. Is that possible?

**Comment by glenn2223** [comment]
Yes, please refer to [liveSassCompile.settings.partialsList
](https://github.com/glenn2223/vscode-live-sass-compiler/blob/master/docs/settings.md#livesasscompilesettingspartialslist)

_This is based on the assumption that your partials don't start with a leading underscore `_`_

Hope this helps

**Comment by glenn2223** [comment]
Did this help @TimurKr?

**Comment by TimurKr** [comment]
Yes, worked perfectly. For anyone else doing this, files mentioned in `.settings.excludeList` will be ignored even if they are added in the `.settings.partialsList`.

**Comment by glenn2223** [comment]
> files mentioned in `.settings.excludeList` will be ignored even if they are added in the `.settings.partialsList`

Hmm, fair point. When I added this, `partialsList` wasn't a thing. Might have to think (and poll) about this one.

Regardless, glad it's working for you now 😁

**Comment by TimurKr** [comment]
I believe the functionality is great this way, I would simply add a comment about this in the docs. Thank you again
