### ISSUE TITLE
Keeps breaking every time I start a new project

### ISSUE THREAD

**Issue by Louistam888** [glenn2223/vscode-live-sass-compiler#228]
Is not compiling a css file at all. The past few times I got around this problem by uninstalling and reinstalling multiple times but this time it is not working all.

**Comment by glenn2223** [comment]
Can you follow the steps from the ['Why are my files not compiling?'](https://github.com/glenn2223/vscode-live-sass-compiler/blob/master/docs/faqs.md#why-are-my-files-not-compiling) section of the FAQ.

I'd also need:
- to see your file structure.
- is the extension showing in the bottom right of the window
- is there any output from the extension whatsoever

**Comment by glenn2223** [comment]
Any luck @Louistam888

**Comment by Louistam888** [comment]
> 

Working now, thanks

**Comment by glenn2223** [comment]
Glad you got it working
