### ISSUE TITLE
Compiling content: "/xxx" issue

### ISSUE THREAD

**Issue by primanegara** [glenn2223/vscode-live-sass-compiler#229]
![Screen Shot 2022-10-24 at 08 27 13](https://user-images.githubusercontent.com/17535883/197430103-dc58f4a5-6b91-457a-98f5-8c57bad81d15.png)
HI there, i got an issue about compiling property "content: " for an icon style.  
So for example: 
`.fa-test:before {
  content: "\f09a";
}`
and then the result (min.csss) compiled file be like this 
`.fa-test:before{content:""}`

Of course that is unidentified symbol.
Could you help me about this ?

**Comment by glenn2223** [comment]
Please refer to #39
