### ISSUE TITLE
Breaking: Can Live Server be disabled?

### ISSUE THREAD

**Issue by enoversum** [glenn2223/vscode-live-sass-compiler#23]
Hi @glenn2223 , I just switched from the legacy to your extension, and a general question came up: Is it possible to in some way disable the Live Server feature? I develop mostly WordPress themes, thus already have a local server running on my machine. Though I don't know if just _having_ the extension does any load on VS Code's end.

**Comment by glenn2223** [comment]
Hi @enoversum, this has definitely crossed my mind. There is no actual dependency on Live Server, so it could be removed. I was going to schedule this for the next major release. Just going to review the code and group any other "breaking changes" in with it

**Comment by enoversum** [comment]
Hey @glenn2223 , thanks for getting back so quickly! At least within the extension there seems to be no way to separate the two. As soon as I want to disable the Live Server extension, your Sass Compiler would also be disabled. Glad you're taking care of it! 
As a side question: Can I also use the include settings with wildcards? In my case, the source for SCSS files to be compiles is always '/wp-content/themes/THEMENAME/css/SOMENAME.scss', so something like 'wp-content/themes/' as a wildcard, so your extension only watches scss files in the 'themes' folder? The theme folder name at least varies, so a wildcard would be helpful. The documentation only uses direct files in the examples.

**Comment by glenn2223** [comment]
>thanks for getting back so quickly! At least within the extension there seems to be no way to separate the two. As soon as I want to disable the Live Server extension, your Sass Compiler would also be disabled. Glad you're taking care of it!

Yeah, it's been setup as a dependency when it was more of a package deal with ritwickdey's extension. This means VS Code thinks one can't survive without the other ☹️ 

>As a side question: Can I also use the include settings with wildcards?

The `includeFiles` setting does accept wildcards. 

So you can do `"wp-content/themes/**/css/*.scss"`

**Comment by enoversum** [comment]
@glenn2223 On any account - thank you so much. And I'll use the includeFiles settings as described. If I got it right from the other thread, that doesn't _ignore_ all the other files and folders, unless I set up `excludeFiles` rules?

**Comment by glenn2223** [comment]
That's right, as per #22 . Include settings do not ignore every other folders/files in the directory. This is purely down to the exclude settings. 

Any issues with speed should be addressed by increasing the exclude settings array 

----

There's a small fix coming soon but this doesn't address the whole issue it just *halves* the impact

A better fix will be coming in v5

**Comment by enoversum** [comment]
Thanks again, @glenn2223, for intense support here. I already set some exclude rules, and I think they cut out most stuff in the projects that are system files :-) . Absolutely no hurry here, just interested, is v5 around the corner? I'm happy with how it works now, so no rush from my side.

**Comment by glenn2223** [comment]
No worries, thank you for confirming my initial thoughts of removing the live sever dependency.

I'm afraid v5 isn't right around the corner. Doing a couple of things for v4.4 tonight then I'll shift focus to v5. I'm hoping the full v5 release will come in a few of weeks


I'll probably open a new branch for `v5-alpha` and implement this first change immediately. I'll also make sure it includes a `.vsix` file that you can drag straight into the `Extensions` tab on VS Code to install it. This has the added benefit of some alpha testing

**Comment by glenn2223** [comment]
Closing as change is accessibly from the [v5 tree](https://github.com/glenn2223/vscode-live-sass-compiler/tree/v5) by downloading and installing the `live-sass-5.0.0-alpha.#.vsix` file (where `#` is the current alpha revision)

---

**Still open for discussion until official v5 release - comment here for any issues, queries or concerns**

**Comment by Tealk** [comment]
If i try to disable Live Sass
![image](https://user-images.githubusercontent.com/12276250/108134256-2f02bf00-70b6-11eb-94a6-f3d8c4043061.png)

**Comment by glenn2223** [comment]
That's really strange. As you can see below, I can uninstall and just need to reload to remove it. Can you completely close and then reopen VS Code, see if it lets you then. Also, I assume you have uninstalled Ritwick Dey's Live Sass extension and you have no other extensions that depend on Live Server?

![Live Sass 5 installed & Live Server ready to be removed](https://user-images.githubusercontent.com/33450392/108134708-99176600-70ae-11eb-9a63-e500fe67bf29.png)

**Comment by Tealk** [comment]
Apparently the error only occurs when deactivating, I was able to uninstall it.

**Comment by glenn2223** [comment]
FYI: alpha-2 is available [here](https://github.com/glenn2223/vscode-live-sass-compiler/blob/ef03dbeea5c990326db0c5aac94bf34a43076c8d/live-sass-5.0.0-alpha.2.vsix)
