### ISSUE TITLE
Issue Report: SUMMARY HERE

### ISSUE THREAD

**Issue by ArtVanT** [glenn2223/vscode-live-sass-compiler#230]
[live-sass-compiler-doesn't-work.zip](https://github.com/glenn2223/vscode-live-sass-compiler/files/9879353/live-sass-compiler-doesn.t-work.zip)

**Comment by glenn2223** [comment]
Can I have details of your issue? Thanks

**Comment by ArtVanT** [comment]
Live SASS refuses to compile SCSS files in CSS. When I started a project everything was great, but in moment (in the middle of the work) it's just stopped to compile.

**Comment by glenn2223** [comment]
What's the output from the compiler?

**Comment by glenn2223** [comment]
I'm guessing
```
Compilation Error
Error: Undefined mixin.
   ╷
38 │                             @include greenarrow;
   │                             ^^^^^^^^^^^^^^^^^^^
   ╵
```

**Comment by ArtVanT** [comment]
I have a problem with main.scss, I didn't check any other files yet.

**Comment by glenn2223** [comment]
That's where the problem is

Here you're trying to use `greenarrow` but you haven'e defined it. That's why the compiler is outputting the warning I have copied in above. Define the mixin and the error will go away. Does that make sense?
```SASS
.btn-text1::after {
    @include greenarrow;
}
```
Your

**Comment by ArtVanT** [comment]
The problem is it doesn't compile in css, I'm trying to set style but it doesn't work

**Comment by ArtVanT** [comment]
And it's not compiling in CSS.

**Comment by ArtVanT** [comment]
It worked, I found in CSS. Fixed that mistake thank you.

**Comment by glenn2223** [comment]
No problem
