### ISSUE TITLE
Live sass compiler taking long time to compile

### ISSUE THREAD

**Issue by MatinsVeismans** [glenn2223/vscode-live-sass-compiler#233]
When I click on 'Watch sass' it takes very long time to fully compile to the scss file I waiting for minutes for it to compile and saying 'Watching...' . I have like around 160 lines in a single file and it takes very long to finish and while it is compiling the styles are also not working properly. I have i7 cpu, 16gb and nvme ssd and it is compiling very slow. What am I suppose to do? What is the problem?

![Screenshot 2022-10-29 125518](https://user-images.githubusercontent.com/108291939/198825231-eb1214ac-7208-4c57-a5fb-c3170432611a.jpg)

It show this for a very long time...

**Comment by glenn2223** [comment]
It's not compiling anything. If it finds something to compile them the output says it's generating a CSS file

Check out the [FAQ](https://github.com/glenn2223/vscode-live-sass-compiler/blob/master/docs/faqs.md). The migration guide and compilation issue answers should help

Let me know 😁

**Comment by glenn2223** [comment]
Did you resolve your issue @MatinsVeismans?

**Comment by MatinsVeismans** [comment]
Well, I have the same issue I did some configuration to `settings.json` here is how it looks like:
```
{
    "liveSassCompile.settings.formats": [
        {
            "format": "compressed",
            "extensionName": ".min.css"
        }
    ],
    "liveSassCompile.settings.autoprefix": [
        "defaults"
    ],
}
```
also I ran `liveSass.command.debugInclusion` and it showed:
Checking current file
```
c:\Users\myname\Documents\my_website\css\styles.scss
--------------------
File should get processed
If the file isn't being processed, run `liveSass.command.debugFileList`
--------------------
```
and when I click `Watch Sass` it is still stuck at watching and doesn't say success

also when I run `liveSass.command.debugFileList` it shows this:

```
Extension Info
--------------------
Current File
--------------------
c:\Users\myname\Documents\my_website\css\styles.scss
--------------------
Workspace Folders
--------------------
[0] my_website
c:\Users\myname\Documents\my_website
--------------------
Checking workspace folder 1 of 1
Path: c:\Users\myname\Documents\my_website
--------------------
--------------------
Current Include/Exclude Settings
--------------------
Include: [ NULL ]
Exclude: [ /**/node_modules/**, /.vscode/** ]
--------------------
Included SASS Files
--------------------
c:\Users\myname\Documents\my_website\css\styles.scss
c:\Users\myname\Documents\my_website01\temp\css\style.scss
--------------------
Included Partial SASS Files
--------------------
--------------------
Excluded SASS Files
--------------------
--------------------
```
Note: `myname` and `my_website` are just placeholders.

What does this output mean?  Is the configuration correct? Why is it still stuck at `Watching...` ? What am I suppose to do?

**Comment by glenn2223** [comment]
Do you get any output after saving the scss file?

Can I see your user settings? (Press <kbd>F1</kbd> type `user settings json` - as below - and click first option)

![image](https://user-images.githubusercontent.com/33450392/199284299-61e77329-e8ef-4e99-b60c-fbe2b4643ce4.png)

The only thing I can think of is that some setting somewhere is stopping compilation on watch (like `liveSassCompile.settings.compileOnWatch: false`)

**Comment by glenn2223** [comment]
Sorry, to answer your questions

>What does this output mean?

That the files under `Included SASS files` should be compiled, settings dependant

>Is the configuration correct?

Yes, based on what you've included

>Why is it still stuck at `Watching...`?

Possibly a setting issue, or an extension issue on your platform. What OS are you running?

**Comment by MatinsVeismans** [comment]
There are the answers:

> Do you get any output after saving the scss file?

When I press ctrl + s it says success and then again is watching the scss file. I mean I have autosave enabled in VS Code.

> Can I see your user settings?

Here I copied:
```

{
    "python.defaultInterpreterPath": "C:\\Users\\myname\\AppData\\Local\\Programs\\Python\\Python310\\python.exe",
    "tabnine.experimentalAutoImports": true,
    "code-runner.runInTerminal": true,
    "liveServer.settings.CustomBrowser": "chrome",
    "workbench.colorTheme": "GitHub Dark",
    "php.validate.executablePath": "",
    "liveServer.settings.donotShowInfoMsg": true,
    "files.autoSave": "afterDelay",
    "liveSassCompile.settings.formats": [
        {
            "format": "compressed",
            "extensionName": ".min.css"
        }
    ],
    "liveSassCompile.settings.autoprefix": [
        "defaults"
    ],
}
```
This is now the full JSON file...

> What OS are you running?

`Windows-10-10.0.19044-SP0`

**Comment by glenn2223** [comment]
Sorry, to be clear. When you save (Ctrl + S) it says it's generated the file, as below.

![image](https://user-images.githubusercontent.com/33450392/199301042-4b703385-0b01-4acf-9821-9eef04654aa9.png)

If so, how fast is that processing?

---

If those are your user settings then do you have a settings file in the project - as below?

![image](https://user-images.githubusercontent.com/33450392/199300665-3328d708-d941-4e16-b72d-d5a4fc1cc3f6.png)

---

So confused. The only reason it wouldn't save when you click watch sass is if the `liveSassCompile.settings.compileOnWatch` setting was false

**Comment by MatinsVeismans** [comment]
It does show 'generated'.
Yes I suppose this is how it is processing:

![Screenshot 2022-11-01 201751](https://user-images.githubusercontent.com/108291939/199308316-358c55d0-7d29-4b47-a1fe-397478628972.jpg)

Also the settings.json is file is located in: `C:\Users\myname\AppData\Roaming\Code\User` rather than in the project folder .

I tried to add and set `liveSassCompile.settings.compileOnWatch` to true but still same thing.

Do I need settings.json in the .vscode folder?

**Comment by glenn2223** [comment]
I'm also using windows. I also enabled autosave `afterDelay` and that caused no issue

> Do I need settings.json in the .vscode folder?

No, you can remove it

---

So I can debug this, can you set the output level to trace, clear the output window and then start watching. 

This will output a whole trace log. Can you past in in here for me to look through? Thanks

**Comment by MatinsVeismans** [comment]
How am I suppose to do that?

[exthost.log](https://github.com/glenn2223/vscode-live-sass-compiler/files/9918388/exthost.log)

Is this the correct file?

**Comment by MatinsVeismans** [comment]
So I executed `liveSass.command.showOutputOn.trace` and it showed this:

```
Command called: "liveSass.command.showOutputOn.trace"
--------------------
Command called: "liveSass.command.watchMySass"
--------------------
Starting to compile all files
--------------------
Changing status bar to: "Working on it..."
--------------------
Getting SASS files
Query pattern: undefined
Can be overwritten: true
--------------------
Checking folder 1 of 1
Folder: Unfinished projects
--------------------
No base folder override found. Keeping workspace folder
--------------------
Found 2 SASS files
--------------------
Compiling Sass/Scss Files: 
c:\Users\Matins Veismans\Documents\Unfinished projects\my_website01\css\styles.scss
c:\Users\Matins Veismans\Documents\Unfinished projects\my_website02\temp\css\style.scss
--------------------
Starting file 1 of 2
Path: c:\Users\Matins Veismans\Documents\Unfinished projects\my_website01\css\styles.scss
--------------------
Found the workspace folder
Workspace Name: Unfinished projects
--------------------
Starting format 1 of 1
Settings: {"format":"compressed","extensionName":".min.css"}
--------------------
Calculating file paths
Calculating the save paths for the css and map output files
Originating path: c:\Users\Matins Veismans\Documents\Unfinished projects\my_website01\css\styles.scss
--------------------
No workspace provided
Using originating path: c:\Users\Matins Veismans\Documents\Unfinished projects\my_website01\css\styles.scss
--------------------
Starting file 2 of 2
Path: c:\Users\Matins Veismans\Documents\Unfinished projects\my_website02\temp\css\style.scss
--------------------
Found the workspace folder
Workspace Name: Unfinished projects
--------------------
Starting format 1 of 1
Settings: {"format":"compressed","extensionName":".min.css"}
--------------------
Calculating file paths
Calculating the save paths for the css and map output files
Originating path: c:\Users\Matins Veismans\Documents\Unfinished projects\my_website02\temp\css\style.scss
--------------------
No workspace provided
Using originating path: c:\Users\Matins Veismans\Documents\Unfinished projects\my_website02\temp\css\style.scss
--------------------
Starting compilation
Starting compilation of file
Path: c:\Users\Matins Veismans\Documents\Unfinished projects\my_website01\css\styles.scss
--------------------
Autoprefixer isn't false, applying to file
Path: c:\Users\Matins Veismans\Documents\Unfinished projects\my_website01\css\styles.scss
--------------------
Preparing autoprefixer
--------------------
Starting autoprefixer
--------------------
Starting compilation
Starting compilation of file
Path: c:\Users\Matins Veismans\Documents\Unfinished projects\my_website02\temp\css\style.scss
--------------------
Autoprefixer isn't false, applying to file
Path: c:\Users\Matins Veismans\Documents\Unfinished projects\my_website02\temp\css\style.scss
--------------------
Preparing autoprefixer
--------------------
Starting autoprefixer
--------------------
Completed autoprefixer
--------------------
Completed autoprefixer
--------------------
Saving file
Saving a file to the system
Target: c:\Users\Matins Veismans\Documents\Unfinished projects\my_website01\css\styles.min.css.map
--------------------
Saving file
Saving a file to the system
Target: c:\Users\Matins Veismans\Documents\Unfinished projects\my_website01\css\styles.min.css
--------------------
Saving file
Saving a file to the system
Target: c:\Users\Matins Veismans\Documents\Unfinished projects\my_website02\temp\css\style.min.css.map
--------------------
Saving file
Saving a file to the system
Target: c:\Users\Matins Veismans\Documents\Unfinished projects\my_website02\temp\css\style.min.css
--------------------
Generated:
c:\Users\Matins Veismans\Documents\Unfinished projects\my_website02\temp\css\style.min.css.map
c:\Users\Matins Veismans\Documents\Unfinished projects\my_website02\temp\css\style.min.css
--------------------
Changing status bar to: Success
Registered timeout to switch state back
--------------------
Generated:
c:\Users\Matins Veismans\Documents\Unfinished projects\my_website01\css\styles.min.css.map
c:\Users\Matins Veismans\Documents\Unfinished projects\my_website01\css\styles.min.css
--------------------
Changing status bar to: Success
Registered timeout to switch state back
--------------------
Switching UI state
--------------------
Changing status bar to: Watching
--------------------
Watching...
--------------------
Firing timeout function to switch back
--------------------
Changing status bar to: Watching
--------------------
Firing timeout function to switch back
--------------------
Changing status bar to: Watching
--------------------
```
And showed this after I stopped watching:

```
Command called: "liveSass.command.donotWatchMySass"
--------------------
Switching UI state
--------------------
Changing status bar to: Not watching (or Watch SASS)
--------------------
Not Watching...
--------------------
```
I also tried `"liveSassCompile.settings.showOutputWindowOn ": "Trace"` , however it said said `Unknown Configuration Setting` . 

Is this the output showing any problems? Why the configuration setting was unknown? What does the output even mean?

**Comment by glenn2223** [comment]
> I also tried `"liveSassCompile.settings.showOutputWindowOn ": "Trace"` , however it said said `Unknown Configuration Setting`
>... Why the configuration setting was unknown? ...

Sorry, I put a space at the end of the command. `n ":` should be `n":`  
In full, and correct, `"liveSassCompile.settings.showOutputWindowOn": "Trace"`

>What does the output even mean?

The output is just for me to debug the issue.

>Is this the output showing any problems?

No, the output looks fine.

From the output you provided it says it has generated the file after starting to watch - as from these lines:
>```
> --------------------
> Generated:
> c:\Users\Matins Veismans\Documents\Unfinished projects\my_website01\css\styles.min.css.map
> c:\Users\Matins Veismans\Documents\Unfinished projects\my_website01\css\styles.min.css
> --------------------
>```

Has it started working now?

**Comment by MatinsVeismans** [comment]
Idk it is still watching but the css is working properly probably it was due to some wrong configuration settings. 

Is it suppose to say watching every time i click save? And why it doesn't say success after some time?

**Comment by glenn2223** [comment]
>Is it suppose to say watching every time i click save?

No, `Watching` only pops up once you start watching. Before that, it should show generated if the user settings say to compile on watch. Then, after each file save it will output further `Generated` messages

>And why it doesn't say success after some time?

The status bar changes to `Success` after successfully compiling any files

>And to answer the question I would say no...

The output you provided shows that SCSS files are being found, compiled and saved before "watching" begins.

The `Watching` and `Generated` messages are both set to output at the logging level `Information` so if you see one then you'd see the other.

The only possible way that I can see files not being compiled on "watch" is if the `compileOnWatch` setting is false.

Not sure where to go from here.

**Comment by glenn2223** [comment]
Can you create and share a small project that I can test?

**Comment by glenn2223** [comment]
Closing as info required

**Comment by MatinsVeismans** [comment]
Fine, try to compile this...
[test.zip](https://github.com/glenn2223/vscode-live-sass-compiler/files/10058466/test.zip)
