### ISSUE TITLE
Pseudo Classes and Elements are not compiling properly.

### ISSUE THREAD

**Issue by Rebbbellion** [glenn2223/vscode-live-sass-compiler#239]
Good afternoon, Glenn Marks! I found some issues in compiling of pseudo classes and pseudo elements. When I`m trying to add some pseudo class(or element) to element it compiles with space and browser is not reading it. Here are some screenshots. Sorry for my English. It might be not perfect, but I hope you`ve understood me.
![image](https://user-images.githubusercontent.com/111085729/201957783-4036bd49-ed94-4fd5-93ad-a4915fe8a496.png)
![image](https://user-images.githubusercontent.com/111085729/201958004-15a75f03-0740-43dc-a55b-68a0d8fab584.png)
![image](https://user-images.githubusercontent.com/111085729/201958089-adafd6e9-2195-4d95-9a05-567ef10fc5a9.png)
![image](https://user-images.githubusercontent.com/111085729/201958205-62ffc406-b40e-4f02-a790-b290460d3e8c.png)
![image](https://user-images.githubusercontent.com/111085729/201958429-3a110d89-9c0a-4c95-811e-5d4e08a17f18.png)
![image](https://user-images.githubusercontent.com/111085729/201958515-fd772dfe-7793-42a7-8131-648ab93f6277.png)

**Comment by glenn2223** [comment]
You need to prepend the `:hover` with an `&`, so it should be `&:hover`. This ties it to the preceding element (takes the space away).

**Comment by Rebbbellion** [comment]
Thanks! I`ve realized that I missed that important thing!

**Comment by glenn2223** [comment]
NP, glad you sorted it 😁
