### ISSUE TITLE
Question for the community - Is it working for everyone?

### ISSUE THREAD

**Issue by glenn2223** [glenn2223/vscode-live-sass-compiler#24]
Hi all,

Hope you're enjoying the extension so far. I have a concern and was hoping for some feedback.

The download to install ratio is wild compared to other extensions on the marketplace (I know it's early days but it rather ask now)

Is anyone having an issue with the extension not working/registering/loading on a specific OS?

**Straight to it:** I have concerns that it's not loading on OSX/Linux and my only testing platform is my own Windows 10 machine

**Comment by glenn2223** [comment]
Windows 10 - 64 bit

**Comment by glenn2223** [comment]
Windows 10 - 64 bit 👍

**Comment by gavin310** [comment]
macOS 11.1 installs just fine

**Comment by glenn2223** [comment]
Thanks @gavin310

Closing. OSX was my main concern. I trust now that if anything were to be wrong it would have resulted in a report here.

---

Still trying to get the CLI to run my test but I keep encountering different problems. A local test always works, but the downloading of VS Code v1.50 (CLI specific task) always returns some kind of error. Still investigating.
