### ISSUE TITLE
partials compiled despite settings.partialsList

### ISSUE THREAD

**Issue by none511** [glenn2223/vscode-live-sass-compiler#240]
hi all!

saving my "_variables.scss" file, the "main.scss" file (wich imports the partial) is correctly compiled to its "main.css" file, however a "_variables.css" is compiled as well, even though the 
/Users/ME/Library/Application Support/Code/User/settings.json says:
`
"liveSassCompile.settings.partialsList":[
    "/**/_*.s[ac]ss"
    ],	
`
am i doing something wrong?

(i'm on a mac with ventura 13.0.1, i see no .vscode in the project root)

thanx!

**Comment by glenn2223** [comment]
That all looks correct.

With the partial open can you run `liveSass.command.debugInclusion`. Save that output and then clear it.

After that, run `liveSass.command.debugFileList`. Again, include that output. Thanks

PS, that's the default setting so it doesn't actually need to be set in the JSON file 😁

**Comment by none511** [comment]
good morning glenn, thx for the extension and the reply!

actually looks like the "main.scss" file doesn't compile when saving the "_variabiles.scss", sorry, my bad!
anyway, i tried the procedure you told me, here's the first output:

```
Checking current file
/Applications/MAMP/htdocs/stefi/web/assets/css/commons/_variables.scss
--------------------
File should get processed
If the file isn't being processed, run `liveSass.command.debugFileList`
--------------------
```

and here's the second one:

```
Extension Info
--------------------
Current File
--------------------
/Applications/MAMP/htdocs/stefi/web/assets/css/commons/_variables.scss
--------------------
Workspace Folders
--------------------
[0] web
/Applications/MAMP/htdocs/stefi/web
--------------------
Checking workspace folder 1 of 1
Path: /Applications/MAMP/htdocs/stefi/web
--------------------
--------------------
Current Include/Exclude Settings
--------------------
Include: [ NULL ]
Exclude: [ /node_modules/**, /.vscode/** ]
--------------------
Included SASS Files
--------------------
/Applications/MAMP/htdocs/stefi/web/assets/css/main.scss
/Applications/MAMP/htdocs/stefi/web/assets/css/commons/_variables.scss
/Applications/MAMP/htdocs/stefi/web/assets/css/commons/_tools.scss
--------------------
Included Partial SASS Files
--------------------
--------------------
Excluded SASS Files
--------------------
--------------------
```

these are the basic settings:

```
"liveSassCompile.settings.formats": [
    {
        "format": "compressed",
        "extensionName": ".css",
        "savePath": "/assets/css"
    }
```

**Comment by glenn2223** [comment]
Thanks for the output. Again, all looks good.

What's the output when you save the partial, whilst the extension is watching?

**Comment by none511** [comment]
hell, i wasn't _watching_!

again, sorry! so, when saving the partial, the "main.css" is compiled as weel, just as i said at first, but the partial is compiled as well as the "_variables.css" file.

the output tells:

```
Change detected - 11/17/2022, 11:34:17 AM
_variables.scss
```

then, some compilation error ( due to missing files imported in the "main.scss" but not in "_variables.scss" ) and finally:

```
Generated:
/Applications/MAMP/htdocs/stefi/web/assets/css/main.css.map
/Applications/MAMP/htdocs/stefi/web/assets/css/main.css
```

the "main.css" looks fine, while obviosusly there are missing part in "_variables.css"..  so the problem is the first i asked about: partial files are compiled along with the main file.

**Comment by glenn2223** [comment]
Can you set the output level to `Trace`, as per the docs, save the partial file and then include the output here?

Can you also produce a minimal project example I can use for testing?

Thanks

**Comment by none511** [comment]
ok, now everything works fine, don't know if i found the problem, but here we go: found out i had the old extension by ritwick dey installed, it is marked as deprecated and i couldn't remove it:

<img width="703" alt="immagine" src="https://user-images.githubusercontent.com/42898837/202464856-0264b68a-bfda-4d2b-86b3-de64162f13fc.png">

i ended up removing the extension folder from `/Users/ME/.vscode/extensions/` , it does still appearing but now you're compiler is working like charm.
will investigate further about the problem with vscode.

sorry if i messed up and thank you very much for supporting me!

**Comment by glenn2223** [comment]
No problem, just glad your solution is working now. Let me know if you need anything else 😁
