### ISSUE TITLE
@run vs @import

### ISSUE THREAD

**Issue by sabrinaistheman** [glenn2223/vscode-live-sass-compiler#241]
Would it be possible to update this extension so that it accepts @run on the style.scss (whenever I use it for a variable.scss it breaks and I have to go back to @import for the whole file

**Comment by glenn2223** [comment]
Hey, there is no `@run`

![image](https://user-images.githubusercontent.com/33450392/205264522-f17d4b0a-5622-4aac-99e8-de03e5553717.png)


If you mean `@use` then it's implemented already. See https://sass-lang.com/documentation/at-rules/use#loading-members, where you'll see you need to use the namespace or declare the use statement as global.
