### ISSUE TITLE
Compiling issue

### ISSUE THREAD

**Issue by sougataos** [glenn2223/vscode-live-sass-compiler#242]
Hello
Today I have installed your extension 'live sass compiler' after watching a tutorial. after going through all steps found that something is missing at my version.
as per the youtube tutorial this 'compiler' supposed to add all the necessary css 3 code automatically to the main.css, even this seen on the youtube video too. but at my end this was not happened! I have uploaded the screenshot in the following link, where you can clearly seen the differences between compiled my version 'main.css' & tutorials 'main.css'. Here is the link >> https://ibb.co/wCVY1XF

Please let me know what is wrong here, which is not happening automatically.

look forward
Sougata
sougata@os.me

**Comment by glenn2223** [comment]
Hey @sougataos, can you check out the conversation over at #165

---

Closing as duplicate

**Comment by sougataos** [comment]
ok sure
