### ISSUE TITLE
Negative excluded files

### ISSUE THREAD

**Issue by MarcoLProto** [glenn2223/vscode-live-sass-compiler#249]
I was using the old version and just moved to the new one on the second laptop and i can see when i copy my settings.json i get an error that i am missing "/" on the start.

The original that worked:

```
    "liveSassCompile.settings.excludeList": [
      
      "**/node_modules/**",
      ".vscode/**",
      "**/*[!(styles)]/**"
    ],
```

I added "/" on the start but it seems that its compiling all of the files instead of ignoring all files that are not in styles. Does this functionality with *[!(folderName)] still works or am i writing a new one bad? I was using 3.0.0 version before

**Comment by glenn2223** [comment]
I have normalised the settings, though (in this case) the leading slash is stripped away later on. It has not affected how the settings/extension works.

---

To the matter at hand. I've checked and it's your glob pattern.

The extension uses `picomatch` so I put together a quick sample - available at [RunKit](https://runkit.com/embed/la7vmx7dd74y). The page outputs two regexes from its console - the first is yours and the second is my version of what I think you want. If you test them at www.regex101.com - using the sample list below - you will see that your pattern is matching the correct (but not what you want) lines, whereas mine is matching to your expectations.

```
/myapp/config/production.sass
/myapp/styles/services/utils.sass
/myapp/styles/controllers/health.sass
/myapp/styles/user.module.sass
/styles/utils.sass
/styles/timezone.sass
```

Please confirm this resolves your issue. Thanks

---

_**Some extra info:**_ your pattern is saying that "any of the folders must not be `styles`". So `/styles/file.scss` will be excluded, but `/folder/styles/file.scss` and `/styles/folder/file.scss` will not

**Comment by MarcoLProto** [comment]
Hi Glenn sorry for the late reply, i still didn't test this one out i am on holiday vacation for the new year. I will check it when i return, i did take a look at your reply and i can see that you are using "(**/)(?<!**/styles/**)*.sass'" but i get an error if i don't use "/" on the start so i am forced to use "/**" that is the only difference that does not work from the old example i had, could you write to me the full example of how it should look in the settings json of my vs code please? Thank you

**Comment by MarcoLProto** [comment]
Sorry again, just did a quick test it works this is the example i used: "'/(**/)(?<!**/styles/**)*.sass'". Thank you!
