### ISSUE TITLE
Possible to not have the Output panel open every time I save?

### ISSUE THREAD

**Issue by gavin310** [glenn2223/vscode-live-sass-compiler#25]
In the old Live SASS Compiler extension, when I would save my SASS file it would render to CSS and the only visual indication was the green "Success" message would show briefly. After installing this version, every time I save my SASS file the Output panel pops up and I have to close it. Is there a way to prevent the Output panel from opening every time I save my file?

**Comment by enoversum** [comment]
@gavin310 Know exactly what you mean. Best would be an option to only show it on error detection. You could disable it completely by setting `liveSassCompile.settings.showOutputWindow` to false, see https://github.com/glenn2223/vscode-live-sass-compiler/blob/master/docs/settings.md - but that would probably disable messages on detected errors as well, right, @glenn2223 ?

**Comment by gavin310** [comment]
Thanks for the tip @enoversum ! You're right that when this setting is `false`, when there's an error the output window won't show. I tried clicking on the red "Error" text, but that doesn't show the output window either. Unfortunately I'm not talented enough that I don't need error messages, so it would be great if the output window could only show when it needs to (on errors). Or, just having the output window show when you click on the red "Error" text could work too.

**Comment by glenn2223** [comment]
Hey @gavin310, thanks for contributing to making this extension even better!!

>You could disable it completely by setting `liveSassCompile.settings.showOutputWindow` to false

@enoversum is right, setting this to `false` will hide the output all the time (including on error), but the info is still logged and can be accessed 

You can open the output:
1. With the `liveSassCompile.command.openOutputWindow` command (`F1` then type some of the above or `Live Sass: Open Live Sass Output Window`)
2. Clicking the error warning icons at the bottom far left, then choose the `Output` tab and change the drop down to `Live Sass`

---

>I tried clicking on the red "Error" text, but that doesn't show the output window either.

This should definitely be a feature. Clicking on the `Success` or `Error` should open the output window. Will add this plus fix another for v4.4.0 which I'll try to get on tonight

***Note***
https://github.com/glenn2223/vscode-live-sass-compiler/blob/2a6a0ffdd7cf893b156ebeddbe466965c89cf211/src/StatusbarUi.ts#L70-L74

---

I think I need to readdress the outputting in the extension.

I will open a new issue with my initial thoughts and assign it the v5 milestone

**Comment by enoversum** [comment]
@glenn2223 Make sure you still get some free time, with all the effort you put into this beautiful extension :) . As for the feature, yeah, that would be perfect. 

@gavin310 If you are looking for a quick solution, possibly for other panel message as well, you could try this extension: https://marketplace.visualstudio.com/items?itemName=sirmspencer.vscode-autohide

**Comment by gavin310** [comment]
That's awesome @glenn2223 , that's for working on it so quickly! Just being able to click on the Success/Error caption to bring up the output would be pretty cool.

@enoversum Thanks for that tip!

**Comment by glenn2223** [comment]
v4.4.0 will be up shortly

Closing

**Comment by glenn2223** [comment]
Any input on #26 would be appreciated 😄

**Comment by gavin310** [comment]
> Any input on #26 would be appreciated 😄

It's working great! I had a small issue at the beginning where the red "Error" text was going away after only about a second, but after completely closing and reopening VSCode it's working better and gives me enough time to click the message.

The whole process and experience with the extension is so much more seamless and unobtrusive, I love it :)

**Comment by enoversum** [comment]
> Any input on #26 would be appreciated 😄

I can only second @gavin310 here - it's now very fluid, and lovely to have that input window out of the way. No problems whatsoever. Even with the extension I mentioned above, the output window would still pop up and then disappear after typing (that's how the extension works). But this is now a lot better for the compiler.

**Comment by glenn2223** [comment]
Thanks for the input on this new feature. Glad you like it 😄

#26 is actually a different issue talking about an overhaul to the output window

**Comment by gavin310** [comment]
> Thanks for the input on this new feature. Glad you like it 😄
> 
> #26 is actually a different issue talking about an overhaul to the output window

Oh, I didn't realize the output window was overhauled. I hadn't been paying attention to it. I'll check it out today

**Comment by glenn2223** [comment]
> Oh, I didn't realize the output window was overhauled. I hadn't been paying attention to it. I'll check it out today

No, sorry if I wasn't clear. It's just an issue raised to discuss the possibility of overhauling the log. Making sure it's considered a useful/viable change before I commit to it for v5.
