### ISSUE TITLE
Compilation Error Error: Invalid argument(s): Unsupported output style "expended".

### ISSUE THREAD

**Issue by Kostja-Dzu** [glenn2223/vscode-live-sass-compiler#250]
Hi
I try to use it in Vs code for the first time, and get it all the time

Compilation Error
Error: Invalid argument(s): Unsupported output style "expended".
Any solution?

**Comment by glenn2223** [comment]
> Any solution?

Spell it correctly 😜 😂 - OJ 

The setting expects `collapsed` or `expanded`

**Comment by Kostja-Dzu** [comment]
Excuse me, as I wrote I try to use it for the first time, and follow a guide on Youtube step by step.
On Youtube plugin is start working, is creating new files, but I get error, and no new files created
Can you please explain what  I am doing wrong?

**Comment by glenn2223** [comment]
> Excuse me, as I wrote I try to use it for the first time, ...

No problem, only joking around - got too much Christmas joy 😂

> ... and follow a guide on Youtube step by step. On Youtube plugin is start working, is creating new files, but I get error, and no new files created Can you please explain what I am doing wrong?

Depends on the error. What's the issue?

**Comment by Kostja-Dzu** [comment]
I dont know what is the problem. 
Plugin does not work
Instead to convert scss file to css I just get such error:
--------------------
Compilation Error
Error: Invalid argument(s): Unsupported output style "expended".

**Comment by glenn2223** [comment]
You need to go into the file: `/.vscode/settings.json` and correct the typo to `expanded`

**Comment by Kostja-Dzu** [comment]
Oh sorry.. :) 
Happy New Year!

**Comment by Kostja-Dzu** [comment]
And lust last question
In settings.json I specified to save new created .css file in css folder. But it is still saving the .css file in scss folder near scss file, as it was in beginning..
         "format": "expanded",
         "autoprefix": "last 5 vesions",
         "extensions": ".css",
         "savepass": "css"
Can you tell me where is the problem?

**Comment by glenn2223** [comment]
> "savepass": "css"

It's `savePath`. You can find all the names over at the [settings docs](https://github.com/glenn2223/vscode-live-sass-compiler/blob/master/docs/settings.md)

**Comment by Kostja-Dzu** [comment]
Hello
Can you pls tell me how I can set up saving pass?
I have:  folder/scss/.. 
I want that .css file was generated in the css-folder:   folder/css/..
In settings I specified:
"liveSassCompile.settings.formats": [
      {
         "format": "expanded",
         "extensionName": ".css",
         "savePath": "~/../css"
      }
   ],  
But every time it saves the .css file in the random place, Some time it saves in folder/scss/..
 what shall I write to save .css file in: folder/css/..  ??

**Comment by glenn2223** [comment]
Depends if you want to keep the folder structure. If you want everything in `folder/css/` (no subfolders) then that's the value you should use. If you want to keep the folder structure then you'd need the use `savePathReplacementPairs` from the [settings](https://github.com/glenn2223/vscode-live-sass-compiler/blob/master/docs/settings.md#save-path-notes)

The tilde `~` means relative to the file that's being saved so it will always go up a directory and save in a folder called `css`

**Comment by Kostja-Dzu** [comment]
I have the .scss file in: folder/subfolder scss/.. 
It saves now .css file in the same folder: folder/subfolder scss/.. 
I need to save  it in: folder/subfolder css/..  no subfolder scss/

**Comment by glenn2223** [comment]
Try this:

``` JSON
{
    "liveSassCompile.settings.formats": [
        {
            "format": "expanded",
            "extensionName": ".css",
            "savePathReplacementPairs": {
                "/scss/": "/css/"
            }
        }
    ]
}
```

**Comment by Kostja-Dzu** [comment]
It shows some error..
Ok, thank you anyway
