### ISSUE TITLE
Console popup

### ISSUE THREAD

**Issue by homezonebenny** [glenn2223/vscode-live-sass-compiler#252]
Since one of the new updates of this plugins OR VScode (I guess) everytime you save the file the console log opens and shows itself.
You close the console window (CTRL J) and after you changed something and you saved it, console window pop up again.

Is there any solution for that?

**Comment by glenn2223** [comment]
Please refer to [liveSassCompile.settings.showOutputWindowOn](https://github.com/glenn2223/vscode-live-sass-compiler/blob/master/docs/settings.md#livesasscompilesettingsshowoutputwindowon). Thanks
