### ISSUE TITLE
option to only include a list of directories to watch

### ISSUE THREAD

**Issue by deckberg-quantumdigital** [glenn2223/vscode-live-sass-compiler#256]
is there an option to only include a list of directories to watch?  I have a big project and it takes quite a while for it to iterate through the directory structure when I know there are only two directories that I need to watch.

**Comment by glenn2223** [comment]
Hey! Take a look at the [liveSassCompile.settings.forceBaseDirectory](https://github.com/glenn2223/vscode-live-sass-compiler/blob/master/docs/settings.md#livesasscompilesettingsforcebasedirectory_) setting. Hopefully it will help

**Comment by glenn2223** [comment]
Any luck @deckberg-quantumdigital?

**Comment by glenn2223** [comment]
Closing as confirmation required
