### ISSUE TITLE
compilator error with a @for loop

### ISSUE THREAD

**Issue by KacperPiotrowski** [glenn2223/vscode-live-sass-compiler#257]
hi :)
I wanted created this:
@for $hue from 0 to 360 {
    $var: "color-#{$hue}";
    #{$var}: hsl($hue, 100%, 50%);
}

I got only
Compilation Error
Error: expected "{".
  ╷
3 │     #{$var}: hsl($hue, 100%, 50%);
  │                                  ^
  ╵

But on website https://beautifytools.com/scss-compiler.php eveything works properly,

**Comment by glenn2223** [comment]
It seems you don't have it inside a class. Trying to add random properties, not in a class, is invalid CSS. The compiler recognises this and throws an error.

**THIS DOESN'T WORK**
```SCSS
.test {

}

@for $hue from 0 to 360 {
    $var: "color-#{$hue}";
    #{$var}: hsl($hue, 100%, 50%);
}
```

**THIS DOES WORK**
```SCSS
.test {

    @for $hue from 0 to 360 {
        $var: "color-#{$hue}";
        #{$var}: hsl($hue, 100%, 50%);
    }
}
```

**Comment by glenn2223** [comment]
Closing as my tests seem conclusive the above is the issue
