### ISSUE TITLE
Error: Invalid UTF-8.

### ISSUE THREAD

**Issue by matthmu** [glenn2223/vscode-live-sass-compiler#258]
```
Compilation Error
Error: Invalid UTF-8.
  ╷
1 │ --------------------
```

Everything works perfectly on Windows. But when I open the same working folder in VSCode on a MacOS system, I get this message every time I save and compile SCSS. I can't find any errors at all, the files are all correctly created in UTF-8 format and no special characters or umlauts were used.

The error only exists when I work on my network drive (Ubuntu Homeserver) via SMB integration. If I copy the same directory to my Mac, then there is no error. So the error clearly only occurs when I'm working on my network drive. It can't be because of the directory name either, since it doesn't contain spaces, special characters or umlauts.

**Comment by glenn2223** [comment]
I think the issue is around the network access rather than anything else. However, could you try the alpha (linked further down)? It uses a more recent version of SASS that has a new charset feature (info below)

``` TS
export interface Options<sync extends 'sync' | 'async'> {
  /* If `true`, the compiler may prepend `@charset "UTF-8";` or U+FEFF
   * (byte-order marker) if it outputs non-ASCII CSS.
   * ... REMOVED FOR BREVITY
   * @defaultValue `true`
   */
  charset?: boolean;
}
```

[live-sass-5.5.2-alpha.3.zip](https://github.com/glenn2223/vscode-live-sass-compiler/files/10400812/live-sass-5.5.2-alpha.3.zip) (link taken from https://github.com/glenn2223/vscode-live-sass-compiler/issues/253#issuecomment-1380148084 )

**Comment by matthmu** [comment]
Hey Glenn, thank you for answer. I tested v5.5.2-alpha.3 and the problem is still the same. I can't find any logs of this error, I just saw the lines:

`Compilation Error
Error: Invalid UTF-8.
  ╷
1 │ --------------------`

The strange thing is that the files are compiled anyway, but the error message still appears.

**Comment by glenn2223** [comment]
Maybe two things to try 

1) Can you use sass directly and see if you get the same error through their CLI?  
First, run `npm install -g sass`  
Then, run `sass path/input.scss path/output.css` (more options in [docs](https://sass-lang.com/documentation/cli/dart-sass))

2) Is the issue still persisting if you change to an SSH connection with VS Code. I made a similar suggestion over at https://github.com/glenn2223/vscode-live-sass-compiler/discussions/254 - where they too had issues (albeit different ones) when compiling over a network

**Comment by matthmu** [comment]
Thank you for you support - I'm in the process of trying to find the cause of the error. I suspect it's something to do with my Ubuntu web server. When I copy the files to my Synology NAS and compile it over it, everything works fine.

I'll report as soon as I know more.

**Comment by matthmu** [comment]
So, I have now tried it via SMB, NFS and AFP file service, the error is still the same. The strange thing is that the error only comes when I save a file within an import function.

**Example:**

```
/web.scss
/imports/_addons.scss
```

**Example of my web.scss:**

```
@import 'imports/addons';
```

So, if I save the web.scss, everything works fine. But as soon as I would save the addons.scss, the error comes. The more files I edit and save, the more errors the console throws.

_(I've already tried to force UTF-8 in the files via @charset, but that doesn't change anything either...)_

I am absolutely at a loss. It works perfectly on a Windows system, but I have the error on my Mac. Do you have any other idea what it could be?

**Comment by glenn2223** [comment]
The only thing I can think of is that the main file isn't loaded and accessible to VS Code. If both files are open at the same time, do you still get the error?

**Comment by matthmu** [comment]
The error was probably due to the shadow files, which are automatically created by MacOS. Since I deleted and disabled these, the error has disappeared. So the problem was my environment and not your fault. Nevertheless, thank you very much for the nice support.
