### ISSUE TITLE
Breaking: Changes to Output Window

### ISSUE THREAD

**Issue by glenn2223** [glenn2223/vscode-live-sass-compiler#26]
**Nothing here is set in stone, tagged with `help wanted` to get extra user input**

**Please keep comments related to this issue. Want something else adding/sorting? Please open a new issue**

---

### To do list

- [x] Confirm implementation
- [x] Apply confirmed implementation
- [x] Documentation changes
- [x] Review current logging levels & increase trace/debug logging

---

The current state of the output window is not optimal. Highlighted from #25 

**Issue**
When the `showOuputWindow` setting is set to `false` the output isn't optimised for errors. Plus some errors aren't being shown (again, with the above setup)

**Resolution**
See [this comment](https://github.com/glenn2223/vscode-live-sass-compiler/issues/26#issuecomment-794020359)
<details>
<summary>Old/outdated resolution</summary>

- When the above setting is false the output only saves errors rather than the current full log.
- All ***errors*** during compilation will also force the output to open, regardless of settings

**When `false`, what exactly is going to be saved/shown?**
Type | Saved | Shown
---|---|---
General error | ✔️ | ✔️ 
`@error` | ✔️  | ✔️ 
`@warn` | ✔️  | ❌ 
`@debug` | ✔️  | ❌ 
Autoprefixer warnings | ✔️  | ❌ 
Successful compilation | ❌   | ❌ 
Start/Stop watching | ❌ | ❌ 
Files found/compiling | ❌ | ❌ 

</details>

Extension level errors will still show a pop out. Which you can still report using the `liveSass.command.reportIssue` command

---

This change also requires some document changed

**Comment by glenn2223** [comment]
## Update + More feedback required

I'm considering 1 of 2 further updates/changes

1. Change name to `showAdvancedOutputOnSave` and default to `false`
2. Change current `showOutputWindow` default to `false` and add a new setting (that ties to the above). Something like `outputWindowDetail` which can either be `errors` or (`debug`/`simple`) default to `errors`

**Comment by zigojacko** [comment]
@glenn2223 as per [our conversation at my post](https://github.com/ritwickdey/vscode-live-sass-compiler/issues/460) in the original build, I'd like to see something like the below in the Watch Output.

----------------------------------
Change detected - 01/03/2021 @ 17:21
_header.scss
----------------------------------

Something like this and how you suggested yes.

**Comment by glenn2223** [comment]
**Had an epiphany** - A simple but effective solution

We change the name of the option to `showOuputWindowOn`. This then follows suit with traditional logging values so; `Trace`, `Debug`, `Information`, `Warning` and `Error`. I don't think critical will ever be applicable because the only critical error is an unexpected issue with the extension, which I catch in the `ErrorLogger`. The default will be `Warning`.

This means that the types of messages (the table I used above) will work closer to the below. Where information is Saved & shown based => type.
Type | Show on 👇 or greater
---|---
General error | `Error`
`@error` | `Error`
`@warn` | `warning`
`@debug` | `Debug`
Autoprefixer warnings | `Warning`
Successful compilation | `Trace`
Start/Stop watching | `Trace`
Files found/compiling | `Trace`

Please be aware that `@error` is the only one that is currently supported. However, `@debug` and `@warn` should work soon(ish)

---

Comments are still welcome as this is still undecided and I've not had any feedback yet. Please read and comment 😁

**Comment by glenn2223** [comment]
Closed with v5.0.0-alpha.5 release
