### ISSUE TITLE
Error when setting region in autoprefixer configuration

### ISSUE THREAD

**Issue by KenyaMasuko** [glenn2223/vscode-live-sass-compiler#264]
# summary
`"liveSassCompile.settings.autoprefix": ["> 5% in US"]` 
in setting.json results in error 
`Message: Unknown region name 'US'.`

# other info
- Live Sass Compiller (version: 6.0.0)
- VSCode (version: 1.75.0)

(I am not fluent in English, so the information provided here may not be sufficient🙏)

**Comment by glenn2223** [comment]
I'm not able to replicate this issue. As you can see below, I have tried multiple times

![image](https://user-images.githubusercontent.com/33450392/217580542-c0187b65-339d-4eb0-bfe5-e0e80619c0e8.png)

- Does it happen on every file?
    - If not, can I have the problem file?
- Does having the setting as `true` with `> 5% in US` in a [config file](https://github.com/browserslist/browserslist#config-file) solve the issue?
- Can you provide the trace output log?

**Comment by KenyaMasuko** [comment]
I am very sorry for the delay in replying!

> Does it happen on every file?

Yes, every files.

> Does having the setting as true with > 5% in US in a [config file](https://github.com/browserslist/browserslist#config-file) solve the issue?

I am using Live Sass Compiler as VSCode extension, where should I place package.json file? Currently I only describe the settings of this extension(Live Sass Compiler) in setting.json.

> Can you provide the trace output log?

This is the trace output log!

![image](https://user-images.githubusercontent.com/85816730/218723763-255daf1d-c4a1-4fc8-8594-e7ad87c543ef.png)

**Comment by glenn2223** [comment]
When I use a fake region, my output is different (as below). Can you confirm you're using my version of the extension and not Ritwick's?

![image](https://user-images.githubusercontent.com/33450392/218735902-cad55c01-5a63-44e1-aba4-44b12cd9efbb.png)

If you don't have a `package.json` file then create a [`.browserslistrc`](https://github.com/browserslist/browserslist#browserslistrc) file in the root of your workspace

**Comment by glenn2223** [comment]
Also, just spotted this:

>"A quick way to test your query is to do `npx browserslist '> 0.3%, not dead'` in your terminal.`"

Does putting `npx browserslist '> 5% in US'` into your terminal product an output like that below?

![image](https://user-images.githubusercontent.com/33450392/218737853-d7c3126a-fe53-4f93-be2c-7167802850c8.png)

**Comment by KenyaMasuko** [comment]
> フェイクエリアでは、出力が異なっています（以下のように） あなたが使用している拡張機能は、Ritwickのバージョンではなく、私のバージョンを使用していることを確認できますか？**彼のバージョンはまだインストールされていないこと**。

はい、あなたのバージョンを使っています。i これは正しいですか？
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/85816730/219951585-642b5e43-3181-4e77-8e23-7966432d42b8.png">

>If you don't have a package.json file then create a [.browserslistrc](https://github.com/browserslist/browserslist#browserslistrc) file in the root of your workspace

I made`.browserslistrc` file, and I put `npx browserslist '> 5% in US'` into  my terminal.
<img width="471" alt="image" src="https://user-images.githubusercontent.com/85816730/219951851-eae7fbb1-275d-4fec-a9a1-47a03f230fda.png">

But I could not solve the problem...
I will try again to review my settings.
Thanks for your help!

**Comment by FoxBJK** [comment]
Nope, still broken:
`
"liveSassCompile.settings.autoprefix": [
	"last 3 versions",
	">= 0.5% in US",
	"not dead"
]
`
It's just the "US" string and it's just this plugin. Never had the other one installed.

**Comment by FoxBJK** [comment]
Yes, it's the same error no matter what region:

> Autoprefix error. Your changes have not been saved
> Message: Unknown region name `CA`.

For what it's worth, I'm running VSCodium, not VSCode
