### ISSUE TITLE
Compilation Error :  Can't find stylesheet to import

### ISSUE THREAD

**Issue by Alberl** [glenn2223/vscode-live-sass-compiler#265]
C:\demo\\_sass\main.scss  code has  : 
` @import "./thirdparty/bulma.sass";`

Workspace       is C:\demo
the right path  is  C:\demo\thirdparty\bulma.sass
but error path  is  C:\demo\\_sass\thirdparty\bulma.sass
so, file not found

**Comment by glenn2223** [comment]
it should be `../` to get the parent directory, `./` means the current directory 😁

**Comment by Alberl** [comment]
Thanks!
