### ISSUE TITLE
Live Sass Compiler: Unhandled error on v.6.0.1

### ISSUE THREAD

**Issue by Warface** [glenn2223/vscode-live-sass-compiler#267]
Yesterday on version 6.0.0., everything was working fine but this morning with the new v.6.0.1, I have this error while trying to run watch

Live Sass Compiler: Unhandled error while compiling all files. Error message: Please install picomatch: "npm i picomatch" to use glob matching.

**Comment by glenn2223** [comment]
Bear with me, while I apply a fix. I was concerned it would do this but all my tests passed without issue.

**Comment by Warface** [comment]
No problem! I was wondering if it was on my side or maybe a quick fix on yours. Thanks for the quick reply

**Comment by glenn2223** [comment]
Does this version work? [live-sass-6.0.2.zip](https://github.com/glenn2223/vscode-live-sass-compiler/files/10698761/live-sass-6.0.2.zip)

I'm trying to update a VS code install (which is weird because it should auto-update) so I can test it on another RDP-connected PC

**Comment by robzor** [comment]
I'm also having the same issue fwiw!

**Comment by glenn2223** [comment]
Thanks, pushing a release now

**Comment by glenn2223** [comment]
Just had the "Success!" email from MS, should be live now

**Comment by robzor** [comment]
Thanks!
