### ISSUE TITLE
How to set the output area not to be displayed automatically?

### ISSUE THREAD

**Issue by Alberl** [glenn2223/vscode-live-sass-compiler#269]
![1](https://user-images.githubusercontent.com/25943436/218309840-e8b7fd0f-862b-4903-b706-05d7142eb077.png)

If change the code many times ,  it will pop up many times, disturb me see the code area.
I can see the process from red circle area in the image, so i don't want the output area displayed automatically, can I set the config?

**Comment by glenn2223** [comment]
You can change it from the [showOutputWindowOn](https://github.com/glenn2223/vscode-live-sass-compiler/blob/master/docs/settings.md#livesasscompilesettingsshowoutputwindowon) setting. Hope this helps

**Comment by Alberl** [comment]
Thanks, the plug-in is very powerful！
