### ISSUE TITLE
Sass Compiler has quit working.

### ISSUE THREAD

**Issue by Tigerlady** [glenn2223/vscode-live-sass-compiler#271]
I have been using this for quite a while, but recently it hasn't been compiling the sass files. 

In the workspace file, I have this.  I put Trace in there to see the output of what is happening.  As you will see, I have a list of folders I want to be excluded and the path I want to be included. I have pasted the trace below.   I don't know how to fix this, but I really need this to compile for me today if possible.  Thank you.

**Workspace Code**
```JS
{
	"folders": [
		{
			"path": "."
		}
	],
	"settings": {
		"liveSassCompile.settings.generateMap": false,
        "liveSassCompile.settings.showOutputWindowOn": "Trace",
        "liveSassCompile.settings.formats":[
            {
                "format": "compressed",
                "extensionName": ".min.css",
                "savePath": "/themes/MEX/css"
            }
        ],
        "liveSassCompile.settings.excludeList": [
            "/node_modules/**",
            "/.vscode/**",
            "/admin/**",
            "/config/**",
            "/core/**",
            "/modules/**",
            "/plugins/**",
            "/resource_bundles/**"
        ],
        "liveSassCompile.settings.includeItems": [
            "/themes/MEX/scss/**.scss"
        ]
	}
	
}
```
I am only putting the last portion of the trace as it is too long for here.  

**Trace Output**
```
   - Base path: /Volumes/External-Hard-Dive/Websites-External/Mexicali-Chrome - Dev
   - Rela path: node_modules/node-sass/test/fixtures/watcher/sibling/partials/.__three.scss
Path: /Volumes/External-Hard-Dive/Websites-External/Mexicali-Chrome - Dev/node_modules/node-sass/test/fixtures/watcher/sibling/partials/_three.scss
  isMatch: false
   - Base path: /Volumes/External-Hard-Dive/Websites-External/Mexicali-Chrome - Dev
   - Rela path: node_modules/node-sass/test/fixtures/watcher/sibling/partials/_three.scss
--------------------
File not found, must be excluded
--------------------
File excluded
The file has not been compiled as it's excluded by user settings
Path: /Volumes/External-Hard-Dive/Websites-External/Mexicali-Chrome - Dev/themes/MEX/scss/site/site.scss
--------------------
VS Code event: "onDidSaveTextDocument"
--------------------
Found the workspace folder
Workspace Name: Mexicali-Chrome - Dev
--------------------
```

**Comment by glenn2223** [comment]
Your `includeItems` glob is wrong. It should be `themes/MEX/scss/**/*.scss`

Not working:
![image](https://user-images.githubusercontent.com/33450392/219104673-e35066c8-1bc2-44f9-b1a2-49d90e37257d.png)

Working:
![image](https://user-images.githubusercontent.com/33450392/219104924-9243b1b1-6136-4233-a95c-8c2f9290911b.png)

---

Hope this helps. Closing but continue to comment/reopen if there's further issues

**Comment by Tigerlady** [comment]
You can keep it closed just wanted to say thank you.  I can't believe I missed that.

**Comment by glenn2223** [comment]
No problem, it's easily missed, glad it sorted your issue 😁
