### ISSUE TITLE
NewCompiler: Source maps broken

### ISSUE THREAD

**Issue by florianPopulaer** [glenn2223/vscode-live-sass-compiler#276]
I enabled the new compiler: "liveSassCompile.settings.useNewCompiler" : true

Now source maps are broken. The browser only shows the css file and no line number, instead of the corresponding scss file including the line number. 

old complier: _layout.scss:17 (that is the correct scss partial, with line number)
new compiler: backend.css:1 (that is the main, combined file)

**Comment by glenn2223** [comment]
I have identified the issue. Can you confirm the below package is also working for you?

[live-sass-6.0.3-beta.1.zip](https://github.com/glenn2223/vscode-live-sass-compiler/files/10823677/live-sass-6.0.3-beta.1.zip)

**Comment by florianPopulaer** [comment]
Yes, it is working correctly now. That was fast 😊.

Thanks for the great support/tool!

**Comment by glenn2223** [comment]
Glad it's working! Will publish a patch soon
