### ISSUE TITLE
How to run it in the background?

### ISSUE THREAD

**Issue by anddns** [glenn2223/vscode-live-sass-compiler#278]
It works wonderfully! Congratulations to everyone involved in this great project. 

But I would like to know if there is a way to run it silently in the background because the terminal keeps jumping to the foreground, and that's very distracting.

**Comment by glenn2223** [comment]
You'll want to look at the [liveSassCompile.settings.showOutputWindowOn](https://github.com/glenn2223/vscode-live-sass-compiler/blob/master/docs/settings.md#livesasscompilesettingsshowoutputwindowon) setting - using this you can customise when the window shows

---

Closing, but please continue to comment if this isn't what you're referring to
