### ISSUE TITLE
Not compiling when directory is on external volume (SSD)

### ISSUE THREAD

**Issue by miguelsanto** [glenn2223/vscode-live-sass-compiler#280]
It took me hours to figure what was happening, but it seems the new version does not compile when working from an external volume. I'm on a mac and the volume is a SSD, not sure if it happens with any sort of external storage.

The exact error is:
  ╷
1 │ --------------------
Compilation Error
Error: Invalid UTF-8.

Moving the directory to internal storage solved this.

**Comment by glenn2223** [comment]
Someone else has reported a similar issue. It was an issue with shadow files I believe

https://github.com/glenn2223/vscode-live-sass-compiler/issues/258#issuecomment-1422160720

---

Closing as duplicate. However, please feel free to reopen/comment if there's any further issues
