### ISSUE TITLE
brackets

### ISSUE THREAD

**Issue by KrutoyVovka** [glenn2223/vscode-live-sass-compiler#286]
when inserting attributes with empty parameters into a .scss document, I want an empty line between { }
for example, instead of
.wrapper {}
get
.wrapper {

}

**Comment by glenn2223** [comment]
This is outside the scope of this project. It's more of a wrapper around the sass/dart-sass package.

If compressed doesn't work for you then you would probably want some form of CSS linter to watch and style it after the file is changed/created.

---

Closing as out of scope. However, continue to comment if there's anything else you think I can help you with
