### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by salmanrazak** [glenn2223/vscode-live-sass-compiler#290]
- Issue Type: `Performance`
- Extension Name: `live-sass`
- Extension Version: `6.0.4`
- OS Version: `Windows_NT x64 10.0.22621`
- VS Code version: `1.77.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///c%3A/Users/razak/AppData/Local/Temp/glenn2223.live-sass-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by glenn2223** [comment]
Hi @salmanrazak,

Can you please provide the file that VS Code has specified an re-open

**Comment by salmanrazak** [comment]
Hay,

My apologies for late reply.
Actually, I remove vscode completely and re-install it. It worked ok with me since then.
I will share again if that error occur again.
