### ISSUE TITLE
 Change filename when compiling from SCSS to CSS

### ISSUE THREAD

**Issue by tobipch** [glenn2223/vscode-live-sass-compiler#293]
Hey,

Can we change the name of the compiled CSS file?
We checked the settings but couldn't find anything, maybe it's possible by changing the "savePath" setting?

**_Example_**
scss/base.scss -> css/custom.css

Thanks.

**Comment by glenn2223** [comment]
Hey @tobipch! It's not actually an option to change the output filename. As the extension is designed to potentially compile hundreds of files, having a fixed output name could result in disaster.

If you're only compiling for a single output file, then the SASS CLI may be better. If you want to continue with this extension, you would have to (in the case of your example) have a `custom.scss` file. You can then add `base.scss` to your `partialsList` to trigger the compilation of `custom.scss => custom.css` (or, much easier 😜, rename `base.scss` to `custom.scss`; if you can)

**Comment by tobipch** [comment]
Thanks for the quick and competent answer. 🙏
