### ISSUE TITLE
Version info confusing

### ISSUE THREAD

**Issue by cfcoder** [glenn2223/vscode-live-sass-compiler#294]
In my Extension list I notice discrepancies in what version I have of your wonderful live compiler of SASS.  By the top title it shows mine as v5.5.1 which is old. Then further down it shows VSCode Marketplace v6.0.5.  The More Info box shows last updated 4/9/2023 which is very recent.

Confusing....

![Snag_7c31d0c](https://github.com/glenn2223/vscode-live-sass-compiler/assets/4595721/1d211651-cca6-4a0b-8e28-506860a67aa2)

**Comment by glenn2223** [comment]
What version of Vs code are you running?

**Comment by cfcoder** [comment]
Hi Glen

I am using version 1.70.0

Bruce

**Comment by glenn2223** [comment]
From [v6.0](https://github.com/glenn2223/vscode-live-sass-compiler/releases/tag/v6.0.0) the extension requires VS Code version 1.74 and later

**Comment by cfcoder** [comment]
That resolved the issue. I am puzzled why VSC did not alert me nor auto-update about VSC version being old. There was/is no Help menu item to Check for Updates either. But I'll need to address that somewhere else unless you know the answer.

**Comment by glenn2223** [comment]
Glad you got it sorted 😁
