### ISSUE TITLE
How can I make it so that when I'm in 'watching', a folder is created in the root directory called 'css', and the 2 files 'main' and 'main.map' are inside that folder?

### ISSUE THREAD

**Issue by instak1ll** [glenn2223/vscode-live-sass-compiler#299]
![Captura de pantalla 2023-06-27 194753](https://github.com/glenn2223/vscode-live-sass-compiler/assets/63525176/c2086aeb-fe6e-42fc-9c72-eb17e6e795f7)
![Captura de pantalla 2023-06-27 194755](https://github.com/glenn2223/vscode-live-sass-compiler/assets/63525176/44bf7a3c-af15-4bb8-bc49-a79ab5b5ce52)

**Comment by glenn2223** [comment]
Glad you found a solution 😁
