### ISSUE TITLE
Breaking: Consistency across all settings

### ISSUE THREAD

**Issue by glenn2223** [glenn2223/vscode-live-sass-compiler#30]
**Nothing here is set in stone. Tagged with `help wanted` so I can get users thoughts and input**

**Please keep comments related to this issue. Want something else adding/sorting? Please open a new issue**

---

Bought to light in #22. The new `forceBaseDirectory` setting is inconsistent with other settings in the extension. Upon reviewing the setting I think it would be handy to force consistency across all settings.

**Issue**
- New setting causing confusion as it conflicts with other settings in the extension  
  - forceBaseDirectory = `"path/to/folder/"`  
  - Others = `"/path/to/folder"`
- Other setting could have better pattern management for:
  - Consistency 
  - Help keep the programme running at it's optimal

**Resolution**
All setting that relate to paths will have the same pattern:
- A leading slash
- No ending slash

The `includeFiles` setting, which relates to files, will have the following restrictions:
- A leading slash
- Must end in `.sass` or `.scss`

---

Documentation changes are required

<details>
<summary>Error detection change</summary>

```TS
try{ if (!fs.statSync(baseDirectory).isDirectory()) { /*err not folder*/ } } catch { /* err doesn't exist*/ }
```

</details>

---

**Edit:** Updated to reflect changes across the settings as a whole (not just the new one in v4.4)

**Comment by glenn2223** [comment]
Should I change all patterns so they must start with a slash but not end with one?

**Comment by coderars** [comment]
> Should I change all patterns so they must start with a slash but not end with one?

That would be the best (my vote).

**Comment by glenn2223** [comment]
Closing as change is accessibly from the [v5 tree](https://github.com/glenn2223/vscode-live-sass-compiler/tree/v5) by downloading and installing the `live-sass-5.0.0-alpha.#.vsix` file (where `#` is the current alpha revision)

---

**Still open for discussion until official v5 release - comment here for any issues, queries or concerns**

**Comment by glenn2223** [comment]
FYI: alpha-2 is available [here](https://github.com/glenn2223/vscode-live-sass-compiler/blob/ef03dbeea5c990326db0c5aac94bf34a43076c8d/live-sass-5.0.0-alpha.2.vsix)

**Comment by glenn2223** [comment]
Exclude setting hasn't had pattern matching applied

**Comment by glenn2223** [comment]
Fixed in rc2
