### ISSUE TITLE
It can convert, but the converted .min.css does'nt work.

### ISSUE THREAD

**Issue by will-mar** [glenn2223/vscode-live-sass-compiler#300]
Type: <b>Bug</b>

Greetings! I've started with HTML&CSS since a month ago or less. I managed to work with SASS through Live Sass Compiler. 

I generated a .css file via a .scss file through the command "Watch Sass", and then I "attached" that .css (or .min.css) file in my file.html. (link ref href="")

HOWEVER, the .css or .min.css generated can't apply the CSS rules to my file.html. 

In order to fix it, I've modified some .json files according to some YT guidelines. I've also asked to an acquitance of mine, who is an HTML&CSS expert, through Discord videocall to solve this problem, but he can't fix anything. Thus, I've resetted all the .json file to their original version. I've tried everything in this pasted two days, but I can't come out of this! Any suggestion?

Extension version: 6.0.5
VS Code version: Code 1.79.2 (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:57:04.379Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 3 3200U with Radeon Vega Mobile Gfx   (4 x 2595)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|5.94GB (1.10GB free)|
|Process Argv|--crash-reporter-id 5a384450-e9b9-4033-a999-d8380cac8e44|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30776702
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30610679
2e4cg342:30602488
pyind779:30671433
89544117:30613380
vscrp:30673768
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
pythongtdpath:30769146
i26e3531:30780429
pythonnosmt12:30779714
pythonidxpt:30772539
pythonnocebcf:30776496

```

</details>

**Comment by glenn2223** [comment]
Sorry, this is not a compiler issue. Seems like a local issue to me. See example.

Working local example: [Issue 300 Example.zip](https://github.com/glenn2223/vscode-live-sass-compiler/files/11931687/Issue.300.zip)

However, I'm happy to help when I get some spare time. Do you have a github repository you can share?

----

Do you have `rel="stylesheet"` on your `<link href="..." />`?

**Comment by will-mar** [comment]
https://github.com/will-mar?tab=repositories

There's a link of my training project. The .css file mapped by LSC can't apply .css rule to the .html file.

**Comment by glenn2223** [comment]
https://github.com/will-mar/More-Buttons---.css-file-illegible-when-converted-from-.scss-by-LSC/blob/dc2ff5f57fa6e114aebce870f92b997acb53971b/more-buttons.html#L5

Should be `rel` not `ref`

**Comment by glenn2223** [comment]
Hope this sorts your issue. 

As it's not an issue with the extension I have closed this isuue

**Comment by will-mar** [comment]
It doesn't work anyway.

**Comment by glenn2223** [comment]
I closed this as it's user error and not an issue with the extension.

As I said, please change your HTML as stated in an earlier comment. Below is a screenshot of the working and NOT working code (see the underline which is marking the error). As to correcting your settings, you can open the User JSON file (by pressing <kbd>F1</kbd> and typing "User JSON"). Then delete everything that's "messed up"

**Not working**
![image](https://github.com/glenn2223/vscode-live-sass-compiler/assets/33450392/572f8f59-9593-4c45-b771-9db10e92db94)

**Working**
![image](https://github.com/glenn2223/vscode-live-sass-compiler/assets/33450392/c37cb263-8828-4e8a-8d38-b9216c3eb2f0)
