### ISSUE TITLE
Problem with errors only in some files

### ISSUE THREAD

**Issue by minjooo96** [glenn2223/vscode-live-sass-compiler#305]
Hello!
I'm using the live class compiler really well. Thank you for making it.
First of all, please note that I used a translator because I don't speak English!

My problem is that when I compile the scss file, I get an error with the phrase below.

**Compilation Error
Error: NoSuchMethodError: method not found: 'line' on null**

The project is using 12 scss files, but only 2 of them get this error. I didn't use anything special. What's wrong with this?

I will copy the error scss file and leave a code pen!
https://codepen.io/minjooo/pen/yLQREpr

Please check as soon as possible (Crying)!

**Comment by glenn2223** [comment]
Sorry you're having an issue with the extension.

I am able to replicate this on the extensions public release. However, when trying to debug it on my windows PC, there are no errors! It seems that the package created with the GitHub action, which is run on Ubuntu, is causing some weirdness in the final package

This will take me a little time to check up on, so I won't be able to resolve it immediately. Sorry!

Does using an earlier version of the extension resolve the issue temporarily, until I find a fix? If so, what version worked?

**Comment by minjooo96** [comment]
I got an error when I used the latest version, and now I downgrade to 6.0.5 and there is no issue!
There was no issue until 2 days ago, and there was an issue from the day I left the post (Yesterday).

Still, I'm glad it worked out well to be back in the previous version. I didn't think of it. Thank you!

**Comment by glenn2223** [comment]
Sorry for the delay.

I think it's related to line 1045:
```SASS
                    +& {
                        border-left: 1px solid #ddd;
                    }
```

As it should output:
```
--------------------
Change detected - 8/8/2023, 12:00:51 AM
problem.scss
--------------------
Warning:
The selector "+ .comm_tab.ftm .tab_item" is invalid CSS.
This will be an error in Dart Sass 2.0.0.

More info: https://sass-lang.com/d/bogus-combinators
     ╷
1045 |                    +& {
     |                   ^..^
     ╵
file:///c:/YOUR_PATH/YOUR_FILE.scss:1045:20
THIS IS DEPRECATED AND WILL BE REMOVED IN SASS 2.0
--------------------
```

The SASS version used (or the compilation process) must have caused an error which was causing some weirdness. I have updated SASS in the `sass-update-from-1.62` branch and I packaged up - using WSL Ubuntu - the below VSIX file (that's ZIP'd). You should be able to drag into your extensions tab and it will work - as mine did

[live-sass-6.0.6.zip](https://github.com/glenn2223/vscode-live-sass-compiler/files/12285702/live-sass-6.0.6.zip)

**Comment by minjooo96** [comment]
I've used two methods, but I'm not sure if I applied it well.

1. Ctrl + Shift + P  > Install from VSIX > select file > vscode reload
-> The watch scss button does not appear.

2. Drag onto the Extension tab to install
-> Same error occurred

Did I do anything wrong?
Do I have to apply the vsix file after correcting the "+ &" part in question?

![image](https://github.com/glenn2223/vscode-live-sass-compiler/assets/47136112/a0e71131-8237-48fc-bded-1551226ae245)

**Comment by glenn2223** [comment]
After you drag the VSIX file over, it should prompt you to reload the window and just work

It may be worth uninstalling the current one before dragging on the new one

>First of all, thanks to your information on the error part, I corrected that part and used it as the latest version. :-)

No problem, glad to help 😁

----

If it's still no good then v6.1 should be out soon and ew can give that a whirl

**Comment by minjooo96** [comment]
As you said, I was able to use sass after deleting the extension and dragging it! Thank you.
But the error about '+ &' is still the same 😥
First of all, I'll try to use '&+&'!

**Comment by glenn2223** [comment]
So v6.1.0 is out!

However, you'll need to rename your `rem()` function as it now collides with the CSS equivalent (of the same name) which calculates remainders <sup>[ref](https://developer.mozilla.org/en-US/docs/Web/CSS/rem)</sup>

---

If the official release closes your issue then let me know or close this issue yourself 😁

**Comment by minjooo96** [comment]
I updated to v6.1.0,
Modifying 'rem()' to 'remp()' completed.

However, the same error still appears...
Did I do anything wrong? (Crying)

Thank you for always responding!

![image](https://github.com/glenn2223/vscode-live-sass-compiler/assets/47136112/45429397-2d6c-4543-b2e1-b7655581dfc7)

**Comment by glenn2223** [comment]
Sorry for the delay been trying to figure out what's going on here.

While I check why the error isn't outputting correctly I though I should explain why the `+ & { ... }` is returning an error.

When you have an ampersand it doesn't include the chain up to that point too it's saying that the chain should be ONLY included at the ampersand. That means you're trying to generate CSS that looks like:
```CSS
+ .comm_radio {
  margin-left: min(1.5625vw, calc(30 * 1px));
}
/* AND */
+ .comm_tab.ftm .tab_item {
  border-left: 1px solid #ddd;
}
```

Which is invalid, because you can't have a CSS rule that starts with a [combinator](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Selectors#combinators_and_separators).

To fix it, you ned to write `& + & { ... }`. There are two places that you have done `+ &` so you will ned to apply it at both.

**Comment by minjooo96** [comment]
I understand what you mean!
I shared this with my team members and told them to use CSS rules well in the future.

Thank you for leaving a good answer to my question!
I will close this issue :-)
