### ISSUE TITLE
[Suggestion] Play sound on error

### ISSUE THREAD

**Issue by javl** [glenn2223/vscode-live-sass-compiler#311]
Most of the time my .scss files compile without any problem, but every now and then I make a typo and it does fail, resulting in me spending way too much time trying to figure out why stuff isn't working, only to realize the sass didn't compile.

My VS Code window is pretty much always split into the VS Code editor with one or more terminals below, meaning there isn't really a good (visual) place to put the output of the Live Sass Compiler. So I was wondering; do you think it's (technically) possible to have VS Code play a simple, optional _*ding*_ sound when an error occurs during compiling? That would really help to signal an error has occurred (at which point I can open up the logs) without 'wasting' screen space on something you don't need to see 99% of the time.

**Comment by glenn2223** [comment]
Sorry for the delay. It _may_ be possible to play a sound with another dependency in the project - I'd have to take a proper look around. Don't suppose you have any extensions that do this already I could look at? I'm also not sure how this would work with remote environments - like SSH connected sessions - I'd have to check on this too

---

I personally have `showOutputWindowOn` set to `"Warning"` thenclose the window. Then when the next error/issue occurs it throws the output window in my face 😁

**Comment by javl** [comment]
Ah wait! The window would open as soon as I run the addon, but I didn't realize I can just set 'ShowOutputWindowOn' to something less verbose (like 'warning') and use it like you described. 

That might actually be enough, I'll give it a go after the weekend. Thanks!

**Comment by javl** [comment]
Pff, who needs sound? Settings `ShowutputWindowOn` to `warning` works great. Thanks for the suggestion!
