### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by HSD33V** [glenn2223/vscode-live-sass-compiler#314]
- Issue Type: `Performance`
- Extension Name: `live-sass`
- Extension Version: `6.1.0`
- OS Version: `Darwin x64 17.7.0`
- VS Code version: `1.81.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///var/folders/tz/07lf4m4x1mq72d854mlwpldm0000gp/T/glenn2223.live-sass-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by glenn2223** [comment]
Sorry to hear it's causing you CPU issues, can you send me the file that VS Code is referencing?

**Comment by glenn2223** [comment]
Closing as info required
