### ISSUE TITLE
Feature Request: A new setting similar to "forceBaseDirectory" which tells it to only compile in current folder and sub folders

### ISSUE THREAD

**Issue by gavin310** [glenn2223/vscode-live-sass-compiler#32]
Sorry if this already exists, but from what I've read about `forceBaseDirectory`, there isn't a setting to only render CSS in the current SASS file's directory and subdirectories. For example if your SASS file is located in `files/assets/css/` then it would only render SASS/SCSS files in `files/assets/css/`, `files/assets/css/bootstrap/`, etc., but would not render any CSS in let's say `files/plugins/`. Maybe to do this you would just set `forceBaseDirectory` to `current` or something?

It might complicate things too much, but it would also be cool to have one setting to only render in the current directory and no subdirectories, and another setting to render in the current directory and include subfolders. Like `current` and `currentTree` or something.

I usually like to keep my CSS in `/css/` and my SASS in `/css/src/`, but I can see how that won't work for this extension's plugin-and-play functionality without compiling all CSS in the entire workspace, so I think just being able to only render in the current directory would be just fine.

**Comment by glenn2223** [comment]
Hi @gavin310 

The idea of `forceBaseDirectory` was to speed up processing on larger workspaces that have hundreds of non-scss files located in different subdirectories. before implementing the new setting it would waste a lot of time (and resources) searching these (essentially useless) directories. The `forceBaseDirectory` setting allows you to skip these unnecessary directories by saying that all of the files you care about processing are under the directory path `files/`. The blue files on the left are those that will be processed with the above setting.

What I think you need is the below settings (I have described each)
```JS
{
    // Don't forget your other settings

    // I don't care about anything outside of `/files/`, so save me some time and RESOURCES!!
    //   - Note: if this is the root of your workspace, the setting can be omitted
    "liveSassCompile.settings.forceBaseDirectory": "files/"

    // I only want to process scss/sass files that are under a `/src/` folder
    //   - You can extend `/src/` to `/css/src/` if this is a guaranteed structure
    "liveSassCompile.settings.includeItems": [ "**/src/[^_]*.s[a|c]ss" ],

    // I don't card about files in `files/dont-need-this/` so exclude it 
    // and all of its subdirectories and subfiles
    //   - Note: I dont start with `files/` as this is set by `forceBaseDirectory`
    "liveSassCompile.settings.excludeList": [ "dont-need-this/**" ],
}
```

---

These setting are based on the below file structure (based somewhat on your example above). Note that I've not set up an exclude for `dont-need-this/`, for brevity. Also, note that I have started the pattern with `/files/` to replicate what `forceBaseDirectory` does behind the scenes.

![Example file structure, as per the below list, it highlights that any scss files that are under a src folder](https://user-images.githubusercontent.com/33450392/106883770-57fb7b00-66d8-11eb-93fa-f819c7cd204b.png)


**To replicate the above image:** open [globster](https://globster.xyz/), click the folder structure on the left and paste the below into the text field that shows up. You can then test with my pattern or your own
```
/files/assets/css/main.css
/files/assets/css/src/main.scss
/files/assets/css/bootstrap/css/src/_partial1.scss
/files/assets/css/bootstrap/css/src/main.scss
/files/assets/css/bootstrap/css/main.scss
/files/plugins/css/main.css
/files/plugins/css/src/main.scss
/files/dont-need-this/css/src/main.scss
/files/dont-need-this/css/main.css
```

---

I hope this all makes sense, please let me know if I can help any more

**Comment by glenn2223** [comment]
Hey @gavin310,

Did this help or was I of the mark with my reply?

**Comment by gavin310** [comment]
@glenn2223 Ahh sorry! I thought I replied to this! Yes, that helped a lot. It's all clear now. Mostly I need to remember that it's designed for single projects and not necessarily a 3rd party plugin folder that contains 20+ individual projects.

**Comment by glenn2223** [comment]
Thanks for clarifying, closing.

After re-reading: yeah it seems like sorting #17 will help even further with the issues you're having

**Comment by gusbemacbe** [comment]
Good evening, @glenn2223 !

My configuration:

```json
{
	"liveSassCompile.settings.autoprefix": null,
	"liveSassCompile.settings.compileOnWatch": true,
	"liveSassCompile.settings.excludeList": 
	[
		"/**/node_modules/**",
		"/.vscode/**"
	],
	"liveSassCompile.settings.forceBaseDirectory": "/assets",
	"liveSassCompile.settings.formats": 
	[
		{
			"format": "expanded",
			"extensionName": ".css",
			"savePath": "/assets/css",
		},
		{
			"format": "expanded",
			"extensionName": ".css",
			"savePath": "/assets/css/tokens",
		},
		{
			"format": "expanded",
			"extensionName": ".css",
			"savePath": "/assets/css/utils",
		}
	],
	"liveSassCompile.settings.generateMap": false,
	"liveSassCompile.settings.showOutputWindowOn": "None",
	"liveSassCompile.settings.useNewCompiler": true
}
```

The screenshot:

![image](https://github.com/glenn2223/vscode-live-sass-compiler/assets/2257024/e6fdbd2f-4db9-4309-848a-ae99f2fee6a8)

I would like to output the files to:

- `assets/css/tokens/art-deco.css`
- `assets/css/tokens/colours.css`
- `assets/css/utils/fonts.css`
- `assets/css/utils/media-queries.css`
- `assets/css/utils/reboot.css`
- `assets/css/utils/reset.css`

Is it possible?

**Comment by glenn2223** [comment]
It is!

Take a look at `savePathReplacementPairs` [here](https://github.com/glenn2223/vscode-live-sass-compiler/blob/master/docs/settings.md#livesasscompilesettingsformats). It takes the save path and will replace a `key` with the `value` from the pair. 

You basically want:  
_I have included the slashes to ensure it only matches folders_

```js
{
	//... other settings
	"liveSassCompile.settings.formats": 
	[
		{
			"format": "expanded",
			"extensionName": ".css",
                        "savePathReplacementPairs": {
                            "/scss/": "/css/"
                        }
		}
	],
	//... other settings
}
```

---

Just an FYI, if you have a question/issue that's not directly associated with an issue then you can always open a anew one (it stops the OP from getting emails too)

**Comment by gusbemacbe** [comment]
I am pleased to report that the procedure worked, @glenn2223. Thank you so much for that!
