### ISSUE TITLE
How to import all files in current directory?

### ISSUE THREAD

**Issue by mumus** [glenn2223/vscode-live-sass-compiler#321]
Hello. I have a problem. I need to import all scss files from current directory where current scss file is located

Sass Live Compiler throws error like this:

Compilation Error
Can't find stylesheet to import.

All these imports throws errors:

`@import "./*";
@import "*";
@import "./*.scss";
@import "*.scss"`

**Comment by glenn2223** [comment]
You can't import all files, you need to specify. 

If you only wanted to import one file in all your other files, you'd need a file that `@forward`s all your specific files. You can then just `@use` that one file

### Example

**./foundation/_index.scss**
```
@forward './variables'; // this one declares $classColor
@forward './functions';
@forward './thing-three';
```

**./main.scss**
```
@use 'foundation/index'; 
// above could be just 'foundation' or 'foundation/_index' 
// just remember to adjust your namespace

.class {
    color: index.$classColor;
}
```

Refs:  
- https://sass-lang.com/documentation/at-rules/use/
- https://sass-lang.com/documentation/at-rules/forward/

---

Closing as not an issue with the extension. Though, please continue to comment if you need anything else (though I'd recommend checking out the links above
