### ISSUE TITLE
Formatter make my code go wrong

### ISSUE THREAD

**Issue by NhanVo95** [glenn2223/vscode-live-sass-compiler#324]
The formatter changes the indent of code, and it wrong. But it changes the first, not the second.
![image](https://github.com/glenn2223/vscode-live-sass-compiler/assets/47500159/61412dd7-d33c-4515-b64c-521080c34b5a)

**Comment by glenn2223** [comment]
Hi @NhanVo95, the extension doesn't have a built-in formatted. Follow the below steps and you can find the formatted and report the problem there

1. Open the command pallet and type `Format Document With...`  
![image](https://github.com/glenn2223/vscode-live-sass-compiler/assets/33450392/f86b058c-f9c1-4b90-baf3-6838830a95f8)
2. Click `Configure Default Formatter...`  
![image](https://github.com/glenn2223/vscode-live-sass-compiler/assets/33450392/40c09fac-70e9-49c1-8d92-ed430c7616dd)


---
Closing as not an issue with the extension
