### ISSUE TITLE
compile only the open file

### ISSUE THREAD

**Issue by Tealk** [glenn2223/vscode-live-sass-compiler#33]
Hello,

is it possible that only the opened file is compiled?

I write character sheets in a fork of [this](https://github.com/Roll20/roll20-character-sheets) repo and whenever I run the command `liveSass.command.oneTimeCompileSass` it wants to compile all files in the repo.

**Comment by Tealk** [comment]
Ok I found it myself, who can read is clearly at an advantage.
Sorry
`liveSass.command.compileCurrentSass | Compile Current Sass File`

**Comment by glenn2223** [comment]
Glad you found the setting 👍. I knew it would be a handy addition

**Comment by Tealk** [comment]
Yes I have only switched to your fork and before there was not this option.

thank you for your work that you continue to development.
