### ISSUE TITLE
Enconding escaped characters for ISO88591 or UTF-8

### ISSUE THREAD

**Issue by feperrella** [glenn2223/vscode-live-sass-compiler#335]
Hi, 

I did not want to encode:
`content: "\201C";`

however does not matter if I use UTF-8 or ISO8859-1 the content changes to 
`content: "“"; `
or respectively to
`content:"â";`

Is there a way to retain the escaped content in the final file like in the original?
`content: "\201C";`

**Comment by glenn2223** [comment]
Please refer to #39 

---

Closing as duplicate
