### ISSUE TITLE
How to map css output into the same hierarchy as the source SCSS file hierarchy

### ISSUE THREAD

**Issue by cfcoder** [glenn2223/vscode-live-sass-compiler#338]
I have a SCSS directory of files and folders something like this:
```
/scss
  /modules
    _core.scss
    _variables.scss
  /pages
    /projects
      /overview_styles.scss
      /costs_styles.scss

```
I'd like to compile the css output into the same hierarchy:
```
/css
  /pages
    /projects
      /overview _styles.css
      /costs_styles.css

```
Is this possible?  I need this as I want to load different chunks of css for each page type.  Currently I see it compile both overview_styles.css and costs_styles.css into /css, basically removing the hierarchy of the output.

**Comment by glenn2223** [comment]
You need to use the `savePathReplacementPairs` option in the `formats` setting - as such:

```JS
{
"liveSassCompile.settings.formats": [
    {
        "format": "expanded",
        "extensionName": ".css",
        "savePathReplacementPairs": {
            "/scss/": "/css/"
        }
    }
]
}
```

This will replace the `/scss/` part of the file path with`/css/`

PS: you need to do this in your settings by pressing <kbd>F1</kbd>, then type "Settings JSON" and finally choose the appropriate option

---

There's a video explaining the setting (sorry for the dodgy audio quality 😁) https://youtu.be/9J__JAgQbS0?t=308

---

Closing as this will resolve the issue. Feel free to comment again if you need further assistance on this

**Comment by cfcoder** [comment]
This didn't really fix my issue. It was already (by default) placing the output css into the directory specified in the formats "savePath" directive. I'm wanting the scss files saved in sub-directories under scss to be mapped to their equivalent sub-directory location in the savePath directory. So is the example I provided originally, the two scss files (overview_styles.scss and costs_styles.scss) would compile into the same subdirectory under /css/ projects directory as overview_styles.css and costs_styles.css. Does this require a "savePathReplacementPairs" directive for each and every folder?

**Comment by cfcoder** [comment]
It appears I have to comment out the "savePath" directive. When I did that, things started compiling css files and placing them into where I map them. it also appears I have to have a directive for each layer of the hierarchy to direct where to place the files in a directory hierarchy. Correct me if any of this is not necessary.

**Comment by glenn2223** [comment]
Sorry there seems to be some misunderstanding/miscommunication, I'll explain further.

So, the format setting I'm recommending will search the current path and replace any "key" with its corresponding "value". This means, in you're case, it's going to search the first path, identify the section in bold, replace it and save to the new (second) path - thus maintaining your folder structure.
- _**/scss/**_ pages/projects/overview_styles.scss
- _**/css/**_ pages/projects/overview_styles.scss

---

>It appears I have to comment out the "savePath" directive.

That's right you don't need the save path component
