### ISSUE TITLE
FEATURE REQUEST: Minify/Uglify output css

### ISSUE THREAD

**Issue by siMobin** [glenn2223/vscode-live-sass-compiler#342]
I propose adding a CSS minification/uglification feature to the Live Sass Compiler extension. This addition would optimize the generated CSS output by removing unnecessary characters, whitespace, leading to smaller file sizes and improved website performance.

**Benefits:**

- **Enhanced Performance:** Minified/uglified CSS files load faster, benefiting website or application performance.
- **Streamlined Workflow:** Integrating this feature within the extension eliminates the need for external tools or additional build steps.

**Potential Implementation:**

Adding a simple setting within the extension to ***enable/disable*** CSS **minification/uglification** would suffice. This setting could reside within the extension panel in VS Code, providing an option for developers to optimize their CSS output.

**Comment by glenn2223** [comment]
Sorry, how is this different from changing the [liveSassCompile.settings.formats[].format](https://github.com/glenn2223/vscode-live-sass-compiler/blob/master/docs/settings.md#livesasscompilesettingsformats) setting to `compressed`?

**Comment by glenn2223** [comment]
Tweaking the output CSS would be out of scope for the project. I know you used it as an example... but, your output is technically larger with no change to the layout 😜

But seriously, the issue with doing this sort of manipulation is that it could take out something important and change the expected layout.

However it's something you could do, of your own accord. If you were to watch for the output CSS, you can run it through some postcss stuff and perform the kind of manipulation you require

---

But, as I said, it's out of scope so I will close this issue
