### ISSUE TITLE
Erro to compiling .min.css with @import 

### ISSUE THREAD

**Issue by pmoreno-rodriguez** [glenn2223/vscode-live-sass-compiler#345]
When compiling a scss file that has @import 'path/to-file.css', for example, the resulting .min.css file removes the space between @import and the quoted string that calls the imported file, so the .min.css file does not import styles and.

Input example:
`@import '../css/fontawesome-all.min.css';`

Output example:
`@import'../css/fontawesome-all.min.css';`

**Comment by glenn2223** [comment]
Sorry for the delay. New baby is taking up all my spare time 😴

A space isn't actually required. What error is the browser outputting when it tries to load the CSS file?

If you think the CSS styles should be being compiled into your outputted file, you need to remove the `.css` suffix <sup>[[ref](https://sass-lang.com/documentation/at-rules/import/#importing-css)]</sup>

**Comment by pmoreno-rodriguez** [comment]
Hi @glenn2223. Thanks for your answer. 

It must have been some specific error, because now I am not able to reproduce it, it does not matter if there are spaces or not after @import, which works fine with main.min.css

Everything works as expected.
Thank you very much for your work.

**Comment by pmoreno-rodriguez** [comment]
Hi @glenn2223. Thanks for your answer.

It must have been some specific error, because now I am not able to reproduce it, it does not matter if there are spaces or not after @import, which works fine with main.min.css

Everything works as expected.
Thank you very much for your work.
