### ISSUE TITLE
live server doesn't work 

### ISSUE THREAD

**Issue by Ritupant1** [glenn2223/vscode-live-sass-compiler#347]

**Comment by glenn2223** [comment]
Wrong extension my friend. This is live sass, not live server - I don't maintain that one

---

Closing as not relevant to this extension

**Comment by Ritupant1** [comment]
I apologise for typing mistake but live sadd compiler doesn't work properly

**Comment by glenn2223** [comment]
Ahh, no problem.

Sorry, I'm going to need more information. What file? Has it ever compiled? Have you made the switch to the `@use` rule before it stopped? There might be a sass error, did the icon in the bottom left change when you save the file?

Have you referred to the faq section https://github.com/glenn2223/vscode-live-sass-compiler/blob/master/docs/faqs.md

**Comment by glenn2223** [comment]
Any news/updates @Ritupant1?

**Comment by glenn2223** [comment]
Closing as info required
