### ISSUE TITLE
it is waching the code with succes when i save the file but on the browser content is not changing

### ISSUE THREAD

**Issue by xolmuhammedov** [glenn2223/vscode-live-sass-compiler#356]

**Comment by javl** [comment]
Just posting your problem as the title of an issue isn't very helpful as there is no way of telling what might be wrong.

Can you provide more info, like:
* What settings are you using?
* Do you see the changes you made appear in the .css when you view the file in your code editor directly?
* How do you load the .css on you page?

**Comment by xolmuhammedov** [comment]
oh sorry i already solved the problem the settings.json was not properly edited

**Comment by glenn2223** [comment]
Closing as solved
