### ISSUE TITLE
problem help

### ISSUE THREAD

**Issue by xolmuhammedov** [glenn2223/vscode-live-sass-compiler#357]
it is waching the code with succes when i save the file but on the browser content is not changing , wheni manually click on Watching... and re press Watch Sass then it is working 

{
  "liveSassCompile.settings.formats": [
    {
      "format": "compressed",
      "extensionName": ".css",
      "savePath": "/css"
    }
  ],
  "liveSassCompile.settings.showOutputWindow": false
}

this is .vscode/settings.json file

**Comment by javl** [comment]
Please don't open multiple issues for the same problem. Just add any additional information to your original issue (here #356).

**Comment by glenn2223** [comment]
Closing as duplicate
