### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by n-masayuki** [glenn2223/vscode-live-sass-compiler#362]
- Issue Type: `Performance`
- Extension Name: `live-sass`
- Extension Version: `6.1.2`
- OS Version: `Darwin arm64 23.5.0`
- VS Code version: `1.91.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///var/folders/bz/4ytcdxx513n6nhy344yv6yb40000gn/T/glenn2223.live-sass-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by glenn2223** [comment]
> ⚠️`file:///var/folders/bz/4ytcdxx513n6nhy344yv6yb40000gn/T/glenn2223.live-sass-unresponsive.cpuprofile.txt`

Can you provide this file that's on your local machine?

**Comment by glenn2223** [comment]
Closing as the file was not provided
