### ISSUE TITLE
Live Sass Compiler doesn't compile

### ISSUE THREAD

**Issue by TecnoProgress** [glenn2223/vscode-live-sass-compiler#363]
Hi, 
I migrated olt Live Sass Compiler to Live Sass Compiler (v6.1.2) in Visual Studio Code (1.91.1 user setup) but it doesn't work.
It detect chenges but it doesn't compile, this is what I see in my

```
Change detected - 7/23/2024, 8:25:43 AM
_middle.scss
--------------------
Watching...
--------------
```

Here's my settings.json file content:
```JS
{"liveSassCompile.settings.formats": [
 
    {
 
      "format": "compressed",
      "extensionName": ".min.css",
      "savePath": "/web/Content"
    }
 
  ],
  "workbench.startupEditor": "none",
  "liveSassCompile.settings.autoprefix": [
  
 
  ],
"editor.minimap.enabled": false,
"liveSassCompile.settings.useNewCompiler": true,
"liveSassCompile.settings.compileOnWatch": true,
"liveSassCompile.settings.generateMap": false,
"liveSassCompile.settings.watchOnLaunch": true,
"workbench.settings.applyToAllProfiles": [
    "liveSassCompile.settings.watchOnLaunch"
],
}
```

What's wrong with it?

Thank you very much

Wania

**Comment by TecnoProgress** [comment]
Thank you very much!

VS Code event: "onDidSaveTextDocument"
--------------------
Found the workspace folder
Workspace Name: satarco_new.tp
--------------------
SASS file saved
A SASS file has been saved, starting checks
--------------------
Checking SASS path isn't excluded
Path: h:\Clienti\satarco_new.tp\web\Content\scss\_buttons.scss
--------------------
No base folder override found. Keeping workspace folder
--------------------
Searching folder
Search results
Path: h:\Clienti\satarco_new.tp\web\Content\scss\_area.scss
  isMatch: true
   - Base path: h:\Clienti\satarco_new.tp
   - Rela path: web\Content\scss\_area.scss
  compare: false
   - Orig file path: h:\Clienti\satarco_new.tp\web\Content\scss\_area.scss
   - Orig sass path: h:\Clienti\satarco_new.tp\web\Content\scss\_buttons.scss
Path: h:\Clienti\satarco_new.tp\web\Content\scss\_blog.scss
  isMatch: true
   - Base path: h:\Clienti\satarco_new.tp
   - Rela path: web\Content\scss\_blog.scss
  compare: false
   - Orig file path: h:\Clienti\satarco_new.tp\web\Content\scss\_blog.scss
   - Orig sass path: h:\Clienti\satarco_new.tp\web\Content\scss\_buttons.scss
Path: h:\Clienti\satarco_new.tp\web\Content\scss\_box-menu.scss
  isMatch: true
   - Base path: h:\Clienti\satarco_new.tp
   - Rela path: web\Content\scss\_box-menu.scss
  compare: false
   - Orig file path: h:\Clienti\satarco_new.tp\web\Content\scss\_box-menu.scss
   - Orig sass path: h:\Clienti\satarco_new.tp\web\Content\scss\_buttons.scss
Path: h:\Clienti\satarco_new.tp\web\Content\scss\_buttons.scss
  isMatch: true
   - Base path: h:\Clienti\satarco_new.tp
   - Rela path: web\Content\scss\_buttons.scss
  compare: true
   - Orig file path: h:\Clienti\satarco_new.tp\web\Content\scss\_buttons.scss
   - Orig sass path: h:\Clienti\satarco_new.tp\web\Content\scss\_buttons.scss
Path: h:\Clienti\satarco_new.tp\web\Content\scss\_footer.scss
  isMatch: true
   - Base path: h:\Clienti\satarco_new.tp
   - Rela path: web\Content\scss\_footer.scss
  compare: false
   - Orig file path: h:\Clienti\satarco_new.tp\web\Content\scss\_footer.scss
   - Orig sass path: h:\Clienti\satarco_new.tp\web\Content\scss\_buttons.scss
Path: h:\Clienti\satarco_new.tp\web\Content\scss\_form.scss
  isMatch: true
   - Base path: h:\Clienti\satarco_new.tp
   - Rela path: web\Content\scss\_form.scss
  compare: false
   - Orig file path: h:\Clienti\satarco_new.tp\web\Content\scss\_form.scss
   - Orig sass path: h:\Clienti\satarco_new.tp\web\Content\scss\_buttons.scss
Path: h:\Clienti\satarco_new.tp\web\Content\scss\_header.scss
  isMatch: true
   - Base path: h:\Clienti\satarco_new.tp
   - Rela path: web\Content\scss\_header.scss
  compare: false
   - Orig file path: h:\Clienti\satarco_new.tp\web\Content\scss\_header.scss
   - Orig sass path: h:\Clienti\satarco_new.tp\web\Content\scss\_buttons.scss
Path: h:\Clienti\satarco_new.tp\web\Content\scss\_libs.scss
  isMatch: true
   - Base path: h:\Clienti\satarco_new.tp
   - Rela path: web\Content\scss\_libs.scss
  compare: false
   - Orig file path: h:\Clienti\satarco_new.tp\web\Content\scss\_libs.scss
   - Orig sass path: h:\Clienti\satarco_new.tp\web\Content\scss\_buttons.scss
Path: h:\Clienti\satarco_new.tp\web\Content\scss\_loader.scss
  isMatch: true
   - Base path: h:\Clienti\satarco_new.tp
   - Rela path: web\Content\scss\_loader.scss
  compare: false
   - Orig file path: h:\Clienti\satarco_new.tp\web\Content\scss\_loader.scss
   - Orig sass path: h:\Clienti\satarco_new.tp\web\Content\scss\_buttons.scss
Path: h:\Clienti\satarco_new.tp\web\Content\scss\_middle.scss
  isMatch: true
   - Base path: h:\Clienti\satarco_new.tp
   - Rela path: web\Content\scss\_middle.scss
  compare: false
   - Orig file path: h:\Clienti\satarco_new.tp\web\Content\scss\_middle.scss
   - Orig sass path: h:\Clienti\satarco_new.tp\web\Content\scss\_buttons.scss
Path: h:\Clienti\satarco_new.tp\web\Content\scss\_modal_newsletter_amico.scss
  isMatch: true
   - Base path: h:\Clienti\satarco_new.tp
   - Rela path: web\Content\scss\_modal_newsletter_amico.scss
  compare: false
   - Orig file path: h:\Clienti\satarco_new.tp\web\Content\scss\_modal_newsletter_amico.scss
   - Orig sass path: h:\Clienti\satarco_new.tp\web\Content\scss\_buttons.scss
Path: h:\Clienti\satarco_new.tp\web\Content\scss\_navbar.scss
  isMatch: true
   - Base path: h:\Clienti\satarco_new.tp
   - Rela path: web\Content\scss\_navbar.scss
  compare: false
   - Orig file path: h:\Clienti\satarco_new.tp\web\Content\scss\_navbar.scss
   - Orig sass path: h:\Clienti\satarco_new.tp\web\Content\scss\_buttons.scss
Path: h:\Clienti\satarco_new.tp\web\Content\scss\_popup.scss
  isMatch: true
   - Base path: h:\Clienti\satarco_new.tp
   - Rela path: web\Content\scss\_popup.scss
  compare: false
   - Orig file path: h:\Clienti\satarco_new.tp\web\Content\scss\_popup.scss
   - Orig sass path: h:\Clienti\satarco_new.tp\web\Content\scss\_buttons.scss
Path: h:\Clienti\satarco_new.tp\web\Content\scss\_slider.scss
  isMatch: true
   - Base path: h:\Clienti\satarco_new.tp
   - Rela path: web\Content\scss\_slider.scss
  compare: false
   - Orig file path: h:\Clienti\satarco_new.tp\web\Content\scss\_slider.scss
   - Orig sass path: h:\Clienti\satarco_new.tp\web\Content\scss\_buttons.scss
Path: h:\Clienti\satarco_new.tp\web\Content\scss\settings\_defaults.scss
  isMatch: true
   - Base path: h:\Clienti\satarco_new.tp
   - Rela path: web\Content\scss\settings\_defaults.scss
  compare: false
   - Orig file path: h:\Clienti\satarco_new.tp\web\Content\scss\settings\_defaults.scss
   - Orig sass path: h:\Clienti\satarco_new.tp\web\Content\scss\_buttons.scss
Path: h:\Clienti\satarco_new.tp\web\Content\scss\settings\_media.scss
  isMatch: true
   - Base path: h:\Clienti\satarco_new.tp
   - Rela path: web\Content\scss\settings\_media.scss
  compare: false
   - Orig file path: h:\Clienti\satarco_new.tp\web\Content\scss\settings\_media.scss
   - Orig sass path: h:\Clienti\satarco_new.tp\web\Content\scss\_buttons.scss
Path: h:\Clienti\satarco_new.tp\web\Content\scss\settings\_settings.scss
  isMatch: true
   - Base path: h:\Clienti\satarco_new.tp
   - Rela path: web\Content\scss\settings\_settings.scss
  compare: false
   - Orig file path: h:\Clienti\satarco_new.tp\web\Content\scss\settings\_settings.scss
   - Orig sass path: h:\Clienti\satarco_new.tp\web\Content\scss\_buttons.scss
--------------------
File found, not excluded
--------------------
Changing status bar to: "Working on it..."
--------------------
Change detected - 7/23/2024, 10:29:54 AM
_buttons.scss
--------------------
Getting SASS files
Query pattern: undefined
Can be overwritten: true
--------------------
Checking folder 1 of 1
Folder: satarco_new.tp
--------------------
No base folder override found. Keeping workspace folder
--------------------
Found 0 SASS files
--------------------
Compiling Sass/Scss Files: 
--------------------
Changing status bar to: Success
Registered timeout to switch state back
--------------------
Registered timeout to revert UI to correct watching status
--------------------
Switching UI state
--------------------
Changing status bar to: Watching
--------------------
Watching...
--------------------
Firing timeout function to switch back
--------------------
Changing status bar to: Watching
--------------------

**Comment by TecnoProgress** [comment]
Hi, I solved my problem.. there was sometring wrong with files scss...

**Comment by glenn2223** [comment]
Glad you sorted it
