### ISSUE TITLE
Please add support for tailwindcss

### ISSUE THREAD

**Issue by naruko-hstk** [glenn2223/vscode-live-sass-compiler#367]
I using tailwindcss with scss.
Already do settings on [here](https://tailwindcss.com/docs/using-with-preprocessors#using-sass-less-or-stylus).
But got error.
![image](https://github.com/user-attachments/assets/8bd89792-a97a-4f06-97fc-93ebda7e409b)
p.s. Ignore `@apply` error.

**Comment by glenn2223** [comment]
Taken from #346 

>... Tailwind analysis your choice to create small CSS files whereas SASS just compiles into CSS. If you're creating content with tailwind classes compiling your CSS but having extra stylings coming from your SASS work then I don't see why they won't work side by side. I'd imagine you'd just have the 2 CSS links in your head elements
>
>However, in the more likely case, you're building custom styles for tailwind via SASS. You probably don't want to and can refer to https://tailwindcss.com/docs/using-with-preprocessors with details as to why

I hope this helps and makes sense

**Comment by glenn2223** [comment]
Closing as "info required"
