### ISSUE TITLE
Disable Life Server

### ISSUE THREAD

**Issue by Tealk** [glenn2223/vscode-live-sass-compiler#37]
Hello,

would it be possible to disable the live server, I do not need it and it takes a long time to start. VSCode always shows me a warning message because of this.
I use the add-on only to compile sass, there is no better add-on for that either

![image](https://user-images.githubusercontent.com/12276250/107732526-e1bed000-6cf8-11eb-88ae-66e489c1c322.png)

**Comment by glenn2223** [comment]
Hi @Tealk,

Sorry for the delay, been crazy and the email from GitHub went into my junk for some reason.

I actually have a branch for [v5](https://github.com/glenn2223/vscode-live-sass-compiler/tree/v5). It's not ready for a full release, but I have removed the Live Server dependency and created an alpha for direct download.

There is a `.vsix` file that you can download, just click the file (currently `live-sass-5.0.0-alpha.1.vsix`) and then click download. Then drag the file into the extensions tab of VS Code. You will need to relaunch for the update to take affect. You will also have to manually uninstall Live Server.

An issue was already raised at #23, so I'll mark this as duplicate and close it.

Thanks
