### ISSUE TITLE
Flex-row does not apply

### ISSUE THREAD

**Issue by hatakealex** [glenn2223/vscode-live-sass-compiler#375]
**main.scss**

```
...
@import "tools/flex";
...
@import "elements/page_item";
...
```

**_flex.scss**
```
...
%flex-column {
    -webkit-box-direction: normal;
    -webkit-box-orient: vertical;
    -moz-box-direction: normal;
    -moz-box-orient: vertical;
    -webkit-flex-direction: column;
    -moz-flex-direction: column;
    -ms-flex-direction: column;
    flex-direction: column;
}

%flex-row {
    -webkit-box-direction: normal;
    -webkit-box-orient: horizontal;
    -moz-box-direction: normal;
    -moz-box-orient: horizontal;
    -webkit-flex-direction: row;
    -moz-flex-direction: row;
    -ms-flex-direction: row;
    flex-direction: row;
}

.row{
    @extend %flex-row;
}
...
```

**_page_item.scss**
```
...
.shop2-product-data {
    .row {
        @extend %flex-column;
    }
}
...
```

No errors occur during compilation. There is no property `.shop2-product-data .row{...}` in the final css file. if I comment the property `.row` in the _flex.scss file, then the required property is found in the final css file

**Comment by hatakealex** [comment]
if i add any css property, for example:
```
.shop2-product-data { 
    .row{
        margin: 0;
        @extend %flex-column;
    }
 }
```
then everything is displayed correctly

**Comment by glenn2223** [comment]
I have just tested it and the output is as expected.

![image](https://github.com/user-attachments/assets/a959d347-ad9d-4df2-a703-ed70583cbdce)

**NOTE:** my `-webkit-` and `-ms-` prefixes were removed as the default autoprefixer/caniuse data no longer require them

**Comment by hatakealex** [comment]
How can I understand the reason in my case?

**Comment by glenn2223** [comment]
Though you may be extending an element well into your SASS file (maybe half way down - or maybe even further); don't forget that the the `@extend` will simply add your class hierarchy/string at the point where your `%flex-row` "class" is declared - so the class reference might just be near the top

Can you send the output CSS file?

**Comment by hatakealex** [comment]
@glenn2223 Thank you very much for the answer. I made many edits to the SCSS, and now the file compiles correctly. I tried to roll back the project to identify the bug, but everything is correct there too. It may have been related to the VScode update (I updated it over the weekend).
