### ISSUE TITLE
@use not applying unless Sass compiler is restarted

### ISSUE THREAD

**Issue by jms-1005** [glenn2223/vscode-live-sass-compiler#376]
Hi Glenn - I am using the @use to import styles from another scss file. I noticed that making changes to the source file requires a restart until the changes are applied to the generated CSS file. 

Steps to reproduce the bug.
1. Create a .scss file and add a variable $color: blue
2. Create another .scss file 
3. Add @use '..path' as *; 
4. Declare a CSS class and reference the $color
5. Now change the $color value in the source file. It will not be applied unless the SASS watcher is restarted.

Thanks 
John

**Comment by glenn2223** [comment]
Sounds like you have included a file that doesn't start with an underscore - see #17 & #329

You need to either adjust your `partialFiles` setting are edit the file name to start with an underscore.

Let me know if this fixes your issue

**Comment by jms-1005** [comment]
Thanks Glenn. It worked for me. Appreciate your quick response.

Best
John
________________________________
