### ISSUE TITLE
How to hide the terminal?

### ISSUE THREAD

**Issue by 6CRIPT** [glenn2223/vscode-live-sass-compiler#379]
How can I hide the terminal while I am compiling code so it does not anoy me so bad?

**Comment by glenn2223** [comment]
Check out [this section](https://github.com/glenn2223/vscode-live-sass-compiler/blob/master/docs/settings.md#livesasscompilesettingsshowoutputwindowon) of the documentation

You can hear about it on my quick-start guide, on YouTube at https://youtu.be/9J__JAgQbS0?t=129

Hope this helps

**Comment by 6CRIPT** [comment]
Thanks man, but where can I find the settings.json file?

**Comment by glenn2223** [comment]
Sorry for the delay.

You create it in a `.vscode` folder, in the root of your project. Alternatively if you press <kbd>F1</kbd> and type "settings", you can choose to edit your workspace or user settings by clicking on one of the options that appears. Changing an option here (again searching on the left) should create a file in the necessary folder.

**Comment by glenn2223** [comment]
Sorry, completely missed this notification.

It's a file you can create in a `.vscode` folder; or, you can press <kbd>F1</kbd> and start typing "settings" you can then choose to edit your user settings (defaults for every project you open, ever) or for the workspace (which overrides user settings) - this will create a file if you opt for workspace settings
