### ISSUE TITLE
Not generating css

### ISSUE THREAD

**Issue by Jonius7** [glenn2223/vscode-live-sass-compiler#4]
When using the original Live Sass Compiler from Ritwick Dey, watching Sass works and I get the output
```
Generated :
.... style.css
.... style.css.map
```
etc.

Went ahead, installed/uninstalled your version and it would just say `Watching...` but no generated output, nor is it generating files.

Is there anything I need to change in settings between the two versions?

**Comment by glenn2223** [comment]
Hi @Jonius7,

Sorry to hear you're having an issue. There's only one setting change that may have to be made,  
`"liveSassCompile.settings.formats": [ { "format":  } ]` now only supports `compressed` and `expanded` [(ref)](https://github.com/glenn2223/vscode-live-sass-compiler#breaking-changes), `compact` and `nested` are no longer supported with the direct link to dart-sass.

I tested it with the same settings as I had with the original extension and mine worked as expected. 

If the above isn't an issue, can you do the following for me:
- Include a copy of your settings
- Include a screenshot of your folder structure
- With a SASS/SCSS file open, run command `Live Sass: Compile Current Sass File` and, if there's no output, see if the icon at the bottom changes to anything

**Comment by Jonius7** [comment]
So it looks like it works if I run the command manually (`Live Sass: Compile Current Sass File`) but it doesn't run when I `Ctrl + S` to save a file.

I do get this error in the output however:
```
Autoprefix Error
auto-fill value is not supported by IE
--------------------
Autoprefix Error
auto-fill value is not supported by IE
--------------------
Autoprefix Error
auto-fill value is not supported by IE
```

Attached is how I've set up my folder:
[scss setup.zip](https://github.com/glenn2223/vscode-live-sass-compiler/files/5725024/scss.setup.zip)

**Comment by glenn2223** [comment]
Sorry for the delay, been racking my brain (to no avail).

Can you do the following for me:
- Download and unpack this: [live-sass-4.2.0.zip](https://github.com/glenn2223/vscode-live-sass-compiler/files/5727395/live-sass-4.2.0.zip), it's a copy of v4.2.0 (before I release it I'm hoping to fix your issue)
- Drag the `.vsix` file into the "Extensions" tab on VS Code (see below screenshot for ref)
- Reload VS Code
- Run `liveSass.command.debugFileList`
- Finally, paste the output into here

Thanks. Again, sorry you're having issues and having to do a bit of debugging for me

![image](https://user-images.githubusercontent.com/33450392/102841534-04212500-43fd-11eb-9d8e-d0acfd8ce475.png)

**Comment by glenn2223** [comment]
Closing as more info is required
