### ISSUE TITLE
Breaking: Changes to Autoprefixer

### ISSUE THREAD

**Issue by glenn2223** [glenn2223/vscode-live-sass-compiler#41]
***~THIS CHANGE RELIES ON THE OUTCOME OF [THIS](https://github.com/postcss/autoprefixer/issues/1399) - I WILL MONITOR AND UPDATE THIS ISSUE WITH ANY STATUS UPDATES~ - Have a working sample, okay to push in the next alpha release***

---

**Nothing here is set in stone. Open for discussion but happy with the current plans**

**Please keep comments related to this issue. Want something else adding/sorting? Please open a new issue**

---

### To do list

- [X] Change default autoprefixer setting to `defaults` (applied in [alpha.3](https://github.com/glenn2223/vscode-live-sass-compiler/blob/18610e21d3be0a3e5c275b2c73b234c70b920096/live-sass-5.0.0-alpha.3.vsix))
- [X] Allow a specific string in the Autoprefixing should happen when there is: (applied in [alpha.3](https://github.com/glenn2223/vscode-live-sass-compiler/blob/18610e21d3be0a3e5c275b2c73b234c70b920096/live-sass-5.0.0-alpha.3.vsix))
    - `"browserslist": [ ... ]` in the `package.json` file
    - a `.browserslistrc` file
    - *By setting the `overrideBrowserslist` to `null`, in the specified string instance, we can immediately support any new files, or new settings within files, that get supported by autoprefixer later on*
- [x] Documentation changes

---

The settings we use for `Autoprefixer` has two issues:
1. uses an outdated default (see note)
2. it forces users to enter duplicate info if they have a `.browserslistrc` file or setting in their `package.json`

#### Outdated default note
The current default is:
```JSON
[
    "> 0.5%",
    "last 2 versions",
    "Firefox ESR",
    "not dead"
]
```

Autoprefixer recommends the below as it *"gives a reasonable configuration for most users"*
```JSON
[
    "defaults"
]
```

**Comment by glenn2223** [comment]
I've managed to get a sample working so this should be pushed in v5.0.0-alpha.3

**Comment by glenn2223** [comment]
[alpha.3](https://github.com/glenn2223/vscode-live-sass-compiler/blob/455e362986e1be7031de1769d3f314b79007eb23/live-sass-5.0.0-alpha.3.vsix) is now availble to use

**Comment by KunalTanwar** [comment]
I have `.browserslistrc` in my root directory and I configured my setting `"liveSassCompile.settings.autoprefix": true` but it is not generating or prefixing CSS Properties.

**Comment by glenn2223** [comment]
Sorry to hear that. I just have a few questions:

1. Do you get the same results with the same list copied directly into the `autoprefix` setting?
    I only ask because of the below (copied from [here](https://github.com/postcss/autoprefixer/tree/10.2.5#why-doesnt-autoprefixer-add-prefixes-to-border-radius))

    ### Why doesn’t Autoprefixer add prefixes to `border-radius`?
    Developers are often surprised by how few prefixes are required today. If Autoprefixer doesn’t add prefixes to your CSS, check 
    if they’re still required on [Can I Use](https://caniuse.com/).

2. If you set the 'showOutputOn' to `Information` can you see that it's using autoprefixer from the output window

**Comment by glenn2223** [comment]
> **P.S** _I found this issue related to prefixing so I commented my issue here._

That's fine, where were you - for testing - when I was introducing this change 😉😂

**Comment by KunalTanwar** [comment]
Well there are several things that `live-sass-compiler` by **ritwickdey** prefixing but your not for example `box-sizing`, CSS `grid` related stuff and many more. The main and I already mentioned in [#561](https://github.com/ritwickdey/vscode-live-sass-compiler/issues/561)
