### ISSUE TITLE
live sass compiler is dependent on Live Server Ritwikey dey 

### ISSUE THREAD

**Issue by turkishkitten** [glenn2223/vscode-live-sass-compiler#42]
I have tried to disable it and use another but when I use Glen sass compiler it automatically adds the live server I mention above. (which is not working) 

I don't know what to use to get a live view when I right click there isn't even an option to see a live preview or open .... 

Ok this may help I have installed a previous version of live server ritwikety..and wallah it has a Go live button that is working but I had to use version from 3 years ago. Would love if this issue was updated :) thanks

**Comment by glenn2223** [comment]
Sorry if I haven't got this right but it looks like you want Live Server disabled?

If so, this is actually scheduled for V5. You can download an alpha below to test it (all my tests have been fine 😁)

alpha.2 = https://github.com/glenn2223/vscode-live-sass-compiler/blob/ef03dbeea5c990326db0c5aac94bf34a43076c8d/live-sass-5.0.0-alpha.2.vsix

alpha.1 = https://github.com/glenn2223/vscode-live-sass-compiler/blob/ef03dbeea5c990326db0c5aac94bf34a43076c8d/live-sass-5.0.0-alpha.1.vsix

**Comment by glenn2223** [comment]
Closing, more info required

**Comment by turkishkitten** [comment]
I just installed an earlier version and the live works but it says on this extension it’s not being updated as the person doesn’t have time.
