### ISSUE TITLE
compile issue v5 alpha 2

### ISSUE THREAD

**Issue by Tealk** [glenn2223/vscode-live-sass-compiler#43]
Hi,

I have found the following error while compiling

```
body[data-theme="dark"]

  .fa-moon::before
    content: "\f185"
```

```
body[data-theme="dark"] .fa-moon::before {
  content: "";
} 
```

**Comment by Tealk** [comment]
Ok after compiling several times the problem has been solved.

**Comment by glenn2223** [comment]
Hey, glad it's working for you. I'm curious how you managed to get it working after compiling the file a few times. My belief was that it's a known issue with SASS, as per #39

**Comment by Tealk** [comment]
Maybe it has to do with the fact that more code is now included

The error occurred when I used the following code, I added the variables only after the compiling was already working

```
body[data-theme="dark"]
  
  .fa-moon::before
    content: "\f185"
```

as soon as i expanded the code, the error was gone

```
body[data-theme="dark"]
  background-color: $bg_dark

  main
    color: $text_dark
  
  .fa-moon::before
    content: "\f185"
```

**Comment by Tealk** [comment]
because i just looked at error #39, is it possible that it is related to another extension? i also have an extension installed which gives me suggestions for fontawesome icons

**Comment by glenn2223** [comment]
> is it possible that it is related to another extension?

No, I wouldn't think so.

People from the original thread report it happening in different situations (when using variables, unquoted string, etc). I suppose if the extension in question is adding text as per any of those cases then it could be at fault. However I'd say that it's still, at its root, a sass issue (as per the link @ #39)

**Comment by glenn2223** [comment]
Out of curiosity, what's the extension and how does it work?

**Comment by Tealk** [comment]
This one
https://github.com/medzhidov/font-awesome-codes-css

**Comment by glenn2223** [comment]
I was right, there's no issue with their extension. It's simple (but effective) and drops the Unicode in as a quoted string.

---

**To confirm:** the issue here appears to be related to the known issue with SASS (as per details in #39)
