### ISSUE TITLE
Is it possible to "Compile Current Sass File" on save?

### ISSUE THREAD

**Issue by nexuz6** [glenn2223/vscode-live-sass-compiler#44]
Hey!

Thanks keeping this fantastic extension alive!

Is it possible to "Compile Current Sass File" when I save?

If not. Is it possible to isolate the "Watch Sass" to current sub-folder where my current .scss file is?

**Comment by glenn2223** [comment]
There are two choices! I'd say you need the second, especially as you want to do it `"when I save"`

1. There is a command you can use.
    1. Open the command palette - press <kbd>F1</kbd> OR (<kbd>Ctrl</kbd>/<kbd>Cmd</kbd>) + <kbd>Shift</kbd> + <kbd>P</kbd>
    2. Enter either:
        1. `liveSass.command.compileCurrentSass`, or
        2. `Compile Current Sass File`
2. Adjust the settings
```JSON
{
    "liveSassCompile.settings.includeItems": [
        "/folder/path/file.scss"
    ]
}
```

---

> Thanks keeping this fantastic extension alive!

You're more than welcome 😁

**Comment by nexuz6** [comment]
Thanks for the quick answer! I will use the second answer. 

I would love to see a watchOnlyCurrentFolder option 😄 

Take care!

**Comment by glenn2223** [comment]
> I would love to see a watchOnlyCurrentFolder option 😄

Sorry, I should have made it clearer.

The `includeItems` setting does accept glob patterns. So, each of the below will work with different results

```JS
{
    "liveSassCompile.settings.includeItems": [
        "/folder/path/file.scss", // Watch just this file
        "/folder/path/*.scss",    // Watch just this folder
        "/folder/path/**.scss"    // Watch this folder and all it's subfolders
    ]
}
```

**Comment by nexuz6** [comment]
Fantastic! 🥇 

Thanks
