### ISSUE TITLE
Release Plan - v5

### ISSUE THREAD

**Issue by glenn2223** [glenn2223/vscode-live-sass-compiler#45]
This is the release plan for v5 (*dates may move*)

- [x] Release final alpha for testing - 2021-03-25 ([v5.0.0-alpha.5](https://github.com/glenn2223/vscode-live-sass-compiler/blob/d7702f45b13c4dad84909032cca8a9a2ea6094f6/live-sass-5.0.0-alpha.5.vsix))
- [x] RC1 (release candidate 1) published on the marketplace - 2021-04-01 (no joke)
- [x] **Issues raised**, paused deployment plan - 2021-04-02
-
- [X] Release rc2 - 2021-04-02
- [x] **Issues raised**, paused deployment plan - 2021-04-02
-
- [X] Release rc3 - 2021-04-03
- [x] **Issues raised**, paused deployment plan - 2021-04-03
-
- [X] Release rc4 - 2021-04-03
- [X] ~~If there are no issues then full v5 release - 2021-04-18 (2 weeks after RC release)~~
-
- [x] Official v5 release - 2021-04-06

**If any changes are required:**
- The current plan freezes
- Issues are fixed and a new RC is published
- This issue is updated with new dates
- Again, it's monitored for two weeks and:
  - if there are no problems, there's a full v5 release
  - if there are problems, this cycle starts again

---

*Marked as `help wanted` to get user feedback (post here) and highlight any issues (post as a new issue)*

---

**Edit:**  
#54 shows an issue that occurred with the limited SemVer support on the VS Code Marketplace. As this is causing installation issues, I will be releasing v5 officially tonight and any further issues will have to be addressed in patches

**Comment by glenn2223** [comment]
rc1 is live! Go install and enjoy!

**Comment by enoversum** [comment]
@glenn2223 That is wonderful. Happily uninstalled the ever-slowing Live Server extension. If any trouble arises, I will let you know. Just went through the settings that needed adapting due to your changes.

**Comment by glenn2223** [comment]
As per #54, I will release v5 officially tonight
