### ISSUE TITLE
thank you for maintaining app.

### ISSUE THREAD

**Issue by JUNGHUNKIM-7** [glenn2223/vscode-live-sass-compiler#46]
could you support new live server(five-server)? old live-server and sass seem not be maintained by admin anymore. if you have plan for that, comment please.
thanks.

**Comment by glenn2223** [comment]
Hi @JUNGHUNKIM-7,

Sorry for the delay.

I'm actually removing the liver server dependency in v5. I believe this extension should remain as a standalone SASS/SCSS compiler with no dependencies on any other VS Code extensions.

If anyone would like to add live reload features then they can then install their preferred extension in addition to my own. 

This extension triggers a change when it outputs the CSS file. So, no matter whichever live reload tool you use, the change should be registered and displayed. If it doesn't then that would be something you'd have to take up with the creator of the chosen live reload extension.

I hope this helps 😁

**Comment by JUNGHUNKIM-7** [comment]
More Cool, i totally agree your plan!
