### ISSUE TITLE
Relative paths in the exclude & include settings aren't working

### ISSUE THREAD

**Issue by glenn2223** [glenn2223/vscode-live-sass-compiler#49]
Paths that are relative to the workspace folder root - or `forceBatchPath` path, if specified - in the include and exclude settings aren't working. Currently, paths have to start with `**/` to work.

**Example**
```JS
{
    "liveSassCompile.settings.excludeList": [
        "**/node_modules/**",      // <= Works
        ".vscode/**",              // <= Doesn't work
        "Style/_Partials/**",      // <= Doesn't work
        "**/Style/_Partials/**",   // <= Works
    ],
    "liveSassCompile.settings.includeList": [
        "/Style/Folder/*.s[ac]ss",      // <= Doesn't work
    ],
}

**Comment by glenn2223** [comment]
I have a fix applied to the repo.

I just want to wait and see if this is the issue @enoversum is referring to. If not, I'd rather fix that problem too - before `rc.2` release

---

@enoversum, can you confirm that this is the issue you're having. 

Thanks

**Comment by enoversum** [comment]
It's related to the `includeItems` settings in my case.  
The following is being reported as the wrong syntax, but is working: 

`"liveSassCompile.settings.includeItems": [
    "wp-content/themes/**/css/*.scss",
    "**/wp-content/themes/**/css/*.scss",
  ],`

The following is suggested ('must start with a path separator'), but doesn't work obviously:

`"liveSassCompile.settings.includeItems": [
    "/wp-content/themes/**/css/*.scss",
    "/**/wp-content/themes/**/css/*.scss",
  ],`

**Comment by glenn2223** [comment]
Thanks for confirming. The syntax isn't forced so you can continue to use the working syntax, despite the error

---

>`"/**/wp-content/themes/**/css/*.scss",`

I just realised there's no pattern matching, like with the include setting. I'll reopen #30 and apply it

**Comment by enoversum** [comment]
Sounds good to me :) !

**Comment by glenn2223** [comment]
Fixed in rc2 - releasing tonight
