### ISSUE TITLE
Output window auto-open

### ISSUE THREAD

**Issue by zsombok** [glenn2223/vscode-live-sass-compiler#53]
I asked for this option and it was implemented:
![image](https://user-images.githubusercontent.com/52130510/113472560-7fff2480-9464-11eb-800a-897c8aad1e51.png)

Now it is gone. :(
So when type "z-ind" and I stop typing, the extension has time to compile and it opens up output window showing the error.
Pls add "None" to "liveSassCompile.settings.showOutputWindowOn".

Thank you! Awesome extension! 🥇

**Comment by glenn2223** [comment]
Sorry, my bad. I'll re-add/fix this in rc3

**Comment by zsombok** [comment]
Much appreciated! 💯

**Comment by MrSandrow** [comment]
I'd really appreciate this feature to be back too.
Thanks for your work !

**Comment by glenn2223** [comment]
Fixed in rc3.  As per #54, you will have to drag the `.vsix` file into the "Extensions" tab to install it
