### ISSUE TITLE
Running the contributed command: 'liveSass.command.watchMySass' failed.

### ISSUE THREAD

**Issue by Wolk9** [glenn2223/vscode-live-sass-compiler#57]
After Updating VSC to version  1.55.0 the Live compiler stays at 'Working on it...' and gives the error: `"Running the contributed command: 'liveSass.command.watchMySass' failed."`

Version: 1.55.0
Commit: c185983a683d14c396952dd432459097bc7f757f
Date: 2021-03-30T16:01:05.981Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 20.3.0

**Comment by glenn2223** [comment]
Sorry to hear about this.

What version of the extension are you using?

In the bottom right corner, did you see something similar to either of the below images?
![Collapsed example error popup that is shown by Live SASS Compiler](https://user-images.githubusercontent.com/33450392/113686477-34948280-96bf-11eb-8886-8a13c10c9633.png)
![Expanded example error popup that is shown by Live SASS Compiler](https://user-images.githubusercontent.com/33450392/113686492-38280980-96bf-11eb-8b38-1c35aecb0847.png)

If so, please press <kbd>F1</kbd> and type `liveSass.command.createIssue`. This will copy the error info to your clipboard and try to open a new browser tab. Ignore the open window prompt and instead paste it into a new comment here.

----

Alternatively, in your settings, add/change `liveSassCompile.settings.showOutputWindowOn` to  `"Trace"`. 

then, try the command again and paste the output here.

Thank you

**Comment by Wolk9** [comment]
> What version of the extension are you using?

I use the latest version v5.0.0

**Comment by Wolk9** [comment]
`### UNEXPECTED ERROR

**Machine & Versions**
| Item | Value |
|----------------------:|:-----------------------|
| VS Code | v1.55.0 |
| Platform | darwin x64 |
| Node | 12.18.3 (85) |
| Live Sass | 5.0.0 |
<details><summary>Installed Extensions</summary><div>
- vscode.configuration-editing (1.0.0)<br/>- vscode.css-language-features (1.0.0)<br/>- vscode.debug-auto-launch (1.0.0)<br/>- vscode.emmet (1.0.0)<br/>- vscode.git (1.0.0)<br/>- vscode.github (0.0.1)<br/>- vscode.github-authentication (0.0.1)<br/>- vscode.html-language-features (1.0.0)<br/>- vscode.json-language-features (1.0.0)<br/>- vscode.merge-conflict (1.0.0)<br/>- vscode.microsoft-authentication (0.0.1)<br/>- ms-vscode.js-debug (1.55.1)<br/>- vscode.testing-editor-contributions (1.0.0)<br/>- vscode.typescript-language-features (1.0.0)<br/>- alefragnani.Bookmarks (13.0.4)<br/>- christian-kohler.path-intellisense (2.3.0)<br/>- CoenraadS.bracket-pair-colorizer-2 (0.2.0)<br/>- donjayamanne.githistory (0.6.16)<br/>- eamodio.gitlens (11.3.0)<br/>- Equinusocio.vsc-material-theme (33.2.0)<br/>- equinusocio.vsc-material-theme-icons (1.2.2)<br/>- esbenp.prettier-vscode (6.3.2)<br/>- formulahendry.auto-rename-tag (0.1.6)<br/>- formulahendry.terminal (0.0.10)<br/>- glenn2223.live-sass (5.0.0)<br/>- Gruntfuggly.todo-tree (0.0.209)<br/>- HookyQR.beautify (1.5.0)<br/>- jgclark.vscode-todo-highlight (2.0.1)<br/>- lihui.vs-color-picker (1.0.0)<br/>- mhutchie.git-graph (1.30.0)<br/>- mkaufman.HTMLHint (0.10.0)<br/>- mrmlnc.vscode-scss (0.9.0)<br/>- naumovs.color-highlight (2.3.0)<br/>- oderwat.indent-rainbow (7.5.0)<br/>- PKief.material-icon-theme (4.6.0)<br/>- ritwickdey.LiveServer (5.6.1)<br/>- stylelint.vscode-stylelint (0.86.0)<br/>- tombonnike.vscode-status-bar-format-toggle (2.0.0)<br/>- Zignd.html-css-class-completion (1.20.0)
</div></details>

**LOG**: 
```JSON
{
"NO LOG": "PLEASE SPECIFY YOUR ISSUE BELOW"
}
```
=======================


`

**Comment by glenn2223** [comment]
My original comment got lost (somehow??), re-adding

---

Sorry to hear this. I wasn't able to replicate it, in Windows, so more info is required.

What version of the extension are you running?

If you saw a Live SASS Compiler error (like the screengrabs at the bottom):
1. Run the command `liveSass.command.createIssue`
    This will save some error info to the clipboard and try to open a URL
2. Ignore the open URL prompt
3.  Instead, paste the info here

If not:
1. Set `liveSassCompile.settings.showOutputWindowOn` to `"Trace"`
2. Try the command again
3. Paste the output here

![image](https://user-images.githubusercontent.com/33450392/113688774-88a06680-96c1-11eb-8ce9-721ccdba0be4.png)

![image](https://user-images.githubusercontent.com/33450392/113688803-8f2ede00-96c1-11eb-97a1-a962835afb7a.png)

**Comment by glenn2223** [comment]
> `### UNEXPECTED ERROR

Thank you, it doesn't seem to have retained the error info. Could you please try the second suggestion?

**Comment by Wolk9** [comment]
### UNEXPECTED ERROR

**Machine & Versions**
| Item | Value |
|----------------------:|:-----------------------|
| VS Code | v1.55.0 |
| Platform | darwin x64 |
| Node | 12.18.3 (85) |
| Live Sass | 5.0.0 |
<details><summary>Installed Extensions</summary><div>
- vscode.configuration-editing (1.0.0)<br/>- vscode.css-language-features (1.0.0)<br/>- vscode.debug-auto-launch (1.0.0)<br/>- vscode.emmet (1.0.0)<br/>- vscode.git (1.0.0)<br/>- vscode.github (0.0.1)<br/>- vscode.github-authentication (0.0.1)<br/>- vscode.html-language-features (1.0.0)<br/>- vscode.json-language-features (1.0.0)<br/>- vscode.merge-conflict (1.0.0)<br/>- vscode.microsoft-authentication (0.0.1)<br/>- ms-vscode.js-debug (1.55.1)<br/>- vscode.testing-editor-contributions (1.0.0)<br/>- vscode.typescript-language-features (1.0.0)<br/>- alefragnani.Bookmarks (13.0.4)<br/>- christian-kohler.path-intellisense (2.3.0)<br/>- CoenraadS.bracket-pair-colorizer-2 (0.2.0)<br/>- donjayamanne.githistory (0.6.16)<br/>- eamodio.gitlens (11.3.0)<br/>- Equinusocio.vsc-material-theme (33.2.0)<br/>- equinusocio.vsc-material-theme-icons (1.2.2)<br/>- esbenp.prettier-vscode (6.3.2)<br/>- formulahendry.auto-rename-tag (0.1.6)<br/>- formulahendry.terminal (0.0.10)<br/>- glenn2223.live-sass (5.0.0)<br/>- Gruntfuggly.todo-tree (0.0.209)<br/>- HookyQR.beautify (1.5.0)<br/>- jgclark.vscode-todo-highlight (2.0.1)<br/>- lihui.vs-color-picker (1.0.0)<br/>- mhutchie.git-graph (1.30.0)<br/>- mkaufman.HTMLHint (0.10.0)<br/>- mrmlnc.vscode-scss (0.9.0)<br/>- naumovs.color-highlight (2.3.0)<br/>- oderwat.indent-rainbow (7.5.0)<br/>- PKief.material-icon-theme (4.6.0)<br/>- ritwickdey.LiveServer (5.6.1)<br/>- stylelint.vscode-stylelint (0.86.0)<br/>- tombonnike.vscode-status-bar-format-toggle (2.0.0)<br/>- Zignd.html-css-class-completion (1.20.0)
</div></details>

**LOG**: 
```JSON
{
"NO LOG": "PLEASE SPECIFY YOUR ISSUE BELOW"
}
```
=======================

**Comment by Wolk9** [comment]
"liveSassCompile.settings.showOutputWindowOn": "Trace"

**Comment by glenn2223** [comment]
> "liveSassCompile.settings.showOutputWindowOn": "Trace"

Sorry, if I wasn't clear before. That needs adding to your `settings.json` file or your workspace folder settings (this file has the extension `.code-workspace`).

Then try running the `liveSass.command.watchMySass` command again. This will show a output window at the bottom (like the screengrab below). Copy that info here

![image](https://user-images.githubusercontent.com/33450392/113690077-f0a37c80-96c2-11eb-8ccc-d43021f6b11c.png)

**Comment by Wolk9** [comment]
> > "liveSassCompile.settings.showOutputWindowOn": "Trace"
> 
> Sorry, if I wasn't clear before. That needs adding to your `settings.json` file or your workspace folder settings (this file has the extension `.code-workspace`).
> 
> Then try running the `liveSass.command.watchMySass` command again. This will show a output window at the bottom (like the screengrab below). Copy that info here
> 
> ![image](https://user-images.githubusercontent.com/33450392/113690077-f0a37c80-96c2-11eb-8ccc-d43021f6b11c.png)

No no, I just copied the JSON code here. I did change the LiveSassCompile.settings.showOutputWindowsOn to trace in the settings. 

Hang on.. I will restart my VSC again. Seems that the error isn't comming up again.

**Comment by Wolk9** [comment]
Command called: "liveSass.command.watchMySass"
--------------------
Switching UI state
--------------------
Changing status bar to: Watching
--------------------
Watching...
--------------------
VS Code event: "onDidSaveTextDocument"
--------------------
SASS file saved
A SASS file has been saved, starting checks
--------------------
Checking SASS path isn't excluded
Path: /Users/treffers/Documents/WINC opleiding/Winc_Academy/Slak_Test/style.scss
--------------------
Checking all workspace folders in project
--------------------
Checking folder 1 of 2
Folder: [object Object]
--------------------
No base folder override found. Keeping workspace folder
--------------------
Searching folder
--------------------
Checking folder 2 of 2
Folder: [object Object]
--------------------
No base folder override found. Keeping workspace folder
--------------------
Searching folder
--------------------
Getting SASS files
Query pattern: **/[^_]*.s[a|c]ss
Can be overwritten: true
--------------------
Checking folder 1 of 2
Folder: [object Object]
--------------------
No base folder override found. Keeping workspace folder
--------------------
Checking folder 2 of 2
Folder: [object Object]
--------------------
No base folder override found. Keeping workspace folder
--------------------

**Comment by Wolk9** [comment]
But this happens after I have set the ShowOutputWindowOn to Trace. After that issuing LiveSass Watch Sass, then in the bar it says 'Watching..." while it is initial saying: 'Working on that' and gives the error in the topic of this very thread.

**Comment by glenn2223** [comment]
And did an error like the below show up in the bottom corner?

![Collapsed example error popup that is shown by Live SASS Compiler](https://user-images.githubusercontent.com/33450392/113686477-34948280-96bf-11eb-8886-8a13c10c9633.png)

**Comment by Wolk9** [comment]
> And did an error like the below show up in the bottom corner?
> 
> ![Collapsed example error popup that is shown by Live SASS Compiler](https://user-images.githubusercontent.com/33450392/113686477-34948280-96bf-11eb-8886-8a13c10c9633.png)

Yes, but then with the message: Running the contributed command: 'liveSass.command.watchMySass' failed. #57

**Comment by Wolk9** [comment]
I have now restarted VSC code with the 'trace' option on. It loads with the following information output:

`"live-sass-compiler" is now activate
--------------------
Constructing app model
--------------------
Constructing error logger
--------------------
Clearing any old log data
--------------------
Error logs cleared
--------------------
Changing status bar to: "Starting..."
--------------------
App model constructed
--------------------
Checking for an unread announcement
--------------------
Live SASS commands ready
Commands have been saved and are ready to be used
--------------------
Announcement has already been shown
--------------------
Changing status bar to: Not watching (or Watch SASS)
--------------------
`

Then I click on 'Watch Sass' in the toolbar  and this appears:

<img width="601" alt="Schermafbeelding 2021-04-06 om 11 53 24" src="https://user-images.githubusercontent.com/66083478/113693313-c22b9e80-96ce-11eb-845b-18d8865d403d.png">

**Comment by glenn2223** [comment]
Ahh okay, I wanted to start with `"Unhandled error with Live Sass Compiler. Error message:"`. It's this that means the error information has been saved for me to debug.

Can you try installing the below version:  
[live-sass-5.0.0-rc.4.1.zip](https://github.com/glenn2223/vscode-live-sass-compiler/files/6263807/live-sass-5.0.0-rc.4.1.zip)

To install it you: unzipping the folder then drag the `.vsix` file into the "Extensions" tab of VS Code

**Comment by Wolk9** [comment]
Done.

Gives the same error. Keeps staying on 'Working on it...'

**Comment by glenn2223** [comment]
So I can see why the error wasn't reportng as I expected.

Please try the below. 

This will not resolve the issue, but it should show the error message I wanted (`"Unhandled error with Live Sass Compiler. Error message:"`)

If it does, can you (as you did before):
1. Run the command `liveSass.command.createIssue`
2. This will save some error info to the clipboard and try to open a URL
3. Ignore the open URL prompt
4. Instead, paste the info here

**Comment by Wolk9** [comment]
Done.

Have to disappoint you. Still the failed error and 'Working on it...'

**Comment by glenn2223** [comment]
Sorry I left off the new zip file 

Did you install [live-sass-5.0.0-rc.4.2.zip](https://github.com/glenn2223/vscode-live-sass-compiler/files/6263928/live-sass-5.0.0-rc.4.2.zip)?

**Comment by Wolk9** [comment]
Yes I did install rc.4.2

**Comment by glenn2223** [comment]
Sorry for the delay, been frazzling my mind as to why the error wasn't being caught. Turned out I'd applied the error catcher to only one function and not the other 🤦‍♂️

Please can you try again for the below:  
[live-sass-5.0.0-rc.4.3.zip](https://github.com/glenn2223/vscode-live-sass-compiler/files/6264147/live-sass-5.0.0-rc.4.3.zip)

Hopefully this time I will get usable error info 🤞

**Comment by Wolk9** [comment]
No probs. I was having lunch break. I wil give it a try now. Hang on.

**Comment by Wolk9** [comment]
rc4.3 installed and run.

Have to disappoint you again. Still the failed error. 

This is the output:

`"live-sass-compiler" is now activate
--------------------
Constructing app model
--------------------
Constructing error logger
--------------------
Clearing any old log data
--------------------
Error logs cleared
--------------------
Changing status bar to: "Starting..."
--------------------
App model constructed
--------------------
Checking for an unread announcement
--------------------
Live SASS commands ready
Commands have been saved and are ready to be used
--------------------
Announcement has already been shown
--------------------
Changing status bar to: Not watching (or Watch SASS)
--------------------
Command called: "liveSass.command.watchMySass"
--------------------
Starting to compile all files
--------------------
Changing status bar to: "Working on it..."
--------------------
Getting SASS files
Query pattern: **/[^_]*.s[a|c]ss
Can be overwritten: true
--------------------
Checking folder 1 of 2
Folder: [object Object]
--------------------
No base folder override found. Keeping workspace folder
--------------------
Checking folder 2 of 2
Folder: [object Object]
--------------------
No base folder override found. Keeping workspace folder
--------------------
Getting SASS files
Query pattern: **/[^_]*.s[a|c]ss
Can be overwritten: true
--------------------
Checking folder 1 of 2
Folder: [object Object]
--------------------
No base folder override found. Keeping workspace folder
--------------------
Checking folder 2 of 2
Folder: [object Object]
--------------------
No base folder override found. Keeping workspace folder
--------------------
`

**Comment by Wolk9** [comment]
and

### UNEXPECTED ERROR

**Machine & Versions**
| Item | Value |
|----------------------:|:-----------------------|
| VS Code | v1.55.0 |
| Platform | darwin x64 |
| Node | 12.18.3 (85) |
| Live Sass | 5.0.0 |
<details><summary>Installed Extensions</summary><div>
- vscode.configuration-editing (1.0.0)<br/>- vscode.css-language-features (1.0.0)<br/>- vscode.debug-auto-launch (1.0.0)<br/>- vscode.emmet (1.0.0)<br/>- vscode.git (1.0.0)<br/>- vscode.github (0.0.1)<br/>- vscode.github-authentication (0.0.1)<br/>- vscode.html-language-features (1.0.0)<br/>- vscode.json-language-features (1.0.0)<br/>- vscode.merge-conflict (1.0.0)<br/>- vscode.microsoft-authentication (0.0.1)<br/>- ms-vscode.js-debug (1.55.1)<br/>- vscode.testing-editor-contributions (1.0.0)<br/>- vscode.typescript-language-features (1.0.0)<br/>- alefragnani.Bookmarks (13.0.4)<br/>- christian-kohler.path-intellisense (2.3.0)<br/>- CoenraadS.bracket-pair-colorizer-2 (0.2.0)<br/>- donjayamanne.githistory (0.6.16)<br/>- eamodio.gitlens (11.3.0)<br/>- Equinusocio.vsc-material-theme (33.2.0)<br/>- equinusocio.vsc-material-theme-icons (1.2.2)<br/>- esbenp.prettier-vscode (6.3.2)<br/>- formulahendry.auto-rename-tag (0.1.6)<br/>- formulahendry.terminal (0.0.10)<br/>- glenn2223.live-sass (5.0.0)<br/>- Gruntfuggly.todo-tree (0.0.209)<br/>- HookyQR.beautify (1.5.0)<br/>- jgclark.vscode-todo-highlight (2.0.1)<br/>- lihui.vs-color-picker (1.0.0)<br/>- mhutchie.git-graph (1.30.0)<br/>- mkaufman.HTMLHint (0.10.0)<br/>- mrmlnc.vscode-scss (0.9.0)<br/>- naumovs.color-highlight (2.3.0)<br/>- oderwat.indent-rainbow (7.5.0)<br/>- PKief.material-icon-theme (4.6.0)<br/>- ritwickdey.LiveServer (5.6.1)<br/>- stylelint.vscode-stylelint (0.86.0)<br/>- tombonnike.vscode-status-bar-format-toggle (2.0.0)<br/>- Zignd.html-css-class-completion (1.20.0)
</div></details>

**LOG**: 
```JSON
{
"NO LOG": "PLEASE SPECIFY YOUR ISSUE BELOW"
}
```
=======================

**Comment by glenn2223** [comment]
Are you sure you have installed rc4.3? I only ask because the `Checking folder # of #` should read as below

```
--------------------
Checking folder 1 of 1
Folder: Sass Sample // <- this is the folder name (Not [object Object])
--------------------
```

**Comment by glenn2223** [comment]
Thanks for that extra info as well. I can see you haven't installed it. Can you take a screengrab of the "Extensions" tab?

Yours is `glenn2223.live-sass (5.0.0)` and it should be `glenn2223.live-sass (5.0.0-rc.4.3)`

**Comment by Wolk9** [comment]
Ah... you rang a bell.... 
I checked and indeed it wasn't installed. Possible I clicked on "update to 5.0.0" and downgraded with that. 

Uninstalled the complete extention, then installed rc4.3. Now the screen shows:

<img width="637" alt="Schermafbeelding 2021-04-06 om 14 09 59" src="https://user-images.githubusercontent.com/66083478/113708791-f8264e00-96e1-11eb-8c29-3b5c6b7f1a98.png">

**Comment by Wolk9** [comment]
### UNEXPECTED ERROR

**Machine & Versions**
| Item | Value |
|----------------------:|:-----------------------|
| VS Code | v1.55.0 |
| Platform | darwin x64 |
| Node | 12.18.3 (85) |
| Live Sass | 5.0.0-rc.4.3 |
<details><summary>Installed Extensions</summary><div>
- vscode.css-language-features (1.0.0)<br/>- vscode.debug-auto-launch (1.0.0)<br/>- vscode.emmet (1.0.0)<br/>- vscode.git (1.0.0)<br/>- vscode.github (0.0.1)<br/>- vscode.github-authentication (0.0.1)<br/>- vscode.html-language-features (1.0.0)<br/>- vscode.merge-conflict (1.0.0)<br/>- vscode.microsoft-authentication (0.0.1)<br/>- ms-vscode.js-debug (1.55.1)<br/>- vscode.testing-editor-contributions (1.0.0)<br/>- alefragnani.Bookmarks (13.0.4)<br/>- christian-kohler.path-intellisense (2.3.0)<br/>- CoenraadS.bracket-pair-colorizer-2 (0.2.0)<br/>- donjayamanne.githistory (0.6.16)<br/>- eamodio.gitlens (11.3.0)<br/>- Equinusocio.vsc-material-theme (33.2.0)<br/>- equinusocio.vsc-material-theme-icons (1.2.2)<br/>- esbenp.prettier-vscode (6.3.2)<br/>- formulahendry.auto-rename-tag (0.1.6)<br/>- formulahendry.terminal (0.0.10)<br/>- glenn2223.live-sass (5.0.0-rc.4.3)<br/>- Gruntfuggly.todo-tree (0.0.209)<br/>- HookyQR.beautify (1.5.0)<br/>- jgclark.vscode-todo-highlight (2.0.1)<br/>- lihui.vs-color-picker (1.0.0)<br/>- mhutchie.git-graph (1.30.0)<br/>- mkaufman.HTMLHint (0.10.0)<br/>- mrmlnc.vscode-scss (0.9.0)<br/>- naumovs.color-highlight (2.3.0)<br/>- oderwat.indent-rainbow (7.5.0)<br/>- PKief.material-icon-theme (4.6.0)<br/>- ritwickdey.LiveServer (5.6.1)<br/>- stylelint.vscode-stylelint (0.86.0)<br/>- tombonnike.vscode-status-bar-format-toggle (2.0.0)<br/>- Zignd.html-css-class-completion (1.20.0)
</div></details>

**LOG**: 2021-04-06 12:09:42.200Z
```JSON
{
    "createdAt": "2021-04-06T12:09:42.200Z",
    "event": {
        "files": "Error lies in getSassFiles()",
        "error": {
            "stack": "Error: ENOENT: no such file or directory, scandir '/Volumes/config'",
            "message": "ENOENT: no such file or directory, scandir '/Volumes/config'",
            "errno": -2,
            "code": "ENOENT",
            "syscall": "scandir",
            "path": "/Volumes/config"
        }
    }
}
```
=======================

**Comment by Wolk9** [comment]
Seeing this log myself I have a clue:

The 'config' workspace is residing on my RP4i with Home Assistant running on it. But once this Samba server is somehow disconnected, the mappings to those directories are not available anymore. And it appears that this extension wants them to be real, dispite the fact that they have no tie with the Sass/scss files I would like to live-compile. Maybe this should be addressed in a next RFC.

**Comment by glenn2223** [comment]
Can you take a screengrab of the file structure or make a copy here if you can't? Something like:
```
- Folder
  - Volumes
    - config
      - somefile.config
  - Sass
    - style.scss
```

Just so I can try and tackle this. Thanks

**Comment by Wolk9** [comment]
<img width="652" alt="Schermafbeelding 2021-04-06 om 14 32 41" src="https://user-images.githubusercontent.com/66083478/113711196-f447fb00-96e4-11eb-80e4-66d7469037f2.png">

**Comment by glenn2223** [comment]
So the config folder (highlighted in blue) path is `/Volumes/config`. It also doesn't have any SASS files and is it the one that can disconnect?

**Comment by Wolk9** [comment]
> So the config folder (highlighted in blue) path is `/Volumes/config`. It also doesn't have any SASS files and is it the one that can disconnect?

Correct .

**Comment by glenn2223** [comment]
So `fdir` allows you to suppress errors, which it claims to do by default (obviously not 😁)

Can you test this one, which should suppress the error: [live-sass-5.0.0-rc.4.4.zip](https://github.com/glenn2223/vscode-live-sass-compiler/files/6264741/live-sass-5.0.0-rc.4.4.zip)

If this works then I can get v5 released tonight.  
*FYI: Problems with publishing to VS Code's marketplace means that I really don't want to (well, can't) publish any more RC's (Ref #54)*

**Comment by Wolk9** [comment]
Flawless!! 

You're the best! 

Glad I could contribute to this release.

**Comment by glenn2223** [comment]
Good, I'm glad it works. v5 here we come 🎉

Thanks for your help in debugging this.

**Comment by Wolk9** [comment]
I will close this issue now.
