### ISSUE TITLE
SCSS compile output

### ISSUE THREAD

**Issue by cfcoder** [glenn2223/vscode-live-sass-compiler#58]
I really like your extension for compiling SCSS code in VSCode! Thanks for making it.  When I first installed it, every compile after turning on Watch would show compile output details of files being compiled in the Output pane of VSC. Recently, something changed (no clue what) and it won't do that any more. I don't see any setting to turn this on or off. I'd actually like to control this from the bottom VSC border. Sometimes I want to see the output details, other times, not.

**Comment by glenn2223** [comment]
> I really like your extension for compiling SCSS code in VSCode!

I'm glad to hear it 😁

>... would show compile output details of files being compiled in the Output pane of VSC. Recently, something changed (no clue what) and it won't do that any more. I don't see any setting to turn this on or off.

It sounds like you've been switched over to the v5 RC I published. This version has had a massive overhaul, including to the output window.

The setting is now called `showOutputWindowOn` and acts more like a logger. The default is `Warning`, this will only shows anything classified as `Warning`or over.

Details of the new setting can be seen [here](https://github.com/glenn2223/vscode-live-sass-compiler/blob/master/docs/settings.md#livesasscompilesettingsshowoutputwindowon). It needs details adding about what/when each of the options will output - which I'll do soon.

> Sometimes I want to see the output details, other times, not.

It sounds like you want this on `Information` when you want to know the files being compiled. Then `Warning`, `Error` or `None` when you don't.

> I'd actually like to control this from the bottom VSC border.

I'm not sure if this could be worked in. How would you expect it to work?

**Comment by cfcoder** [comment]
Yep! That is the setting that makes a difference. It was set to Trace. I set it to Information and now it's outputing.

For control from the bottom VSC border, I'm thinking clicking on the "Watching..." button there and in the popup menu, offer changes to the output level from there instead of having to go into the .json file or the Settings > Preferences.

As an additional nicety, it would be cool to have a keyboard key-combo I could hold down when I Save that would (for that one time) switch from Trace to some other setting (not sure which one) that would 1. Open the Output panel 2. Then show the generated output.

**Comment by glenn2223** [comment]
> Yep! That is the setting that makes a difference. It was set to Trace. I set it to Information and now it's outputing.

Glad I could help

> For control from the bottom VSC border, I'm thinking clicking on the "Watching..." button there and in the popup menu, offer changes to the output level from there instead of having to go into the .json file or the Settings > Preferences.

Bad news I'm afraid. Currently, clicking activates and deactivated the watching state of the extension. This is a key feature and isn't going to change I'm afraid.

I did think about adding a context menu (alt mouse click), however, that's not available to me in VS Code.

>As an additional nicety, it would be cool to have a keyboard key-combo I could hold down when I Save that would (for that one time) switch from Trace to some other setting (not sure which one) that would 1. Open the Output panel 2. Then show the generated output.

I know you can assign a key combination to a command and I could add more commands to programmatically change the setting. However, this might just add unnecessary/confusing bloat to the extension. I'll have to have a look into/think about this.

----

Closing this issue as the key point is resolved and opening a new issue for the proposed feature

**Comment by cfcoder** [comment]
@glenn2223 You stated that clicking on the bottom VSC border toggles watching scss changes to trigger compile... why can't that be top of a dropdown menu there that you see if you click and hold. If you just click like always, could there be a default action which is the same as now (toggle watching)? So users used to clicking still toggle. But click and hold and dropdown appears with explicit choice for watching: on/off plus other menu items?  I don't know what VSC allows but to me that would be cool functionality.
