### ISSUE TITLE
Merge Media Queries

### ISSUE THREAD

**Issue by mediafoks** [glenn2223/vscode-live-sass-compiler#62]
Good afternoon Great extension!
I'm sorry if Google translate badly.
Please tell me if in the future it is possible to make such a function:
There are many media queries in different *.scss files. When compiling, all media queries of the same type must be combined and placed at the end of the output file *.css.
Is it possible?

**Comment by glenn2223** [comment]
Sorry for the delay in getting back to you.

The translation is fine, definitely puts the message across clearly 😁.

However, I don't think this is something that I'd like to implement. The order of CSS is very important and, as there's no perfect way of combining queries, users can get unexpected results.

There's a postcss plugin that does this exact feature and they have a whole notes section on why the user experience could break - you can read it [here](https://github.com/hail2u/node-css-mqpacker#notes).
