### ISSUE TITLE
savePath issue with compiled files

### ISSUE THREAD

**Issue by johced** [glenn2223/vscode-live-sass-compiler#66]
Hi, 

When running Watch sass in VS code, the css files are stored in my scss folder. This became an issue with the old live sass compiler, I then installed yours. It worked, now I just opened up another project and the same thing occurs. It do not create the css / dist/css folders and instead puts the files in the scss folder as mentioned. 

I will try to uninstall and install, but second time it happens so I wanted to post it. When it works it's awesome! 

.vscode -> settings.json 
{
  "liveSassCompile.settings.formats": [
    {
      "format": "expanded",
      "extensionName": ".css",
      "savePath": "/css"
    },
    {
      "extensionName": ".min.css",
      "format": "compressed",
      "savePath": "/dist/css"
    }
  ],
  "liveSassCompile.settings.excludeList": ["**/node_modules/**", ".vscode/**"],
  "liveSassCompile.settings.generateMap": false,
  "liveSassCompile.settings.autoprefix": ["defaults"]
}

It has worked, but now it doesn't.

**Comment by glenn2223** [comment]
Sorry to hear you're having a problem.

- Before doing any of the below, can you take a screengrab of the folder structure?
- Are those the settings for the project that works and the project that doesn't?
- Once open, can you change the `showOutputOn`setting to trace, save a file and then include the output here?
- Does it save the files to the `/css` and `/dist/css` folders if you manually create them?

**Comment by johced** [comment]
Response time === A+. 

**Update:** Uninstalled and installed (same project, folder structure and .vscode/settings.json) and it started to work. 

Same code for the project that worked and this that didn't. Before uninstall/install I did try to create the /css and /dist/css folder manually, it didn't have any affect. 

I will save your instruction for fail search next time it happens, and post it accordingly.

**Comment by glenn2223** [comment]
Glad it's working again for you.

As it's now working, I'll close this issue. Still post the comment/details here, once it happens again, and I'll reopen it.

Thanks in advance 😁
