### ISSUE TITLE
Unhandled error while compiling all files. Error message: Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by TeKGameR950** [glenn2223/vscode-live-sass-compiler#68]
Hi, i just installed the extension and when i click on watch sass here is the message i get.

Live Sass Compiler: Unhandled error while compiling all files. Error message: Cannot read property 'map' of undefined

any known fix ?

**Comment by glenn2223** [comment]
Sorry to hear you have had this problem. 

Can you please follow the below steps? I can then find the problem and apply a fix.

1. Save all the files so you get the error notification pop up
2. Run `liveSass.command.createIssue`, this will copy some data into your clipboard
3. Ignore the pop-up (it's just a link to create a new issue, which isn't necessary)
4. Come back here and paste the info

Can I also see a screengrab of your folder structure and have a copy of your settings?

**Comment by glenn2223** [comment]
@TeKGameR950, did you get my last comment?

**Comment by glenn2223** [comment]
Closing as info required - with no reply
