### ISSUE TITLE
Nothing is being printed to Live Sass Compile output window any more

### ISSUE THREAD

**Issue by zigojacko** [glenn2223/vscode-live-sass-compiler#70]
There has been a few updates since I last used this but I have nothing at all being written to the Live Sass Compile output window any longer. Literally nothing at all.

So this is highly frustrating as I can't see whether compilation is working or not easily.

Not really sure what I can try and do about this...?

**Comment by zigojacko** [comment]
Ah don't worry. Sorted now. Seemed to be an issue with the vscode application writing to settings and logs following an update.

Really odd but seems to have rectified after a few restarts now.

**Comment by zigojacko** [comment]
Actually, this is a problem. There is no output being created from this extension.

Can you suggest anything I can try (I have tried several uninstalls and reinstalls and app restarts).

I really don't know what else to do - this was working fine for ages and something has happened since a recent update.

@glenn2223

**Comment by glenn2223** [comment]
Have you tried setting `liveSassCompile.settings.showOutputWindowOn` to `"Information"`? You can read more about the setting [here](https://github.com/glenn2223/vscode-live-sass-compiler/blob/master/docs/settings.md#livesasscompilesettingsshowoutputwindowon)

**Comment by glenn2223** [comment]
Hi @zigojacko,

Did the above work for you?

**Comment by fatherofphysics** [comment]
Glen is died he cant work on live sass compiler anymore................Sass is dead .........😡😡😡😠😠👿🗯🗯💢

**Comment by glenn2223** [comment]
Please ignore @fatherofphysics's comment, I am still actively maintaining this project

**Comment by zigojacko** [comment]
> Hi @zigojacko,
> 
> Did the above work for you?

I've yet to try it again in the specific project but I will do soon and report back here for sure. 👍

**Comment by fatherofphysics** [comment]
lol Sorry for saying you dead glen it was my problem I already created css and after watching sass it stops cause already have css file. Now sass is working fine . I Love You as a Friend not spammer noob

**Comment by glenn2223** [comment]
> I've yet to try it again in the specific project but I will do soon and report back here for sure. 👍

That's great, thanks. Hopefully, this will cross another issue off the list 😁

**Comment by glenn2223** [comment]
> lol Sorry for saying you dead glen it was my problem I already created css and after watching sass it stops cause already have css file. Now sass is working fine .

It's fine @fatherofphysics, spam was the only thing that really made sense when I was choosing to hide it.

>I Love You as a Friend not spammer noob @glenn2223

Love you too ✌❤  😂

**Comment by glenn2223** [comment]
Closing as:
1. Stale
2. I believe the cause is the old `liveSassCompile.settings.showOutputWindowOn` setting, which has been adjusted in v5.0.3 to align with the default output from Ritwick's original extension

---

If the issue still persists, please reopen this issue with more details
