### ISSUE TITLE
command 'liveSass.command.watchMySass' not found

### ISSUE THREAD

**Issue by lmd10237589** [glenn2223/vscode-live-sass-compiler#72]
<img width="702" alt="WeChat695b718e5c528e8c0666a5cda604f49e" src="https://user-images.githubusercontent.com/50946441/116050153-bf0e4780-a6a9-11eb-99a4-33ab004d38fe.png">
Visual Studio Code：V1.55.2

**Comment by glenn2223** [comment]
Het @lmd10237589,

Sorry to hear it's not activating.

I have copied the below screenshot from the FAQ.

Could you please make sure that you have a SASS or SASS file in your workspace. If there isn't one of these file types (ending `.sass` or `.scss`), then the extension will not activate and the commands will not register.

![image](https://user-images.githubusercontent.com/33450392/116060206-92423c00-a679-11eb-91bc-db06fe8ff5a2.png)
