### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by yama143** [glenn2223/vscode-live-sass-compiler#74]
- Issue Type: `Bug`
- Extension Name: `live-sass`
- Extension Version: `5.0.2`
- OS Version: `Windows_NT x64 10.0.19042`
- VS Code version: `1.55.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by glenn2223** [comment]
HI @yama143,

Sorry to see you've had this problem. 

I really need the information that VS Code would have saved to your clipboard, this is why it states
*`⚠️ We have written the needed data into your clipboard. Please paste! ⚠️`*

At what point did the error come up? When you saved a file or when you launched the project?

**Comment by glenn2223** [comment]
Closing as more info is required.

If you still have the issue then please open a new issue and paste the text copied to your clipboard by VS Code
