### ISSUE TITLE
Doesn't show error

### ISSUE THREAD

**Issue by Shams-Raju** [glenn2223/vscode-live-sass-compiler#76]
- **Problem:** Doesn't show any error when I mistakenly write an error code. (sass)

Please fix these issues. This thing is most important in sass. Hope to take it seriously and fix it quickly.

**Comment by glenn2223** [comment]
Hey @Shams-Raju,

It should definitely show the output on error, that is unless you have set the `showOutputOn` setting set to `"None"` - which will only show critical errors or output relative to a command (i.e. `liveSass.command.debugInclusion`).

See this example project that shows an `Error` in the status bar as well as having an output error: [Issue 76 - Sample Project.zip](https://github.com/glenn2223/vscode-live-sass-compiler/files/6414578/Issue.76.-.Sample.Project.zip) - also see below screenshot

![Image showing error output from the above zipped project](https://user-images.githubusercontent.com/33450392/116872772-63ded680-ac0e-11eb-8d8f-f85558a3b15b.png)

Could you please confirm the above works the same for yourself

**Comment by glenn2223** [comment]
**It is becoming clear that I need to change the default for `showOutputOn`**

When I changed the `showOutput` setting to `showOuputOn` it became more of a logger - rather than a show everything or nothing boolean.

The creation of this issue and #70 - and some other issues that have mentioned no output - shows that the default behaviour of this new setting needs to match Ritwick's original extension. I suppose when people migrate they expect it to work the same way as the original.

I will schedule a release where the default for `showOutputOn` is `Information` and no longer `Warning` - this will give the same output as the original extension.

**Comment by Shams-Raju** [comment]
> **It is becoming clear that I need to change the default for `showOutputOn`**
> 
> When I changed the `showOutput` setting to `showOuputOn` it became more of a logger - rather than a show everything or nothing boolean.
> 
> The creation of this issue and #70 - and some other issues that have mentioned no output - shows that the default behaviour of this new setting needs to match Ritwick's original extension. I suppose when people migrate they expect it to work the same way as the original.
> 
> I will schedule a release where the default for `showOutputOn` is `Information` and no longer `Warning` - this will give the same output as the original extension.

Yes, I saw the difference. When I set ("showOutputWindow": none) then I can't see the sass error in output windows.
But when I set ("showOutputWindow": warning) then this is perfectly working. But there is a problem. 
When I set "warning" then I write a half code like:  color: ------ then instant output windows show me the disgusting warning.
No need for this warning in output windows.😑
![Screenshot_92](https://user-images.githubusercontent.com/63977867/116876241-f5b20800-ac3d-11eb-864c-15041b8a3e9f.png)

**Comment by glenn2223** [comment]
>Yes, I saw the difference. When I set ("showOutputWindow": none) then I can't see the sass error in output windows.
But when I set ("showOutputWindow": warning) then this is perfectly working.

Glad that cleared up the original issue

> But there is a problem.
> When I set "warning" then I write a half code like: color: ------ then instant output windows show me the disgusting warning.
> No need for this warning in output windows.😑

I'm afraid that this is out of scope. This extension is a compiler. This means, to state the obvious, it converts SASS into CSS. So, when you save, it will always reports errors in your code at that point - that's just how it works.

What you need is something that does SASS IntelliSence. This reports errors live, which is what shows in the bottom left - as you have highlighted in your screenshot

**Comment by Shams-Raju** [comment]
> > Yes, I saw the difference. When I set ("showOutputWindow": none) then I can't see the sass error in output windows.
> > But when I set ("showOutputWindow": warning) then this is perfectly working.
> 
> Glad that cleared up the original issue
> 
> > But there is a problem.
> > When I set "warning" then I write a half code like: color: ------ then instant output windows show me the disgusting warning.
> > No need for this warning in output windows.😑
> 
> I'm afraid that this is out of scope. This extension is a compiler. This means, to state the obvious, it converts SASS into CSS. So, when you save, it will always reports errors in your code at that point - that's just how it works.
> 
> What you need is something that does SASS IntelliSence. This reports errors live, which is what shows in the bottom left - as you have highlighted in your screenshot

**Comment by Shams-Raju** [comment]
> What you need is something that does SASS IntelliSense. This reports errors live, which is what shows in the bottom left - as you have highlighted in your screenshot

I understood. Thanks for your reply <3

**Comment by glenn2223** [comment]
You're welcome.

In going to re-close this issue as I assume you reopened it by mistake
