### ISSUE TITLE
[meta] Take over original repository and extension

### ISSUE THREAD

**Issue by binyamin** [glenn2223/vscode-live-sass-compiler#77]
The source repository's readme suggests that the original owner might be willing to transfer the repository and marketplace extension to you.

> _[I'm sorry but I'm now super busy, If you want to be a maintainer of the project please feel me to contact me! You've to be passionate about programming]_
> — [ritwickdey/vscode-live-sass-compiler#README.md](https://github.com/ritwickdey/vscode-live-sass-compiler/blob/master/README.md)

I'd suggest contacting him, for two reasons.
1. If he transfers the GitHub repository, any old links should redirect to your project, and existing users & contributors would find your project more easily.
2. If he transfers the extension namespace, you could update any existing users' extensions too, and the transition would be more seamless.

---
PS: I love what you did here. This fork is a great example of why open-source is so important. Thanks, and best of luck!

**Comment by glenn2223** [comment]
>The source repository's readme suggests that the original owner might be willing to transfer the repository and marketplace extension to you.

Yeah, I have reached out with mentions and multiple direct emails - all to no avail. It seems the email on his account and also the mentions in regards to this project are being ignored (or not sending notifications to his actual email account)

> PS: I love what you did here. This fork is a great example of why open-source is so important. Thanks, and best of luck!

Thanks for the love, good wishes and support. Always means a lot 😍

---

As I have already tried reaching out I will close this issue
