### ISSUE TITLE
Is it possible multiple input and multiple output ??

### ISSUE THREAD

**Issue by sinjuangajan** [glenn2223/vscode-live-sass-compiler#78]
Like this. I mean can I decide which files should compile as separate output?
![image](https://user-images.githubusercontent.com/4011140/116964670-bcbf7500-acc9-11eb-8911-1e255e893f32.png)

**Comment by glenn2223** [comment]
No, I'm afraid not. 

Could using `savePathSegmentKeys` and `savePathReplaceSegmentsWith` help?
- `savePathSegmentKeys` - a `string[]` of folder names
- `savePathReplaceSegmentsWith` - what to replace any "key" with

*Sorry, without an example folder structure it's difficult to know if anything current will help*

---

**Side bar:** you probably just rushed the example... however, it should be `[ { ... }, { ... } ]` and not `[ { ... } ], [ { ... } ]`
