### ISSUE TITLE
Was I wrong to assume that this forked extension will support @use instead of @import?

### ISSUE THREAD

**Issue by antebudimir** [glenn2223/vscode-live-sass-compiler#79]
Hi, Glenn!

[This](https://dev.to/clgolden/there-s-a-new-vs-code-sass-compiler-in-town-4ij8) article brought me here with a promise that the @use rule can be used with this extension. However, when I replace @import with @use, nothing gets compiled.

Can you, please, comment?

**Comment by glenn2223** [comment]
I'm afraid that is not as simple as just replacing an `@import` with an `@use`

When you're using an `@use` statement you must either state the namespace before variables/functions, or declare that the statement doesn't have a namespace. You can read about the `@use` rule [here](https://sass-lang.com/documentation/at-rules/use) - but I have taken the snippets below and provided an example for each.

---

>You can access variables, functions, and mixins from another module by writing `<namespace>.<variable>`, `<namespace>.<function>()`, or `@include <namespace>.<mixin>()`. By default, the namespace is just the last component of the module’s URL.
    &nbsp;&nbsp;&nbsp;&nbsp;- SASS Lang - https://sass-lang.com/documentation/at-rules/use#loading-members

So, using this method `color: $font-color;` would become `color: namespace-here.$font-color;`

---

>You can even load a module without a namespace by writing `@use "<url>" as *`. We recommend you only do this for stylesheets written by you, though; otherwise, they may introduce new members that cause name conflicts!
    &nbsp;&nbsp;&nbsp;&nbsp;- SASS Lang - https://sass-lang.com/documentation/at-rules/use#example-3-scss

Now using this method, `@use "./common/partial1";` would become `@use "./common/partial1" as *;` and then the variable(s) can stay as they are. However, as noted above, this is only recommended when importing your own files (as I imagine you are doing so 😁)

---

I created a project which is based on a sample provided by a different issue. I created it to show the use of both methods highlighted above. You can download the sample project here: [Issue 75 - Sample Project.zip](https://github.com/glenn2223/vscode-live-sass-compiler/files/6412336/Issue.75.-.Sample.Project.zip)

---

Please let me know if this doesn't resolve your problem. If it doesn't then I'd need to see your SASS code

**Comment by antebudimir** [comment]
Thanks for the examples.
The article is misleading since it leads you to believe that the replacement of the import with use is all that it takes.

Closing the issue since it's not an issue with the extension.
