### ISSUE TITLE
Tab space issue

### ISSUE THREAD

**Issue by Shams-Raju** [glenn2223/vscode-live-sass-compiler#81]
I use tab space-4 in the sass file. But when it compiles to CSS then it changes to the tab space-2.
How can I fix it? 

![Untitled-1](https://user-images.githubusercontent.com/63977867/118772804-f685a380-b8a5-11eb-9d91-007e0779b1f7.jpg)

**Comment by glenn2223** [comment]
The default output when SASS compiles files - in the `expanded` format - is 2 spaces.

This will require new settings to accommodate this feature. See proposal at #82

Closing as tracking feature at issue #82
