### ISSUE TITLE
Feature proposal: Support all other SASS output formatting options

### ISSUE THREAD

**Issue by glenn2223** [glenn2223/vscode-live-sass-compiler#82]
**Nothing here is set in stone. Open for discussion, but happy with the current plans**

**Please keep comments related to this issue. Want something else adding/sorting? Please open a new issue**

---

### Proposal details

There is a need to specify other aspects of the output file - which is probably why the settings exist in `dart-sass`. Specifically highlighted in #81.

**Issue**
There is no way to specify the output linefeed terminator nor the indent type of width.

**Resolution**
- We will add extra settings under the `formats` setting:
  - `indentType`: `space` or `tab` (default: `space`)
  - `indentWidth`: `number` (default: `2`. max: `10`)
  - `linefeed`: `cr`, `crlf`, `lf` or `lfcr` (default: `lf`)

This requires some document changes

---

### To do list

- [x] Apply code changes
- [x] Update `package.json` to add settings
- [x] Documentation changes (Settings)

**Comment by Shams-Raju** [comment]
Still now tab space-2. This is wrong? :(

![image](https://user-images.githubusercontent.com/63977867/118822063-a3c5df00-b8d9-11eb-99d2-652a5b8df58a.png)

**Comment by glenn2223** [comment]
This is just the proposal - it hasn't been implemented yet.

Once I have something you can test I will add it here

**Comment by glenn2223** [comment]
The second alpha is available, please find the instructions at #84
