### ISSUE TITLE
Release Candidate: testers required (v5.1.0)

### ISSUE THREAD

**Issue by glenn2223** [glenn2223/vscode-live-sass-compiler#84]
Hey, glad you're here! I need you to test the ~alpha~ RC releases, for v5.1, before it's made ready for general release.

### Setup

1. Sign up to receive notifications (on the right on large screens devices, or below on mobile devices)
2. Download the most up to date `.vsix` file from [this branch](https://github.com/glenn2223/vscode-live-sass-compiler/tree/v5.1.0-alpha) or from the latest RC [release](https://github.com/glenn2223/vscode-live-sass-compiler/releases)
3. Drag it into the `Extensions` tab of VS Code
4. VS Code will tell you to reload, do this
5. You're now using the v5.1 alpha

### Issues

Hopefully, there won't be any 😁 - but... if there are, please open a new issue prefixed with `v5.1 RC:`

### The next steps

Once I think I'm ready to move on to a release candidate I will post a comment here - this is why it's important to sign up for notifications.

Please reply to this comment with something positive to highlight that you have had no issues - also include the features you have used/tested to confirm they are working as you'd expect.

From here I will move to a release candidate and then to a full release

**Comment by glenn2223** [comment]
Just got some final tests on `alpha.2`. I will then publish `rc.1`!

---

**Note:** RC1 will not be published to the VS Marketplace - due to the issues that happened with v5's release (#54). OSV, however, does seem to support semantic versioning so the RC will be published there. Anyone using VS Code (*which is most users*) can use RC1 by downloading it from the [release page](https://github.com/glenn2223/vscode-live-sass-compiler/releases)

**Comment by Supportic** [comment]
God bless alpha.2 supports @use "sass:math"; and math.div. :D otherwise dart sass would still yell at me using "/" for division.

**Comment by glenn2223** [comment]
## Status updates

I will be releasing `alpha.3` immenantely - this just has some dependency bumps

----

Currently, I am postponing the launch of v5.1.0 until sass/sass#3074 is merged and the code changes are released. This change is a new logger that I can use to report any warnings and debug messages.

This is primarily down to a combination of:
1. SASS's [deprecation of `/` (slash) as divide](https://sass-lang.com/documentation/breaking-changes/slash-div) and;
2. no ability to output the appropriate deprecation warnings - those that are thrown for any divide operations that use `/`, over `math.div(x, y)`

I'm monitoring sass/sass#3074 and will release an alpha before `rc.1`, once it's implemented

However, if it proves that the implementation of the logger will take too long then I will schedule a `v5.3.0` release cycle (alpha => rc => general release) - again, once it's implemented

**Comment by glenn2223** [comment]
## Status update

It seems like it may be some time before the logger will be included with production code - [reference here](https://github.com/sass/sass/issues/2979#issuecomment-858177193). I am tracking the situation over at #89

In light of this, I will be releasing `rc.1` soon - but this will be without `@degug` & `@warn` messages outputting anything. 

My tests all appeared to be fine. However, if you experienced an issue or would just like to express your joy for the release then please comment 😁

---

**Note:** RC1 will not be published to the VS Marketplace - due to the issues that happened with v5's release (#54). OSV, however, does seem to support semantic versioning so the RC will be published there. Anyone using VS Code (*which is most users*) can use RC1 by downloading it from the [release page](https://github.com/glenn2223/vscode-live-sass-compiler/releases)

**Comment by glenn2223** [comment]
v5.1.0-rc.2 has been released - check it out [here](https://github.com/glenn2223/vscode-live-sass-compiler/releases/tag/v5.1.0-rc.2)

**Comment by glenn2223** [comment]
v5.1.0-rc.3 has been released - check it out [here](https://github.com/glenn2223/vscode-live-sass-compiler/releases/tag/v5.1.0-rc.3)

---

I expect this to be the last release, with the official release coming soon (days, maybe a week)

**Comment by glenn2223** [comment]
Sorry for the delay, v5.1.0 is now live 🎉
