### ISSUE TITLE
Unexpected Error: SUMMARY HERE

### ISSUE THREAD

**Issue by CallMeBLESSING** [glenn2223/vscode-live-sass-compiler#87]
unable to generate .css files and compilation error

**Comment by glenn2223** [comment]
Hey @CallMeBLESSING,

Sorry to hear you're having problems.

Just a couple of questions:
1. What's the error?
2. It's it just with one file or all files that you're trying to compile?

Thanks

**Comment by CallMeBLESSING** [comment]
It generate the save path  folder but it's empty no extension name file
generated (.CSS file for all the files).

**Comment by glenn2223** [comment]
Are you getting any errors in the output window? Anything like the example below

![An error message shown in the "Live Sass Compile" output window](https://user-images.githubusercontent.com/33450392/121333661-e8f59380-c910-11eb-8dee-d5292f823623.png)

**Comment by CallMeBLESSING** [comment]
No errors at all, I've Uninstall and installed still not working, I've
check the Json file still not working

**Comment by glenn2223** [comment]
Can I see your SASS files and your settings.json file? Thanks

**Comment by CallMeBLESSING** [comment]
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by glenn2223** [comment]
> <http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail> Virus-free. [www.avg.com](http://www.avg.com) <http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail> <#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Sorry there was nothing on that reply

**Comment by CallMeBLESSING** [comment]
![IMG_20210610_081200.jpg](https://user-images.githubusercontent.com/73149676/121675455-1af72900-cabc-11eb-957a-daeb9a3f48be.jpg)![IMG-20210611-WA0001.jpg](https://user-images.githubusercontent.com/73149676/121675607-4aa63100-cabc-11eb-9906-180120f4dad7.jpg)

**Comment by glenn2223** [comment]
In the bottom right you can see `🔭 Watching...` - as pictured below?

![image](https://user-images.githubusercontent.com/33450392/121708412-7383f180-cacf-11eb-8078-d58cffce813c.png)

When you save a SASS file do you see `✔ Success` - as pictured below?

![image](https://user-images.githubusercontent.com/33450392/121708608-a9c17100-cacf-11eb-93f9-93be14745bed.png)

-----

I may need to test your actual files to get to the bottom of this one.

Can you create a private repository on GitHub and grant me access? I can then download the files and do some tests.

**Comment by CallMeBLESSING** [comment]
This is what I get in the terminal output ![IMG_20210611_194655.jpg](https://user-images.githubusercontent.com/73149676/121722299-f0be5f00-caed-11eb-9409-b164a2188b11.jpg)

**Comment by glenn2223** [comment]
Thanks.

It looks like you're trying to use a variable that isn't (or hasn't yet) been defined. When you're code has errors it will not output anything.

You need to declare the variable. If you already censored the variable then make sure it's imported before it's used

**Comment by glenn2223** [comment]
Hi @CallMeBLESSING. Did that solve your issue?

**Comment by CallMeBLESSING** [comment]
Hello @glenn2223 , yes i just solved it, it was the ("liveSassCompile.settings.autoprefix"), there was an error earlier so got this new("liveSassCompile.settings.autoprefix": [
  "> 1%",
  "last 2 versions"
],) online and pasted it in and its working fine now. Thanks for your help, I'm so greatful

**Comment by glenn2223** [comment]
Glad you got it working
