### ISSUE TITLE
@debug messages didn't shown in output window

### ISSUE THREAD

**Issue by hanabira80** [glenn2223/vscode-live-sass-compiler#88]
![scss-test](https://user-images.githubusercontent.com/39180600/121995209-8a815700-cde1-11eb-8b2a-6c45c3be2903.png)

upgrade from :  'Ritwick Dey' version
OS : macOS Big Sur 11.2.3

plz! any solution this issue?

**Comment by glenn2223** [comment]
Hi @hanabira80,

This was never available in Ritwick's extension. I switched back to that extension and then got the below output.

![image](https://user-images.githubusercontent.com/33450392/122038262-53a14600-cdcd-11eb-9a6d-9c41699adc7e.png)

![image](https://user-images.githubusercontent.com/33450392/122037679-b8a86c00-cdcc-11eb-9061-5f6b34596995.png)

---

However, this is in fact a known issue to me.

To simplify the issue and to track it as it proceeds, I have opened a new issue - see #89

I will now close this issue, please monitor #89

**Comment by hanabira80** [comment]
Thanks glenn2223!!
