### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by khon0s** [glenn2223/vscode-live-sass-compiler#9]
I installed the Live sass compiler but the Watch sass button won't show up, I tried everything I found on the web about that without succeeding.

**Comment by glenn2223** [comment]
Hi @khon0s,

Can you confirm the below:
- You have uninstalled ritwickdey's extension, if it was even installed
- Do you have a `.scss` or `.sass` file in your workspace? (sorry, I know, obv. question)
- Are you getting an error in the bottom right corner?

Can you also send me a screenshot/list of your installed extensions as well as a screenshot of your workspace files

Thanks.

**Comment by glenn2223** [comment]
Hi @khon0s, do you have any more information?

**Comment by neonomesis** [comment]
Command 'Live Sass: Watch Sass' resulted in an error (command 'liveSass.command.watchMySass' not found)
Something like that? Same problem

**Comment by glenn2223** [comment]
> Command 'Live Sass: Watch Sass' resulted in an error (command 'liveSass.command.watchMySass' not found)
> Something like that? Same problem

Hi @neonomesis, I think the error might have been "command 'liveSass.command.watchMySass' ***is already defined***". Can you make sure that: `ritwickdey.live-sass` is uninstalled and you have reloaded VS Code.

Thanks

**Comment by glenn2223** [comment]
Closing this issue as neonomesis' comment is not directly relevant to the quest, plus I've not heard from khon0s for over 7 days
