### ISSUE TITLE
正确的语法给出错误的提示

### ISSUE THREAD

**Issue by lipanpan-hub** [glenn2223/vscode-live-sass-compiler#90]
![image](https://user-images.githubusercontent.com/47287977/122142837-cd473b80-ce82-11eb-8696-d643342c3aab.png)

**Comment by glenn2223** [comment]
This isn't an error with my extension. My extension just compiles the SASS and has nothing to do with IntelliSense. 

If you use a custom IntelliSense extension then you'd need to report it with them else you may have to open a new issue at one of the two links below.

https://github.com/microsoft/vscode-css-languageservice/issues/152
https://github.com/microsoft/vscode/issues/86903

**Comment by lipanpan-hub** [comment]
好的 非常感谢

**Comment by lipanpan-hub** [comment]
> This isn't an error with my extension. My extension just compiles the SASS and has nothing to do with IntelliSense.
> 
> If you use a custom IntelliSense extension then you'd need to report it with them else you may have to open a new issue at one of the two links below.
> 
> [microsoft/vscode-css-languageservice#152](https://github.com/microsoft/vscode-css-languageservice/issues/152)
> [microsoft/vscode#86903](https://github.com/microsoft/vscode/issues/86903)

好的 非常感谢
