### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by britanym** [glenn2223/vscode-live-sass-compiler#91]
- Issue Type: `Performance`
- Extension Name: `live-sass`
- Extension Version: `5.0.3`
- OS Version: `Darwin x64 20.5.0`
- VS Code version: `1.57.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/var/folders/mb/hkfwfbmj0q35g7k5v8r8x7b80000gn/T/glenn2223.live-sass-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by glenn2223** [comment]
Hi @britanym,

Sorry to hear that you're having an issue. I would really need the file located at `/var/folders/mb/hkfwfbmj0q35g7k5v8r8x7b80000gn/T/glenn2223.live-sass-unresponsive.cpuprofile.txt` in order to do some debugging.

However, I believe it may be that you have a very large application - is that right? If so, the time may have been spent checking the resources in it for SASS files. Do you have all of your SASS files in a subfolder? If so please try out the [liveSassCompile.settings.forceBaseDirectory
](https://github.com/glenn2223/vscode-live-sass-compiler/blob/master/docs/settings.md#livesasscompilesettingsforcebasedirectory) setting

**Comment by britanym** [comment]
Thank you. I did a search on my computer and unsure how I can find this file. I've never had an issue with this sass compiler on previous projects of the same or larger size setup but I am now on a mac and wondering if this doesn't work well with a mac and the server I am working from.

**Comment by glenn2223** [comment]
>... but I am now on a mac and wondering if this doesn't work well with a mac ...

It's possible that the extension isn't optimal for macOS.

I don't have access to a mac to test it myself, but I could run some comparison tests. However, I'd need that *elusive file* and the SASS project your working on. I could then compare your profile with one I can generate myself (on Windows) for differences and also for any identifiable bottlenecks.

>... and the server I am working from

If you're working on a remote server that may have an effect. I'm not too sure how `fdir` works with remote connections. If you copy the files locally, then open that folder and compile the same file(s), do you still have the same issue?

---

**Just some sidebar questions:**  
Is it a constant issue? Does disabling other extensions help? Can you replicate on Linux/Windows?

**Comment by glenn2223** [comment]
Hey @britanym,

Any luck locating that file and can you provide a copy of your project. Thanks.

**Comment by britanym** [comment]
I am not able to locate that file. I did try disabling the extensions as well. It works really fast when I pull the folder down locally. I'm guessing its an issue with the mac I am on and the server. Not sure if there are any plugins to help with that.

**Comment by glenn2223** [comment]
>It works really fast when I pull the folder down locally

So it seems that it was just a delay in the connection between the server and the local machine that caused the issue.

>Not sure if there are any plugins to help with that.

Sorry, I'm not sure if there are any extensions to help.

---

I will close this issue for now but may open a new issue once I've had a think about addressing these types of delays
