### ISSUE TITLE
SASS Variable inside a CSS Variable is not being processed

### ISSUE THREAD

**Issue by JavonX** [glenn2223/vscode-live-sass-compiler#97]
Hello there

Thank you for keeping this useful extension going.
It seems that sass variables inside a css variable are being ignored and not processed:

`$bg-color: blue;`

`html {`
`  background-color: var(--background-color);`

`  &:root {`
`    --background-color: $bg-color;`
`}`
` }`

in the browser this leads to:
`html:root {
    --background-color: $bg-color;
`
instead of `--background-color: blue;`

I just tested the version 5.1.0-rc.1, same there.

**Comment by glenn2223** [comment]
Please see #83. Thanks
