### ISSUE TITLE
v5.1 The default value of showOutputWindowOn does not match the docs

### ISSUE THREAD

**Issue by StoyanDimitrov** [glenn2223/vscode-live-sass-compiler#98]
The [sources says](/glenn2223/vscode-live-sass-compiler/blob/ahead/src/helper.ts#L41-L42) that too.

**Comment by glenn2223** [comment]
Sorry I don't follow. As you can see from the [docs](https://github.com/glenn2223/vscode-live-sass-compiler/blob/ahead/docs/settings.md#livesasscompilesettingsshowoutputwindowon), it's supposed to be "Information" by default

**Comment by StoyanDimitrov** [comment]
Oh, no, I'm sorry. It could be some metadata, describing the property or leftover from the release version but take a look at the screenshot.
![default-settings](https://user-images.githubusercontent.com/10962709/123874144-30c37580-d927-11eb-90c8-deaa9e2cb8ba.png)
It's a filtered User Settings (viewed as JSON) and in the line above the property says "Default is 'Warning'".

In the UI view of the Settings the same text could be read but the dropdown points "Information" as default.
![ui-version](https://user-images.githubusercontent.com/10962709/123874736-235abb00-d928-11eb-98d8-46d0cd0d0c6c.png)

**Comment by glenn2223** [comment]
Ahh yes, I see it. Thanks for pointing it out!

**Comment by glenn2223** [comment]
Fix applied in [v5.1.0-rc.2](https://github.com/glenn2223/vscode-live-sass-compiler/releases/tag/v5.1.0-rc.2)
